// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type HSOUNDSCRIPTHANDLE = ::std::os::raw::c_short;
pub type PLAYER_ANIM = ::std::os::raw::c_int;
pub type USE_TYPE = ::std::os::raw::c_int;
pub const PLAYER_ANIM_PLAYER_ATTACK1: PLAYER_ANIM = 5;
pub const PLAYER_ANIM_PLAYER_DIE: PLAYER_ANIM = 4;
pub const PLAYER_ANIM_PLAYER_IDLE: PLAYER_ANIM = 0;
pub const PLAYER_ANIM_PLAYER_IN_VEHICLE: PLAYER_ANIM = 6;
pub const PLAYER_ANIM_PLAYER_JUMP: PLAYER_ANIM = 2;
pub const PLAYER_ANIM_PLAYER_LEAVE_AIMING: PLAYER_ANIM = 9;
pub const PLAYER_ANIM_PLAYER_RELOAD: PLAYER_ANIM = 7;
pub const PLAYER_ANIM_PLAYER_START_AIMING: PLAYER_ANIM = 8;
pub const PLAYER_ANIM_PLAYER_SUPERJUMP: PLAYER_ANIM = 3;
pub const PLAYER_ANIM_PLAYER_WALK: PLAYER_ANIM = 1;
pub const USE_TYPE_USE_OFF: USE_TYPE = 0;
pub const USE_TYPE_USE_ON: USE_TYPE = 1;
pub const USE_TYPE_USE_SET: USE_TYPE = 2;
pub const USE_TYPE_USE_TOGGLE: USE_TYPE = 3;
#[repr(C)]
#[derive(Debug)]
pub struct EmitSound_t {
    pub m_nChannel: ::std::os::raw::c_int,
    pub m_pSoundName: *const ::std::os::raw::c_char,
    pub m_flVolume: f32,
    pub m_SoundLevel: soundlevel_t,
    pub m_nFlags: ::std::os::raw::c_int,
    pub m_nPitch: ::std::os::raw::c_int,
    pub m_nSpecialDSP: ::std::os::raw::c_int,
    pub m_pOrigin: *const Vector,
    ///< NOT DURATION, but rather, some absolute time in the future until which this sound should be delayed
    pub m_flSoundTime: f32,
    pub m_pflSoundDuration: *mut f32,
    pub m_bEmitCloseCaption: bool,
    pub m_bWarnOnMissingCloseCaption: bool,
    pub m_bWarnOnDirectWaveReference: bool,
    pub m_nSpeakerEntity: ::std::os::raw::c_int,
    ///< Actual sound origin(s) (can be multiple if sound routed through speaker entity(ies) )
    pub m_UtlVecSoundOrigin: CUtlVector<Vector, CUtlMemory<Vector>>,
    pub m_hSoundScriptHandle: HSOUNDSCRIPTHANDLE,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FireBulletsInfo_t {
    pub m_iShots: ::std::os::raw::c_int,
    pub m_vecSrc: Vector,
    pub m_vecDirShooting: Vector,
    pub m_vecSpread: Vector,
    pub m_flDistance: f32,
    pub m_iAmmoType: ::std::os::raw::c_int,
    pub m_iTracerFreq: ::std::os::raw::c_int,
    pub m_flDamage: f32,
    pub m_iPlayerDamage: ::std::os::raw::c_int,
    pub m_nFlags: ::std::os::raw::c_int,
    pub m_flDamageForceScale: f32,
    pub m_pAttacker: *mut CBaseEntity,
    pub m_pAdditionalIgnoreEnt: *mut CBaseEntity,
    pub m_bPrimaryAttack: bool,
    pub m_bUseServerRandomSeed: bool,
}
include!("layout_assertions.rs");
