// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type TraceType_t = ::std::os::raw::c_uint;
pub const TraceType_t_TRACE_ENTITIES_ONLY: TraceType_t = 2;
pub const TraceType_t_TRACE_EVERYTHING: TraceType_t = 0;
pub const TraceType_t_TRACE_EVERYTHING_FILTER_PROPS: TraceType_t = 3;
pub const TraceType_t_TRACE_WORLD_ONLY: TraceType_t = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IEngineTrace {
    pub vtable_: *const IEngineTrace__bindgen_vtable,
}
#[repr(C)]
pub struct IEngineTrace__bindgen_vtable {
    pub IEngineTrace_GetPointContents: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
        arg3: *mut *mut IHandleEntity,
    ) -> ::std::os::raw::c_int,
    pub IEngineTrace_GetPointContents_Collideable: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *mut ICollideable,
        arg3: *const Vector,
    ) -> ::std::os::raw::c_int,
    pub IEngineTrace_ClipRayToEntity: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut IHandleEntity,
        arg5: *mut trace_t,
    ),
    pub IEngineTrace_ClipRayToCollideable: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut ICollideable,
        arg5: *mut trace_t,
    ),
    pub IEngineTrace_TraceRay: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut ITraceFilter,
        arg5: *mut trace_t,
    ),
    pub IEngineTrace_SetupLeafAndEntityListRay: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Ray_t,
        arg3: *mut CTraceListData,
    ),
    pub IEngineTrace_SetupLeafAndEntityListBox: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: *mut CTraceListData,
    ),
    pub IEngineTrace_TraceRayAgainstLeafAndEntityList: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Ray_t,
        arg3: *mut CTraceListData,
        arg4: ::std::os::raw::c_uint,
        arg5: *mut ITraceFilter,
        arg6: *mut trace_t,
    ),
    pub IEngineTrace_SweepCollideable: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *mut ICollideable,
        arg3: *const Vector,
        arg4: *const Vector,
        arg5: *const QAngle,
        arg6: ::std::os::raw::c_uint,
        arg7: *mut ITraceFilter,
        arg8: *mut trace_t,
    ),
    pub IEngineTrace_EnumerateEntities: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Ray_t,
        arg3: bool,
        arg4: *mut IEntityEnumerator,
    ),
    pub IEngineTrace_EnumerateEntities1: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: *mut IEntityEnumerator,
    ),
    pub IEngineTrace_GetCollideable: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *mut IHandleEntity,
    ) -> *mut ICollideable,
    pub IEngineTrace_GetStatByIndex: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: ::std::os::raw::c_int,
        arg3: bool,
    ) -> ::std::os::raw::c_int,
    pub IEngineTrace_GetBrushesInAABB: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: *mut CUtlVector<::std::os::raw::c_int, CUtlMemory<::std::os::raw::c_int>>,
        arg5: ::std::os::raw::c_int,
    ),
    pub IEngineTrace_GetCollidableFromDisplacementsInAABB: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
        arg3: *const Vector,
    ) -> *mut CPhysCollide,
    pub IEngineTrace_GetBrushInfo: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: ::std::os::raw::c_int,
        arg3: *mut CUtlVector<Vector4D, CUtlMemory<Vector4D>>,
        arg4: *mut ::std::os::raw::c_int,
    ) -> bool,
    pub IEngineTrace_PointOutsideWorld: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
    ) -> bool,
    pub IEngineTrace_GetLeafContainingPoint: unsafe extern "C" fn(
        arg1: *mut IEngineTrace,
        arg2: *const Vector,
    ) -> ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IEntityEnumerator {
    pub vtable_: *const IEntityEnumerator__bindgen_vtable,
}
#[repr(C)]
pub struct IEntityEnumerator__bindgen_vtable {
    pub IEntityEnumerator_EnumEntity: unsafe extern "C" fn(
        arg1: *mut IEntityEnumerator,
        arg2: *mut IHandleEntity,
    ) -> bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ITraceFilter {
    pub vtable_: *const ITraceFilter__bindgen_vtable,
}
#[repr(C)]
pub struct ITraceFilter__bindgen_vtable {
    pub ITraceFilter_ShouldHitEntity: unsafe extern "C" fn(
        arg1: *mut ITraceFilter,
        arg2: *mut IHandleEntity,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub ITraceFilter_GetTraceType: unsafe extern "C" fn(
        arg1: *const ITraceFilter,
    ) -> TraceType_t,
}
include!("layout_assertions.rs");
