// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of INetworkStringTable",
    ][::std::mem::size_of::<INetworkStringTable>() - 8usize];
    [
        "Alignment of INetworkStringTable",
    ][::std::mem::align_of::<INetworkStringTable>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of INetworkStringTableContainer",
    ][::std::mem::size_of::<INetworkStringTableContainer>() - 8usize];
    [
        "Alignment of INetworkStringTableContainer",
    ][::std::mem::align_of::<INetworkStringTableContainer>() - 8usize];
};
