// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CFogController"][::std::mem::size_of::<CFogController>() - 1280usize];
    ["Alignment of CFogController"][::std::mem::align_of::<CFogController>() - 8usize];
    [
        "Offset of field: CFogController::m_fog",
    ][::std::mem::offset_of!(CFogController, m_fog) - 1200usize];
    [
        "Offset of field: CFogController::m_bUseAngles",
    ][::std::mem::offset_of!(CFogController, m_bUseAngles) - 1272usize];
    [
        "Offset of field: CFogController::m_iChangedVariables",
    ][::std::mem::offset_of!(CFogController, m_iChangedVariables) - 1276usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CFogController_NetworkVar_m_fog",
    ][::std::mem::size_of::<CFogController_NetworkVar_m_fog>() - 72usize];
    [
        "Alignment of CFogController_NetworkVar_m_fog",
    ][::std::mem::align_of::<CFogController_NetworkVar_m_fog>() - 8usize];
};
