// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type stepsoundtimes_t = ::std::os::raw::c_uint;
pub const stepsoundtimes_t_STEPSOUNDTIME_NORMAL: stepsoundtimes_t = 0;
pub const stepsoundtimes_t_STEPSOUNDTIME_ON_LADDER: stepsoundtimes_t = 1;
pub const stepsoundtimes_t_STEPSOUNDTIME_WATER_FOOT: stepsoundtimes_t = 3;
pub const stepsoundtimes_t_STEPSOUNDTIME_WATER_KNEE: stepsoundtimes_t = 2;
#[repr(C)]
pub struct autoaim_params_t {
    pub m_vecAutoAimDir: Vector,
    pub m_vecAutoAimPoint: Vector,
    pub m_hAutoAimEntity: EHANDLE,
    pub m_bAutoAimAssisting: bool,
    pub m_bOnTargetNatural: bool,
    pub m_fScale: f32,
    pub m_fMaxDist: f32,
}
include!("layout_assertions.rs");
