// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CItem"][::std::mem::size_of::<CItem>() - 1672usize];
    ["Alignment of CItem"][::std::mem::align_of::<CItem>() - 8usize];
    [
        "Offset of field: CItem::m_flNextResetCheckTime",
    ][::std::mem::offset_of!(CItem, m_flNextResetCheckTime) - 1568usize];
    [
        "Offset of field: CItem::m_bActivateWhenAtRest",
    ][::std::mem::offset_of!(CItem, m_bActivateWhenAtRest) - 1572usize];
    [
        "Offset of field: CItem::m_OnPlayerTouch",
    ][::std::mem::offset_of!(CItem, m_OnPlayerTouch) - 1576usize];
    [
        "Offset of field: CItem::m_OnCacheInteraction",
    ][::std::mem::offset_of!(CItem, m_OnCacheInteraction) - 1608usize];
    [
        "Offset of field: CItem::m_vOriginalSpawnOrigin",
    ][::std::mem::offset_of!(CItem, m_vOriginalSpawnOrigin) - 1640usize];
    [
        "Offset of field: CItem::m_vOriginalSpawnAngles",
    ][::std::mem::offset_of!(CItem, m_vOriginalSpawnAngles) - 1652usize];
    [
        "Offset of field: CItem::m_pConstraint",
    ][::std::mem::offset_of!(CItem, m_pConstraint) - 1664usize];
};
