// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Quaternion48 {
    pub _bindgen_align: [u16; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 6usize]>,
}
impl Quaternion48 {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        x: ::std::os::raw::c_ushort,
        y: ::std::os::raw::c_ushort,
        z: ::std::os::raw::c_ushort,
        wneg: ::std::os::raw::c_ushort,
    ) -> __BindgenBitfieldUnit<[u8; 6usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 6usize]> = Default::default();
        __bindgen_bitfield_unit
            .set_const::<
                0usize,
                16u8,
            >({
                let x: u16 = unsafe { ::std::mem::transmute(x) };
                x as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                16usize,
                16u8,
            >({
                let y: u16 = unsafe { ::std::mem::transmute(y) };
                y as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                32usize,
                15u8,
            >({
                let z: u16 = unsafe { ::std::mem::transmute(z) };
                z as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                47usize,
                1u8,
            >({
                let wneg: u16 = unsafe { ::std::mem::transmute(wneg) };
                wneg as u64
            });
        __bindgen_bitfield_unit
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_wneg(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<47usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_wneg_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 6usize],
            >>::raw_set_const::<
                47usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_x(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 16u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_x_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 6usize],
            >>::raw_set_const::<
                0usize,
                16u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_y(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<16usize, 16u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_y_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 6usize],
            >>::raw_set_const::<
                16usize,
                16u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_z(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<32usize, 15u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_z_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 6usize],
            >>::raw_set_const::<
                32usize,
                15u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn wneg(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<47usize, 1u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn wneg_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 6usize],
                >>::raw_get_const::<
                    47usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn x(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<0usize, 16u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn x_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 6usize],
                >>::raw_get_const::<
                    0usize,
                    16u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn y(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<16usize, 16u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn y_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 6usize],
                >>::raw_get_const::<
                    16usize,
                    16u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn z(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<32usize, 15u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn z_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 6usize],
                >>::raw_get_const::<
                    32usize,
                    15u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Quaternion64 {
    pub _bindgen_align: [u64; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 8usize]>,
}
impl Quaternion64 {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        x: uint64,
        y: uint64,
        z: uint64,
        wneg: uint64,
    ) -> __BindgenBitfieldUnit<[u8; 8usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 8usize]> = Default::default();
        __bindgen_bitfield_unit
            .set_const::<
                0usize,
                21u8,
            >({
                let x: u64 = unsafe { ::std::mem::transmute(x) };
                x as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                21usize,
                21u8,
            >({
                let y: u64 = unsafe { ::std::mem::transmute(y) };
                y as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                42usize,
                21u8,
            >({
                let z: u64 = unsafe { ::std::mem::transmute(z) };
                z as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                63usize,
                1u8,
            >({
                let wneg: u64 = unsafe { ::std::mem::transmute(wneg) };
                wneg as u64
            });
        __bindgen_bitfield_unit
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_wneg(&mut self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<63usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_wneg_raw(this: *mut Self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 8usize],
            >>::raw_set_const::<
                63usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_x(&mut self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 21u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_x_raw(this: *mut Self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 8usize],
            >>::raw_set_const::<
                0usize,
                21u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_y(&mut self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<21usize, 21u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_y_raw(this: *mut Self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 8usize],
            >>::raw_set_const::<
                21usize,
                21u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_z(&mut self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<42usize, 21u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_z_raw(this: *mut Self, val: uint64) {
        unsafe {
            let val: u64 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 8usize],
            >>::raw_set_const::<
                42usize,
                21u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn wneg(&self) -> uint64 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<63usize, 1u8>() as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn wneg_raw(this: *const Self) -> uint64 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 8usize],
                >>::raw_get_const::<
                    63usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn x(&self) -> uint64 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<0usize, 21u8>() as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn x_raw(this: *const Self) -> uint64 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 8usize],
                >>::raw_get_const::<
                    0usize,
                    21u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn y(&self) -> uint64 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<21usize, 21u8>() as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn y_raw(this: *const Self) -> uint64 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 8usize],
                >>::raw_get_const::<
                    21usize,
                    21u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn z(&self) -> uint64 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<42usize, 21u8>() as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn z_raw(this: *const Self) -> uint64 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 8usize],
                >>::raw_get_const::<
                    42usize,
                    21u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u64,
            )
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Vector48 {
    pub x: float16,
    pub y: float16,
    pub z: float16,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct float16 {
    pub m_storage: float16_float16bits,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union float16_float16bits {
    pub rawWord: ::std::os::raw::c_ushort,
    pub bits: float16_float16bits__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float16_float16bits__bindgen_ty_1 {
    pub _bindgen_align: [u16; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize]>,
}
impl float16_float16bits__bindgen_ty_1 {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn biased_exponent(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<10usize, 5u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn biased_exponent_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 2usize],
                >>::raw_get_const::<
                    10usize,
                    5u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn mantissa(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<0usize, 10u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn mantissa_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 2usize],
                >>::raw_get_const::<
                    0usize,
                    10u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        mantissa: ::std::os::raw::c_ushort,
        biased_exponent: ::std::os::raw::c_ushort,
        sign: ::std::os::raw::c_ushort,
    ) -> __BindgenBitfieldUnit<[u8; 2usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 2usize]> = Default::default();
        __bindgen_bitfield_unit
            .set_const::<
                0usize,
                10u8,
            >({
                let mantissa: u16 = unsafe { ::std::mem::transmute(mantissa) };
                mantissa as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                10usize,
                5u8,
            >({
                let biased_exponent: u16 = unsafe {
                    ::std::mem::transmute(biased_exponent)
                };
                biased_exponent as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                15usize,
                1u8,
            >({
                let sign: u16 = unsafe { ::std::mem::transmute(sign) };
                sign as u64
            });
        __bindgen_bitfield_unit
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_biased_exponent(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<10usize, 5u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_biased_exponent_raw(
        this: *mut Self,
        val: ::std::os::raw::c_ushort,
    ) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 2usize],
            >>::raw_set_const::<
                10usize,
                5u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_mantissa(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 10u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_mantissa_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 2usize],
            >>::raw_set_const::<
                0usize,
                10u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_sign(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<15usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_sign_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 2usize],
            >>::raw_set_const::<
                15usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn sign(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<15usize, 1u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn sign_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 2usize],
                >>::raw_get_const::<
                    15usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union float16_float32bits {
    pub rawFloat: f32,
    pub bits: float16_float32bits__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct float16_float32bits__bindgen_ty_1 {
    pub _bindgen_align: [u32; 0],
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 4usize]>,
}
impl float16_float32bits__bindgen_ty_1 {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn biased_exponent(&self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<23usize, 8u8>() as u32)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn biased_exponent_raw(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 4usize],
                >>::raw_get_const::<
                    23usize,
                    8u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u32,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn mantissa(&self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<0usize, 23u8>() as u32)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn mantissa_raw(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 4usize],
                >>::raw_get_const::<
                    0usize,
                    23u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u32,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        mantissa: ::std::os::raw::c_uint,
        biased_exponent: ::std::os::raw::c_uint,
        sign: ::std::os::raw::c_uint,
    ) -> __BindgenBitfieldUnit<[u8; 4usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 4usize]> = Default::default();
        __bindgen_bitfield_unit
            .set_const::<
                0usize,
                23u8,
            >({
                let mantissa: u32 = unsafe { ::std::mem::transmute(mantissa) };
                mantissa as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                23usize,
                8u8,
            >({
                let biased_exponent: u32 = unsafe {
                    ::std::mem::transmute(biased_exponent)
                };
                biased_exponent as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                31usize,
                1u8,
            >({
                let sign: u32 = unsafe { ::std::mem::transmute(sign) };
                sign as u64
            });
        __bindgen_bitfield_unit
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_biased_exponent(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<23usize, 8u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_biased_exponent_raw(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 4usize],
            >>::raw_set_const::<
                23usize,
                8u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_mantissa(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 23u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_mantissa_raw(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 4usize],
            >>::raw_set_const::<
                0usize,
                23u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_sign(&mut self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<31usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_sign_raw(this: *mut Self, val: ::std::os::raw::c_uint) {
        unsafe {
            let val: u32 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 4usize],
            >>::raw_set_const::<
                31usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn sign(&self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<31usize, 1u8>() as u32)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn sign_raw(this: *const Self) -> ::std::os::raw::c_uint {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 4usize],
                >>::raw_get_const::<
                    31usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u32,
            )
        }
    }
}
include!("layout_assertions.rs");
