// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of IEconItemAttributeIterator",
    ][::std::mem::size_of::<IEconItemAttributeIterator>() - 8usize];
    [
        "Alignment of IEconItemAttributeIterator",
    ][::std::mem::align_of::<IEconItemAttributeIterator>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IEconItemInterface"][::std::mem::size_of::<IEconItemInterface>() - 8usize];
    [
        "Alignment of IEconItemInterface",
    ][::std::mem::align_of::<IEconItemInterface>() - 8usize];
};
