// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CBaseCombatWeapon_BaseClass = CBaseAnimating;
pub type CBaseCombatWeapon_CBaseCombatCharacterHandle = CHandle;
#[repr(C)]
pub struct CBaseCombatWeapon {
    pub _base: CBaseAnimating,
    pub m_hOwner: CNetworkVarBase<CBaseCombatWeapon_CBaseCombatCharacterHandle>,
    pub m_nViewModelIndex: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_flNextPrimaryAttack: CNetworkVarBase<f32>,
    pub m_flNextSecondaryAttack: CNetworkVarBase<f32>,
    pub m_flTimeWeaponIdle: CNetworkVarBase<f32>,
    pub m_bInReload: bool,
    pub m_bFireOnEmpty: bool,
    pub m_bFiringWholeClip: bool,
    pub m_iViewModelIndex: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_iWorldModelIndex: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_flNextEmptySoundTime: f32,
    pub m_Activity: Activity,
    pub m_nIdealSequence: ::std::os::raw::c_int,
    pub m_IdealActivity: Activity,
    pub m_bRemoveable: bool,
    pub m_iPrimaryAmmoCount: ::std::os::raw::c_int,
    pub m_iSecondaryAmmoCount: ::std::os::raw::c_int,
    pub m_iState: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_iszName: string_t,
    pub m_iPrimaryAmmoType: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_iSecondaryAmmoType: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_iClip1: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_iClip2: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_bFiresUnderwater: bool,
    pub m_bAltFiresUnderwater: bool,
    pub m_fMinRange1: f32,
    pub m_fMinRange2: f32,
    pub m_fMaxRange1: f32,
    pub m_fMaxRange2: f32,
    pub m_bReloadsSingly: bool,
    pub m_fFireDuration: f32,
    pub m_iSubType: ::std::os::raw::c_int,
    pub m_flUnlockTime: f32,
    pub m_hLocker: EHANDLE,
    pub m_bFlipViewModel: CNetworkVarBase<bool>,
    pub m_hWeaponFileInfo: WEAPON_FILE_INFO_HANDLE,
    pub m_pConstraint: *mut IPhysicsConstraint,
    pub m_iAltFireHudHintCount: ::std::os::raw::c_int,
    pub m_iReloadHudHintCount: ::std::os::raw::c_int,
    pub m_bAltFireHudHintDisplayed: bool,
    pub m_bReloadHudHintDisplayed: bool,
    pub m_flHudHintPollTime: f32,
    pub m_flHudHintMinDisplayTime: f32,
    pub m_nCustomViewmodelModelIndex: CNetworkVarBase<::std::os::raw::c_short>,
    pub m_bSoundsEnabled: bool,
    pub m_OnPlayerUse: COutputEvent,
    pub m_OnPlayerPickup: COutputEvent,
    pub m_OnNPCPickup: COutputEvent,
    pub m_OnCacheInteraction: COutputEvent,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_bFlipViewModel {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_flNextPrimaryAttack {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_flNextSecondaryAttack {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_flTimeWeaponIdle {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_hOwner {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iClip1 {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iClip2 {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iPrimaryAmmoType {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iSecondaryAmmoType {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iState {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iViewModelIndex {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_iWorldModelIndex {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_nCustomViewmodelModelIndex {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseCombatWeapon_NetworkVar_m_nViewModelIndex {
    pub _address: u8,
}
#[repr(C)]
pub struct CBaseCombatWeapon__bindgen_vtable {
    pub CBaseCombatWeapon_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void,
    pub CBaseCombatWeapon_SetRefEHandle: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CBaseHandle,
    ),
    pub CBaseCombatWeapon_GetRefEHandle: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CBaseHandle,
    pub CBaseCombatWeapon_GetCollideable: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut ICollideable,
    pub CBaseCombatWeapon_GetNetworkable: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut IServerNetworkable,
    pub CBaseCombatWeapon_GetBaseEntity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseEntity,
    pub CBaseCombatWeapon_GetModelIndex: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    /// C++ returns `::string_t` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetModelName: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut string_t,
    ) -> *mut string_t,
    pub CBaseCombatWeapon_SetModelIndex: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_GetServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut ServerClass,
    pub CBaseCombatWeapon_YouForgotToImplementOrDeclareServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetDataDescMap: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut datamap_t,
    pub CBaseCombatWeapon_GetScriptDesc: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut ScriptClassDesc_t,
    pub CBaseCombatWeapon_SetModelIndexOverride: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_TestCollision: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CBaseCombatWeapon_TestHitboxes: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CBaseCombatWeapon_ComputeWorldSpaceSurroundingBox: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub CBaseCombatWeapon_ShouldCollide: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseCombatWeapon_SetOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_SetScriptOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: HSCRIPT,
    ),
    pub CBaseCombatWeapon_ShouldTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CCheckTransmitInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_UpdateTransmitState: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_SetTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CCheckTransmitInfo,
        arg3: bool,
    ),
    pub CBaseCombatWeapon_GetTracerType: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_Spawn: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_Precache: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_SetModel: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_OnNewModel: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CStudioHdr,
    pub CBaseCombatWeapon_PostConstructor: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_PostClientActive: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_ParseMapData: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CEntityMapData,
    ),
    pub CBaseCombatWeapon_KeyValue2: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const Vector,
    ) -> bool,
    pub CBaseCombatWeapon_KeyValue1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
        arg3: f32,
    ) -> bool,
    pub CBaseCombatWeapon_KeyValue: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> bool,
    pub CBaseCombatWeapon_GetKeyValue: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseCombatWeapon_Activate: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_SetParent: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_ObjectCaps: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    /// C++ takes `::variant_t` by value. `arg5` points to a temporary copy the caller makes; the callee may modify it, and the callee destroys it.
    pub CBaseCombatWeapon_AcceptInput: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut CBaseEntity,
        arg4: *mut CBaseEntity,
        arg5: *mut variant_t,
        arg6: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseCombatWeapon_GetInputDispatchEffectPosition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut Vector,
        arg4: *mut QAngle,
    ),
    pub CBaseCombatWeapon_DrawDebugGeometryOverlays: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_DrawDebugTextOverlays: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_Save: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ISave,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_Restore: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut IRestore,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_ShouldSavePhysics: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_OnSave: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut IEntitySaveUtils,
    ),
    pub CBaseCombatWeapon_OnRestore: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_RequiredEdictIndex: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_MoveDone: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_Think: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_NetworkStateChanged_m_nNextThinkTick1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_nNextThinkTick: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_GetBaseAnimating: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseAnimating,
    pub CBaseCombatWeapon_GetResponseSystem: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut IResponseSystem,
    pub CBaseCombatWeapon_DispatchResponse: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_Classify: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> Class_T,
    pub CBaseCombatWeapon_DeathNotice: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_ShouldAttractAutoAim: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_GetAutoAimRadius: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetAutoAimCenter: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_GetBeamTraceFilter: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut ITraceFilter,
    pub CBaseCombatWeapon_PassesDamageFilter: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CBaseCombatWeapon_TraceAttack: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CTakeDamageInfo,
        arg3: *const Vector,
        arg4: *mut trace_t,
        arg5: *mut CDmgAccumulator,
    ),
    pub CBaseCombatWeapon_CanBeHitByMeleeAttack: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_OnTakeDamage: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_AdjustDamageDirection: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CTakeDamageInfo,
        arg3: *mut Vector,
        arg4: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_TakeHealth: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_IsAlive: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Event_Killed: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CTakeDamageInfo,
    ),
    pub CBaseCombatWeapon_Event_KilledOther: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
        arg3: *const CTakeDamageInfo,
    ),
    pub CBaseCombatWeapon_BloodColor: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_IsTriggered: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_IsNPC: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_MyCombatCharacterPointer: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseCombatCharacter,
    pub CBaseCombatWeapon_MyNextBotPointer: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut INextBot,
    pub CBaseCombatWeapon_GetDelay: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_IsMoving: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_DamageDecal: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_DecalTrace: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut trace_t,
        arg3: *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_ImpactTrace: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
        arg4: *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_OnControls: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_HasTarget: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: string_t,
    ) -> bool,
    pub CBaseCombatWeapon_IsPlayer: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsNetClient: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsTemplate: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsBaseObject: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsBaseTrain: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsCombatItem: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsBaseCombatWeapon: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsWearable: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_MyCombatWeaponPointer: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseCombatWeapon,
    pub CBaseCombatWeapon_GetServerVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut IServerVehicle,
    pub CBaseCombatWeapon_IsViewable: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_ChangeTeam: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_OnEntityEvent: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: EntityEvent_t,
        arg3: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_CanStandOn1: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut edict_t,
    ) -> bool,
    pub CBaseCombatWeapon_CanStandOn: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_GetEnemy1: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *mut CBaseEntity,
    pub CBaseCombatWeapon_GetEnemy: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseEntity,
    pub CBaseCombatWeapon_Use: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
        arg3: *mut CBaseEntity,
        arg4: USE_TYPE,
        arg5: f32,
    ),
    pub CBaseCombatWeapon_StartTouch: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_Touch: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_EndTouch: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_StartBlocked: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_Blocked: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_EndBlocked: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_PhysicsSimulate: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_UpdateOnRemove: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_StopLoopingSounds: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_SUB_AllowedToFade: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Teleport: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: *const Vector,
    ),
    pub CBaseCombatWeapon_NotifySystemEvent: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
        arg3: notify_system_event_t,
        arg4: *const notify_system_event_params_t,
    ),
    pub CBaseCombatWeapon_MakeTracer: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
        arg3: *const trace_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_GetTracerAttachment: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_FireBullets: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const FireBulletsInfo_t,
    ),
    pub CBaseCombatWeapon_DoImpactEffect: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_ModifyFireBulletsDamage: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CTakeDamageInfo,
    ),
    pub CBaseCombatWeapon_Respawn: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseEntity,
    pub CBaseCombatWeapon_IsLockedByMaster: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetMaxHealth: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_ModifyOrAppendCriteria: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut AI_CriteriaSet,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_iMaxHealth1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_iMaxHealth: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_iHealth1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_iHealth: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_lifeState1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_lifeState: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_takedamage1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_takedamage: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_RunVScripts: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_GetDamageType: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetDamage: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_SetDamage: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ),
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_EyePosition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_EyeAngles: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *const QAngle,
    pub CBaseCombatWeapon_LocalEyeAngles: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *const QAngle,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_EarPosition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_BodyTarget: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: *const Vector,
        arg4: bool,
    ) -> *mut Vector,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_HeadTarget: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: *const Vector,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_GetVectors: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut Vector,
    ),
    pub CBaseCombatWeapon_GetViewOffset: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const Vector,
    pub CBaseCombatWeapon_SetViewOffset: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
    ),
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetSmoothedVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_GetVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub CBaseCombatWeapon_FVisible1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_FVisible: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_CanBeSeenBy: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CAI_BaseNPC,
    ) -> bool,
    pub CBaseCombatWeapon_GetAttackDamageScale: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseCombatWeapon_GetReceivedDamageScale: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseCombatWeapon_GetGroundVelocityToApply: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
    ),
    pub CBaseCombatWeapon_PhysicsSplash: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: f32,
        arg5: f32,
    ) -> bool,
    pub CBaseCombatWeapon_Splash: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_WorldSpaceCenter: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const Vector,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetSoundEmissionOrigin: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_ModifyEmitSoundParams: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut EmitSound_t,
    ),
    pub CBaseCombatWeapon_IsDeflectable: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Deflected: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
        arg3: *mut Vector,
    ),
    pub CBaseCombatWeapon_CreateVPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_ForceVPhysicsCollide: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseCombatWeapon_VPhysicsDestroyObject: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_VPhysicsUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut IPhysicsObject,
    ),
    pub CBaseCombatWeapon_VPhysicsTakeDamage: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_VPhysicsShadowCollision: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CBaseCombatWeapon_VPhysicsShadowUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut IPhysicsObject,
    ),
    pub CBaseCombatWeapon_VPhysicsCollision: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CBaseCombatWeapon_VPhysicsFriction: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut IPhysicsObject,
        arg3: f32,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_UpdatePhysicsShadowToCurrentPosition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ),
    pub CBaseCombatWeapon_VPhysicsGetObjectList: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut *mut IPhysicsObject,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_VPhysicsIsFlesh: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_HasPhysicsAttacker: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ) -> *mut CBasePlayer,
    pub CBaseCombatWeapon_PhysicsSolidMaskForEntity: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_uint,
    pub CBaseCombatWeapon_ResolveFlyCollisionCustom: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut trace_t,
        arg3: *mut Vector,
    ),
    pub CBaseCombatWeapon_PerformCustomPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut QAngle,
        arg5: *mut QAngle,
    ),
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetStepOrigin: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    /// C++ returns `::QAngle` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetStepAngles: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: *mut QAngle,
    ) -> *mut QAngle,
    pub CBaseCombatWeapon_ShouldDrawWaterImpacts: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_NetworkStateChanged_m_fFlags1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_fFlags: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_nWaterLevel1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_nWaterLevel: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_hGroundEntity1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_hGroundEntity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_vecBaseVelocity1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_vecBaseVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_flFriction1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_flFriction: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_vecVelocity1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_vecVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_vecViewOffset1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseCombatWeapon_NetworkStateChanged_m_vecViewOffset: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_ShouldBlockNav: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_ShouldForceTransmitsForTeam: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseCombatWeapon_IsTruceValidForEnt: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_BCanCallVote: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetIdealSpeed: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_GetIdealAccel: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_StudioFrameAdvance: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_SetSequence: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_IsActivityFinished: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetSequenceGroundSpeed: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CStudioHdr,
        arg3: ::std::os::raw::c_int,
    ) -> f32,
    pub CBaseCombatWeapon_ClampRagdollForce: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
        arg3: *mut Vector,
    ),
    pub CBaseCombatWeapon_BecomeRagdollOnClient: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseCombatWeapon_IsRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_CanBecomeRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetSkeleton: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CStudioHdr,
        arg3: *mut Vector,
        arg4: *mut Quaternion,
        arg5: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_GetBoneTransform: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: *mut matrix3x4_t,
    ),
    pub CBaseCombatWeapon_SetupBones: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut matrix3x4_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_CalculateIKLocks: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ),
    pub CBaseCombatWeapon_DispatchAnimEvents: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseAnimating,
    ),
    pub CBaseCombatWeapon_HandleAnimEvent: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut animevent_t,
    ),
    pub CBaseCombatWeapon_PopulatePoseParameters: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_GetAttachment: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: *mut matrix3x4_t,
    ) -> bool,
    pub CBaseCombatWeapon_InitBoneControllers: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetGroundSpeedVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_RefreshCollisionBounds: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_Ignite: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: bool,
        arg4: f32,
        arg5: bool,
    ),
    pub CBaseCombatWeapon_IgniteLifetime: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ),
    pub CBaseCombatWeapon_IgniteNumHitboxFires: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_IgniteHitboxFireScale: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ),
    pub CBaseCombatWeapon_Extinguish: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_SetLightingOriginRelative: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_SetLightingOrigin: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_IsPredicted: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetSubType: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_SetSubType: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_Equip: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseCombatCharacter,
    ),
    pub CBaseCombatWeapon_Drop: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
    ),
    pub CBaseCombatWeapon_UpdateClientData: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBasePlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_IsAllowedToSwitch: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_CanBeSelected: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_VisibleInWeaponSelection: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_HasAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_SetPickupTouch: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_DefaultTouch: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_GiveTo: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseCombatWeapon_ShouldDisplayAltFireHUDHint: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_DisplayAltFireHudHint: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_RescindAltFireHudHint: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_ShouldDisplayReloadHUDHint: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_DisplayReloadHudHint: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_RescindReloadHudHint: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_SetViewModelIndex: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_SendWeaponAnim: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseCombatWeapon_SendViewModelAnim: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_SetViewModel: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_HasWeaponIdleTimeElapsed: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_SetWeaponIdleTime: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
    ),
    pub CBaseCombatWeapon_GetWeaponIdleTime: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_HasAnyAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_HasPrimaryAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_HasSecondaryAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_CanHolster: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_DefaultDeploy: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
        arg5: *mut ::std::os::raw::c_char,
    ) -> bool,
    pub CBaseCombatWeapon_CanDeploy: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Deploy: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Holster: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetLastWeapon: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CBaseCombatWeapon,
    pub CBaseCombatWeapon_SetWeaponVisible: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: bool,
    ),
    pub CBaseCombatWeapon_IsWeaponVisible: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_ReloadOrSwitchWeapons: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_OnActiveStateChanged: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseCombatWeapon_HolsterOnDetach: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsHolstered: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Detach: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_ItemPreFrame: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_ItemPostFrame: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_ItemBusyFrame: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_ItemHolsterFrame: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_WeaponIdle: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_HandleFireOnEmpty: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_CanPerformSecondaryAttack: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_ShouldBlockPrimaryFire: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_IsWeaponZoomed: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_CheckReload: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_FinishReload: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_AbortReload: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_Reload: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_AutoFiresFullClip: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_UpdateAutoFire: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_PrimaryAttack: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_SecondaryAttack: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_GetPrimaryAttackActivity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> Activity,
    pub CBaseCombatWeapon_GetSecondaryAttackActivity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> Activity,
    pub CBaseCombatWeapon_GetDrawActivity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> Activity,
    pub CBaseCombatWeapon_GetDefaultAnimSpeed: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_GetBulletType: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CBaseCombatWeapon_GetBulletSpread1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut Vector,
        arg3: WeaponProficiency_t,
    ) -> *mut Vector,
    pub CBaseCombatWeapon_GetBulletSpread: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *const Vector,
    pub CBaseCombatWeapon_GetSpreadBias: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: WeaponProficiency_t,
    ) -> f32,
    pub CBaseCombatWeapon_GetFireRate: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_GetMinBurst: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetMaxBurst: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetMinRestTime: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_GetMaxRestTime: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_GetRandomBurst: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_WeaponSound: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: WeaponSound_t,
        arg3: f32,
    ),
    pub CBaseCombatWeapon_StopWeaponSound: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: WeaponSound_t,
    ),
    pub CBaseCombatWeapon_GetProficiencyValues: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *const WeaponProficiencyInfo_t,
    pub CBaseCombatWeapon_GetMaxAutoAimDeflection: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_WeaponAutoAimScale: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_StartSprinting: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_StopSprinting: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetDamage1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ) -> f32,
    pub CBaseCombatWeapon_SetActivity: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: Activity,
        arg3: f32,
    ),
    pub CBaseCombatWeapon_AddViewKick: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_GetDeathNoticeName: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut ::std::os::raw::c_char,
    pub CBaseCombatWeapon_OnPickedUp: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseCombatCharacter,
    ),
    pub CBaseCombatWeapon_AddViewmodelBob: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseViewModel,
        arg3: *mut Vector,
        arg4: *mut QAngle,
    ),
    pub CBaseCombatWeapon_CalcViewmodelBob: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_GetControlPanelInfo: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: *mut *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_GetControlPanelClassName: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
        arg3: *mut *const ::std::os::raw::c_char,
    ),
    pub CBaseCombatWeapon_ShouldShowControlPanels: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_CanBePickedUpByNPCs: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetSkinOverride: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetViewModel: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_GetWorldModel: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_GetAnimPrefix: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_GetMaxClip1: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetMaxClip2: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetDefaultClip1: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetDefaultClip2: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetWeight: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_AllowsAutoSwitchTo: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_AllowsAutoSwitchFrom: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_ForceWeaponSwitch: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetWeaponFlags: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetSlot: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetPosition: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetName: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_GetPrintName: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_GetShootSound: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseCombatWeapon_GetRumbleEffect: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_UsesClipsForAmmo1: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_UsesClipsForAmmo2: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetEncryptionKey: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *const ::std::os::raw::c_uchar,
    pub CBaseCombatWeapon_GetPrimaryAmmoType: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetSecondaryAmmoType: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_Clip1: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_Clip2: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_GetSpriteActive: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteInactive: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteAmmo: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteAmmo2: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteCrosshair: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteAutoaim: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteZoomedCrosshair: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_GetSpriteZoomedAutoaim: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> *const CHudTexture,
    pub CBaseCombatWeapon_ActivityOverride: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: Activity,
        arg3: *mut bool,
    ) -> Activity,
    pub CBaseCombatWeapon_ActivityList: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut ::std::os::raw::c_int,
    ) -> *mut acttable_t,
    pub CBaseCombatWeapon_ShouldUseLargeViewModelVROverride: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_FallInit: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_FallThink: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_Materialize: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_CheckRespawn: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ),
    pub CBaseCombatWeapon_Delete: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_Kill: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_CapabilitiesGet: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_WeaponLOSCondition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: bool,
    ) -> bool,
    pub CBaseCombatWeapon_WeaponRangeAttack1Condition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: f32,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_WeaponRangeAttack2Condition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: f32,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_WeaponMeleeAttack1Condition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: f32,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_WeaponMeleeAttack2Condition: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: f32,
        arg3: f32,
    ) -> ::std::os::raw::c_int,
    pub CBaseCombatWeapon_Operator_FrameUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseCombatCharacter,
    ),
    pub CBaseCombatWeapon_Operator_HandleAnimEvent: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut animevent_t,
        arg3: *mut CBaseCombatCharacter,
    ),
    pub CBaseCombatWeapon_Operator_ForceNPCFire: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
        arg2: *mut CBaseCombatCharacter,
        arg3: bool,
    ),
    pub CBaseCombatWeapon_GetDmgAccumulator: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> *mut CDmgAccumulator,
    pub CBaseCombatWeapon_CanLower: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Ready: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_Lower: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_HideThink: unsafe extern "C" fn(arg1: *mut CBaseCombatWeapon),
    pub CBaseCombatWeapon_CanReload: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseCombatWeapon_GetNextSecondaryAttackDelay: unsafe extern "C" fn(
        arg1: *mut CBaseCombatWeapon,
    ) -> f32,
    pub CBaseCombatWeapon_UsesCenterFireProjectile: unsafe extern "C" fn(
        arg1: *const CBaseCombatWeapon,
    ) -> bool,
}
#[repr(C)]
pub struct CDmgAccumulator {
    pub vtable_: *const CDmgAccumulator__bindgen_vtable,
    pub m_updatedInfo: CTakeDamageInfo,
    pub m_TargetsDmgInfo: __BindgenOpaqueArray8<[u8; 40usize]>,
    pub m_bActive: bool,
}
#[repr(C)]
pub struct CDmgAccumulator__bindgen_vtable {
    pub CDmgAccumulator_Start: unsafe extern "C" fn(arg1: *mut CDmgAccumulator),
    pub CDmgAccumulator_AccumulateMultiDamage: unsafe extern "C" fn(
        arg1: *mut CDmgAccumulator,
        arg2: *const CTakeDamageInfo,
        arg3: *mut CBaseEntity,
    ),
    pub CDmgAccumulator_Process: unsafe extern "C" fn(arg1: *mut CDmgAccumulator),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct acttable_t {
    pub baseAct: ::std::os::raw::c_int,
    pub weaponAct: ::std::os::raw::c_int,
    pub required: bool,
}
include!("layout_assertions.rs");
