// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CBaseAnimating_BaseClass = CBaseEntity;
pub type CBaseAnimating__bindgen_ty_1 = ::std::os::raw::c_uint;
pub const CBaseAnimating_NUM_BONECTRLS: CBaseAnimating__bindgen_ty_1 = 4;
pub const CBaseAnimating_NUM_POSEPAREMETERS: CBaseAnimating__bindgen_ty_1 = 24;
/// Opaque: bindgen cannot express this record's C++ layout, so only its size and alignment are kept.
///
/// Generated as fields, its Rust field `m_flEstIkFloor` is at offset 1256, but C++ says 1252.
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating {
    pub _bindgen_opaque_blob: __BindgenOpaqueArray8<[u8; 1544usize]>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_bClientSideAnimation {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_bClientSideFrameReset {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_fadeMaxDist {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_fadeMinDist {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_flCycle {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_flEncodedController {
    pub m_Value: [f32; 4usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_flFadeScale {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_flModelScale {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_flPlaybackRate {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_flPoseParameter {
    pub m_Value: [f32; 24usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_hLightingOrigin {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_hLightingOriginRelative {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nBody {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nForceBone {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nHitboxSet {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nMuzzleFlashParity {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nNewSequenceParity {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nResetEventsParity {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nSequence {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_nSkin {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseAnimating_NetworkVar_m_vecForce {
    pub _address: u8,
}
#[repr(C)]
pub struct CBaseAnimating__bindgen_vtable {
    pub CBaseAnimating_complete_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_SetRefEHandle: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CBaseHandle,
    ),
    pub CBaseAnimating_GetRefEHandle: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> *const CBaseHandle,
    pub CBaseAnimating_GetCollideable: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut ICollideable,
    pub CBaseAnimating_GetNetworkable: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut IServerNetworkable,
    pub CBaseAnimating_GetBaseEntity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CBaseEntity,
    pub CBaseAnimating_GetModelIndex: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_GetModelName: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> string_t,
    pub CBaseAnimating_SetModelIndex: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_GetServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut ServerClass,
    pub CBaseAnimating_YouForgotToImplementOrDeclareServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_GetDataDescMap: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut datamap_t,
    pub CBaseAnimating_GetScriptDesc: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut ScriptClassDesc_t,
    pub CBaseAnimating_SetModelIndexOverride: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_TestCollision: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CBaseAnimating_TestHitboxes: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CBaseAnimating_ComputeWorldSpaceSurroundingBox: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub CBaseAnimating_ShouldCollide: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseAnimating_SetOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_SetScriptOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: HSCRIPT,
    ),
    pub CBaseAnimating_ShouldTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CCheckTransmitInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_UpdateTransmitState: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_SetTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CCheckTransmitInfo,
        arg3: bool,
    ),
    pub CBaseAnimating_GetTracerType: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseAnimating_Spawn: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_Precache: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_SetModel: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseAnimating_OnNewModel: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CStudioHdr,
    pub CBaseAnimating_PostConstructor: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseAnimating_PostClientActive: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_ParseMapData: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CEntityMapData,
    ),
    pub CBaseAnimating_KeyValue: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> bool,
    pub CBaseAnimating_KeyValue1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
        arg3: f32,
    ) -> bool,
    pub CBaseAnimating_KeyValue2: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const Vector,
    ) -> bool,
    pub CBaseAnimating_GetKeyValue: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseAnimating_Activate: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_SetParent: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_ObjectCaps: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_AcceptInput: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut CBaseEntity,
        arg4: *mut CBaseEntity,
        arg5: variant_t,
        arg6: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseAnimating_GetInputDispatchEffectPosition: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut Vector,
        arg4: *mut QAngle,
    ),
    pub CBaseAnimating_DrawDebugGeometryOverlays: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_DrawDebugTextOverlays: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_Save: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ISave,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_Restore: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut IRestore,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_ShouldSavePhysics: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_OnSave: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut IEntitySaveUtils,
    ),
    pub CBaseAnimating_OnRestore: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_RequiredEdictIndex: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_MoveDone: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_Think: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_NetworkStateChanged_m_nNextThinkTick: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_nNextThinkTick1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_GetBaseAnimating: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CBaseAnimating,
    pub CBaseAnimating_GetResponseSystem: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut IResponseSystem,
    pub CBaseAnimating_DispatchResponse: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseAnimating_Classify: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> Class_T,
    pub CBaseAnimating_DeathNotice: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_ShouldAttractAutoAim: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_GetAutoAimRadius: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> f32,
    pub CBaseAnimating_GetAutoAimCenter: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_GetBeamTraceFilter: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut ITraceFilter,
    pub CBaseAnimating_PassesDamageFilter: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CBaseAnimating_TraceAttack: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CTakeDamageInfo,
        arg3: *const Vector,
        arg4: *mut trace_t,
        arg5: *mut CDmgAccumulator,
    ),
    pub CBaseAnimating_CanBeHitByMeleeAttack: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_OnTakeDamage: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_AdjustDamageDirection: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CTakeDamageInfo,
        arg3: *mut Vector,
        arg4: *mut CBaseEntity,
    ),
    pub CBaseAnimating_TakeHealth: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_IsAlive: unsafe extern "C" fn(arg1: *mut CBaseAnimating) -> bool,
    pub CBaseAnimating_Event_Killed: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CTakeDamageInfo,
    ),
    pub CBaseAnimating_Event_KilledOther: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
        arg3: *const CTakeDamageInfo,
    ),
    pub CBaseAnimating_BloodColor: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_IsTriggered: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_IsNPC: unsafe extern "C" fn(arg1: *const CBaseAnimating) -> bool,
    pub CBaseAnimating_MyCombatCharacterPointer: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CBaseCombatCharacter,
    pub CBaseAnimating_MyNextBotPointer: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut INextBot,
    pub CBaseAnimating_GetDelay: unsafe extern "C" fn(arg1: *mut CBaseAnimating) -> f32,
    pub CBaseAnimating_IsMoving: unsafe extern "C" fn(arg1: *mut CBaseAnimating) -> bool,
    pub CBaseAnimating_DamageDecal: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseAnimating_DecalTrace: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut trace_t,
        arg3: *const ::std::os::raw::c_char,
    ),
    pub CBaseAnimating_ImpactTrace: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
        arg4: *const ::std::os::raw::c_char,
    ),
    pub CBaseAnimating_OnControls: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_HasTarget: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: string_t,
    ) -> bool,
    pub CBaseAnimating_IsPlayer: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsNetClient: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsTemplate: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsBaseObject: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsBaseTrain: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsCombatItem: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsBaseCombatWeapon: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_IsWearable: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_MyCombatWeaponPointer: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CBaseCombatWeapon,
    pub CBaseAnimating_GetServerVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut IServerVehicle,
    pub CBaseAnimating_IsViewable: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_ChangeTeam: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_OnEntityEvent: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: EntityEvent_t,
        arg3: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_CanStandOn: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_CanStandOn1: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
        arg2: *mut edict_t,
    ) -> bool,
    pub CBaseAnimating_GetEnemy: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CBaseEntity,
    pub CBaseAnimating_GetEnemy1: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> *mut CBaseEntity,
    pub CBaseAnimating_Use: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
        arg3: *mut CBaseEntity,
        arg4: USE_TYPE,
        arg5: f32,
    ),
    pub CBaseAnimating_StartTouch: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_Touch: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_EndTouch: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_StartBlocked: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_Blocked: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_EndBlocked: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_PhysicsSimulate: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_UpdateOnRemove: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_StopLoopingSounds: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_SUB_AllowedToFade: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_Teleport: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: *const Vector,
    ),
    pub CBaseAnimating_NotifySystemEvent: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
        arg3: notify_system_event_t,
        arg4: *const notify_system_event_params_t,
    ),
    pub CBaseAnimating_MakeTracer: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
        arg3: *const trace_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_GetTracerAttachment: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_FireBullets: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const FireBulletsInfo_t,
    ),
    pub CBaseAnimating_DoImpactEffect: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_ModifyFireBulletsDamage: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CTakeDamageInfo,
    ),
    pub CBaseAnimating_Respawn: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *mut CBaseEntity,
    pub CBaseAnimating_IsLockedByMaster: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_GetMaxHealth: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_ModifyOrAppendCriteria: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut AI_CriteriaSet,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_iMaxHealth: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_iMaxHealth1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_iHealth: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_iHealth1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_lifeState: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_lifeState1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_takedamage: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_takedamage1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_RunVScripts: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_GetDamageType: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_GetDamage: unsafe extern "C" fn(arg1: *mut CBaseAnimating) -> f32,
    pub CBaseAnimating_SetDamage: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
    ),
    pub CBaseAnimating_EyePosition: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_EyeAngles: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *const QAngle,
    pub CBaseAnimating_LocalEyeAngles: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> *const QAngle,
    pub CBaseAnimating_EarPosition: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_BodyTarget: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
        arg3: bool,
    ) -> Vector,
    pub CBaseAnimating_HeadTarget: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
    ) -> Vector,
    pub CBaseAnimating_GetVectors: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut Vector,
    ),
    pub CBaseAnimating_GetViewOffset: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> *const Vector,
    pub CBaseAnimating_SetViewOffset: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
    ),
    pub CBaseAnimating_GetSmoothedVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_GetVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub CBaseAnimating_FVisible: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_FVisible1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_CanBeSeenBy: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CAI_BaseNPC,
    ) -> bool,
    pub CBaseAnimating_GetAttackDamageScale: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseAnimating_GetReceivedDamageScale: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseAnimating_GetGroundVelocityToApply: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut Vector,
    ),
    pub CBaseAnimating_PhysicsSplash: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: f32,
        arg5: f32,
    ) -> bool,
    pub CBaseAnimating_Splash: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_WorldSpaceCenter: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> *const Vector,
    pub CBaseAnimating_GetSoundEmissionOrigin: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_ModifyEmitSoundParams: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut EmitSound_t,
    ),
    pub CBaseAnimating_IsDeflectable: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_Deflected: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
        arg3: *mut Vector,
    ),
    pub CBaseAnimating_CreateVPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_ForceVPhysicsCollide: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseAnimating_VPhysicsDestroyObject: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_VPhysicsUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut IPhysicsObject,
    ),
    pub CBaseAnimating_VPhysicsTakeDamage: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_VPhysicsShadowCollision: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CBaseAnimating_VPhysicsShadowUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut IPhysicsObject,
    ),
    pub CBaseAnimating_VPhysicsCollision: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CBaseAnimating_VPhysicsFriction: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut IPhysicsObject,
        arg3: f32,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_UpdatePhysicsShadowToCurrentPosition: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
    ),
    pub CBaseAnimating_VPhysicsGetObjectList: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut *mut IPhysicsObject,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseAnimating_VPhysicsIsFlesh: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_HasPhysicsAttacker: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
    ) -> *mut CBasePlayer,
    pub CBaseAnimating_PhysicsSolidMaskForEntity: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> ::std::os::raw::c_uint,
    pub CBaseAnimating_ResolveFlyCollisionCustom: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut trace_t,
        arg3: *mut Vector,
    ),
    pub CBaseAnimating_PerformCustomPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut QAngle,
        arg5: *mut QAngle,
    ),
    pub CBaseAnimating_GetStepOrigin: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_GetStepAngles: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> QAngle,
    pub CBaseAnimating_ShouldDrawWaterImpacts: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_NetworkStateChanged_m_fFlags: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_fFlags1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_nWaterLevel: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_nWaterLevel1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_hGroundEntity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_hGroundEntity1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_vecBaseVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_vecBaseVelocity1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_flFriction: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_flFriction1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_vecVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_vecVelocity1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_vecViewOffset: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_NetworkStateChanged_m_vecViewOffset1: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseAnimating_ShouldBlockNav: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_ShouldForceTransmitsForTeam: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseAnimating_IsTruceValidForEnt: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_BCanCallVote: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_GetIdealSpeed: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> f32,
    pub CBaseAnimating_GetIdealAccel: unsafe extern "C" fn(
        arg1: *const CBaseAnimating,
    ) -> f32,
    pub CBaseAnimating_StudioFrameAdvance: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_SetSequence: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_IsActivityFinished: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_GetSequenceGroundSpeed: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CStudioHdr,
        arg3: ::std::os::raw::c_int,
    ) -> f32,
    pub CBaseAnimating_ClampRagdollForce: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
        arg3: *mut Vector,
    ),
    pub CBaseAnimating_BecomeRagdollOnClient: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseAnimating_IsRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_CanBecomeRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> bool,
    pub CBaseAnimating_GetSkeleton: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CStudioHdr,
        arg3: *mut Vector,
        arg4: *mut Quaternion,
        arg5: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_GetBoneTransform: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: *mut matrix3x4_t,
    ),
    pub CBaseAnimating_SetupBones: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut matrix3x4_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_CalculateIKLocks: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
    ),
    pub CBaseAnimating_DispatchAnimEvents: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_HandleAnimEvent: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut animevent_t,
    ),
    pub CBaseAnimating_PopulatePoseParameters: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_GetAttachment: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
        arg3: *mut matrix3x4_t,
    ) -> bool,
    pub CBaseAnimating_InitBoneControllers: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_GetGroundSpeedVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ) -> Vector,
    pub CBaseAnimating_RefreshCollisionBounds: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
    ),
    pub CBaseAnimating_Ignite: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
        arg3: bool,
        arg4: f32,
        arg5: bool,
    ),
    pub CBaseAnimating_IgniteLifetime: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
    ),
    pub CBaseAnimating_IgniteNumHitboxFires: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseAnimating_IgniteHitboxFireScale: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: f32,
    ),
    pub CBaseAnimating_Extinguish: unsafe extern "C" fn(arg1: *mut CBaseAnimating),
    pub CBaseAnimating_SetLightingOriginRelative: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseAnimating_SetLightingOrigin: unsafe extern "C" fn(
        arg1: *mut CBaseAnimating,
        arg2: *mut CBaseEntity,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBoneCache {
    pub _address: u8,
}
include!("layout_assertions.rs");
