// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CBaseViewModel_BaseClass = CBaseAnimating;
pub type CBaseViewModel_CBaseCombatWeaponHandle = CHandle;
pub type CBaseViewModel_ScreenHandle_t = CHandle;
#[repr(C)]
pub struct CBaseViewModel {
    pub _base: CBaseAnimating,
    pub _base_1: IHasOwner,
    pub m_vecLastFacing: Vector,
    pub m_nViewModelIndex: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_hOwner: CNetworkHandleBase,
    pub m_flTimeWeaponIdle: f32,
    pub m_Activity: Activity,
    pub m_nAnimationParity: CNetworkVarBase<::std::os::raw::c_int>,
    pub m_sVMName: string_t,
    pub m_sAnimationPrefix: string_t,
    pub m_hWeapon: CNetworkVarBase<CBaseViewModel_CBaseCombatWeaponHandle>,
    pub m_hScreens: CUtlVector<CBaseViewModel_ScreenHandle_t, CUtlMemory<CHandle>>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseViewModel_NetworkVar_m_hOwner {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseViewModel_NetworkVar_m_hWeapon {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseViewModel_NetworkVar_m_nAnimationParity {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseViewModel_NetworkVar_m_nViewModelIndex {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug)]
pub struct CVGuiScreen {
    _unused: [u8; 0],
}
include!("layout_assertions.rs");
