// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audioparams_t {
    pub vtable_: *const audioparams_t__bindgen_vtable,
    pub localSound: audioparams_t_NetworkVar_localSound,
    pub soundscapeIndex: CNetworkVarBase<::std::os::raw::c_int>,
    pub localBits: CNetworkVarBase<::std::os::raw::c_int>,
    pub entIndex: CNetworkVarBase<::std::os::raw::c_int>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audioparams_t_NetworkVar_entIndex {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audioparams_t_NetworkVar_localBits {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audioparams_t_NetworkVar_localSound {
    pub m_Value: [Vector; 8usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct audioparams_t_NetworkVar_soundscapeIndex {
    pub _address: u8,
}
#[repr(C)]
pub struct audioparams_t__bindgen_vtable {
    pub audioparams_t_NetworkStateChanged1: unsafe extern "C" fn(
        arg1: *mut audioparams_t,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub audioparams_t_NetworkStateChanged: unsafe extern "C" fn(
        arg1: *mut audioparams_t,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t {
    pub vtable_: *const fogparams_t__bindgen_vtable,
    pub dirPrimary: CNetworkVectorBase<Vector>,
    pub colorPrimary: CNetworkColor32Base<color32>,
    pub colorSecondary: CNetworkColor32Base<color32>,
    pub colorPrimaryLerpTo: CNetworkColor32Base<color32>,
    pub colorSecondaryLerpTo: CNetworkColor32Base<color32>,
    pub start: CNetworkVarBase<f32>,
    pub end: CNetworkVarBase<f32>,
    pub farz: CNetworkVarBase<f32>,
    pub maxdensity: CNetworkVarBase<f32>,
    pub startLerpTo: CNetworkVarBase<f32>,
    pub endLerpTo: CNetworkVarBase<f32>,
    pub lerptime: CNetworkVarBase<f32>,
    pub duration: CNetworkVarBase<f32>,
    pub enable: CNetworkVarBase<bool>,
    pub blend: CNetworkVarBase<bool>,
    pub radial: CNetworkVarBase<bool>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_blend {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_colorPrimary {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_colorPrimaryLerpTo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_colorSecondary {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_colorSecondaryLerpTo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_dirPrimary {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_duration {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_enable {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_end {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_endLerpTo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_farz {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_lerptime {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_maxdensity {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_radial {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_start {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogparams_t_NetworkVar_startLerpTo {
    pub _address: u8,
}
#[repr(C)]
pub struct fogparams_t__bindgen_vtable {
    pub fogparams_t_NetworkStateChanged1: unsafe extern "C" fn(
        arg1: *mut fogparams_t,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub fogparams_t_NetworkStateChanged: unsafe extern "C" fn(arg1: *mut fogparams_t),
}
#[repr(C)]
pub struct fogplayerparams_t {
    pub vtable_: *const fogplayerparams_t__bindgen_vtable,
    pub m_hCtrl: CNetworkHandleBase,
    pub m_flTransitionTime: f32,
    pub m_OldColor: color32,
    pub m_flOldStart: f32,
    pub m_flOldEnd: f32,
    pub m_NewColor: color32,
    pub m_flNewStart: f32,
    pub m_flNewEnd: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fogplayerparams_t_NetworkVar_m_hCtrl {
    pub _address: u8,
}
#[repr(C)]
pub struct fogplayerparams_t__bindgen_vtable {
    pub fogplayerparams_t_NetworkStateChanged1: unsafe extern "C" fn(
        arg1: *mut fogplayerparams_t,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub fogplayerparams_t_NetworkStateChanged: unsafe extern "C" fn(
        arg1: *mut fogplayerparams_t,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sky3dparams_t {
    pub vtable_: *const sky3dparams_t__bindgen_vtable,
    pub scale: CNetworkVarBase<::std::os::raw::c_int>,
    pub origin: CNetworkVectorBase<Vector>,
    pub area: CNetworkVarBase<::std::os::raw::c_int>,
    pub fog: sky3dparams_t_NetworkVar_fog,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sky3dparams_t_NetworkVar_area {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sky3dparams_t_NetworkVar_fog {
    pub _base: fogparams_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sky3dparams_t_NetworkVar_origin {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sky3dparams_t_NetworkVar_scale {
    pub _address: u8,
}
#[repr(C)]
pub struct sky3dparams_t__bindgen_vtable {
    pub sky3dparams_t_NetworkStateChanged1: unsafe extern "C" fn(
        arg1: *mut sky3dparams_t,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub sky3dparams_t_NetworkStateChanged: unsafe extern "C" fn(
        arg1: *mut sky3dparams_t,
    ),
}
include!("layout_assertions.rs");
