#![cfg_attr(docsrs, feature(doc_cfg))]

pub(crate) mod cpp_vtable;
mod layout;
mod protobuf;
pub mod provenance;
mod prune;
mod transform;

#[cfg(test)]
#[path = "tests/support/mod.rs"]
mod test_support;

#[cfg(test)]
#[path = "tests/lib.rs"]
mod tests;

use bindgen::RustTarget;

use cpp_vtable::{
	CppAbi, RecordIndex, VtableModel, VtableProbe, collect_records_under_root,
	query_record_call_traits, render_vtable_probe,
};

use crys_bricks::bindings::{ModulePath, ModulePathError, ModuleTree, ModuleTreeError};
use crys_bricks::config::{PathResolutionError, PathResolutionMethod, RequireVarError, cargo_var};
use log::{info, trace};
use proc_macro2::TokenStream;
use provenance::{GeneratedItemKind, ProvenanceCollector, ProvenanceIndex, partition_file};
use quote::ToTokens;
use rscode::rscode_fmt::{FormatError, FormatOptions, Formatter, RsFormatter, SortOptions};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Component, MAIN_SEPARATOR_STR, Path, PathBuf};
use std::str::FromStr;
use syn::visit::Visit;
use syn::{Attribute, Fields, File, ForeignItem, Item, parse_quote};

const BRIDGE_FILE: &str = {
	const HEAD: &[u8; 3] = b"cpp";
	const TAIL: &[u8; 10] = b"bridge.hpp";

	const BRIDGE_FILE_BYTES: [u8; HEAD.len() + MAIN_SEPARATOR_STR.len() + TAIL.len()] = {
		let mut bytes = [0u8; _];
		let (head, tail) = bytes.split_at_mut(HEAD.len());
		let (sep, tail) = tail.split_at_mut(MAIN_SEPARATOR_STR.len());

		head.copy_from_slice(HEAD);
		sep.copy_from_slice(MAIN_SEPARATOR_STR.as_bytes());
		tail.copy_from_slice(TAIL);
		bytes
	};

	let Ok(_str) = str::from_utf8(&BRIDGE_FILE_BYTES) else {
		panic!()
	};

	"bridge.hpp"
};

const BRIDGE_SOURCE: &str = include_str!("cpp/bridge.hpp");

const GENERATED_FILE_HEADER: &str = concat!(
	"// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.\n// Regenerate with the `",
	env!("CARGO_PKG_NAME"),
	"/generate_bindings` Cargo feature.\n\n"
);

const GENERATED_FILES_MANIFEST: &str = ".source-sdk-2013-bindings";
const GENERATED_MANIFEST_HEADER: &str = "# @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.\n";
const MODULE_NAMESPACE: &str = "headers";

const ROOT_TYPES: &[&str] = &[
	"CTFPlayer",
	"CTFPlayerShared",
	"CTFWeaponBase",
	// TF2's game rules, teams, objectives, buildings, weapons, projectiles and
	// navigation areas, from the headers `bridge.hpp` includes for them.
	// `CTFBot` cannot be one: its `GetLastKnownArea` overrides
	// `CBaseCombatCharacter`'s with a covariant return type.
	"CTFGameRules",
	"CTFTeam",
	"CCaptureFlag",
	"CTeamControlPoint",
	"CObjectSentrygun",
	"CObjectDispenser",
	"CObjectTeleporter",
	"CWeaponMedigun",
	"CTFFlameThrower",
	"CTFMinigun",
	"CTFSniperRifle",
	"CTFKnife",
	"CTFBaseRocket",
	"CTFGrenadePipebombProjectile",
	"CTFProjectile_Arrow",
	"CTFNavArea",
	// NextBot's interfaces, the ground and player locomotion and body
	// components built on them, and TF2 bots' own components.
	// `NextBotCombatCharacter` cannot be one: its `GetEntity` overrides
	// `INextBot`'s with a covariant return type.
	"INextBot",
	"ILocomotion",
	"IBody",
	"IVision",
	"IIntention",
	"NextBotGroundLocomotion",
	"PlayerLocomotion",
	"PlayerBody",
	"CTFBotLocomotion",
	"CTFBotBody",
	"CTFBotVision",
	// econ_entity_creation.h's game system and its nonvirtual methods' inputs.
	// The methods themselves are deliberately not directly linked.
	"CItemGeneration",
	"CItemSelectionCriteria",
	"baseitemcriteria_t",
	"entityquality_t",
	"CBaseIssue",
	"vote_create_failed_t",
	"ETFCond",
	"ExtendedFieldType_t",
	"uint32",
	"uint64",
	"CreateInterfaceFn",
	"IVEngineServer",
	"IGameEvent",
	"IGameEventManager2",
	"IGameEventListener2",
	"IGameEventVisitor2",
	"IServerTools",
	"KeyValues",
	// `ServerGameDLL012` from the server factory, and the game's implementation
	// of it in `game/server/gameinterface.h`. Both expose `GetAllServerClasses`.
	"IServerGameDLL",
	"CServerGameDLL",
	// `game/server/entityoutput.h`, the base of every `CEntityOutputTemplate`.
	"CBaseEntityOutput",
	// Other interfaces exported by the engine and game-server factories.
	"IServerGameEnts",
	"IServerGameClients",
	"IPlayerInfoManager",
	"IBotManager",
	"ICvar",
	"IEngineTrace",
	"IEngineSound",
	"INetworkStringTableContainer",
	"IServerPluginHelpers",
	"IVModelInfo",
	"IVoiceServer",
	// Per-client networking. `GetPlayerNetInfo` returns a client's channel, and
	// `GetIServer` the server that owns each client's message handler.
	"INetChannelInfo",
	"INetChannel",
	"INetMessage",
	"INetChannelHandler",
	"IClientMessageHandler",
	"IRecipientFilter",
	"IServer",
	"IClient",
];

const SUPPORT_HEADER: &str = "__bindgen/support.rs";

#[derive(Debug)]
pub struct Bindgen {
	sdk_path: PathBuf,
}

impl Bindgen {
	/// Generates bindings for Cargo's current target.
	pub fn generate(self) -> Result<GeneratedBindings, BindgenError> {
		let target = SupportedTarget::from_parts(
			&cargo_var("CARGO_CFG_TARGET_ARCH")?,
			&cargo_var("CARGO_CFG_TARGET_OS")?,
			&cargo_var("CARGO_CFG_TARGET_ENV")?,
		)?;

		self.generate_for(target)
	}

	/// Generates bindings for an explicitly selected target ABI.
	///
	/// Build scripts should prefer this method so the target selecting the C++
	/// ABI is necessarily the same target selecting the output directory.
	pub fn generate_for(self, target: SupportedTarget) -> Result<GeneratedBindings, BindgenError> {
		info!("[STEP] Config");

		let sdk_src = self.sdk_path.join("src");
		let protocol_headers = protobuf::prepare_for_build(&sdk_src)?;
		let mut clang_args = clang_arguments(&sdk_src, target);
		clang_args.push(format!("-I{}", protocol_headers.include_dir.display()));

		let abi = match target {
			SupportedTarget::Linux32 => CppAbi::ItaniumX86,
			SupportedTarget::Linux64 => CppAbi::Itanium,
			SupportedTarget::Windows32 => CppAbi::MsvcX86,
			SupportedTarget::Windows64 => CppAbi::Msvc,
		};

		// The discovery pass determines which transitively reachable types belong
		// to the SDK. Any reachable compiler/toolchain types become opaque in the
		// final pass; unrelated unreachable types are absent altogether.
		let discovery = ProvenanceCollector::new(&sdk_src, [BRIDGE_FILE])
			.with_external_roots([sdk_src.join("thirdparty")]);

		info!("[STEP] Discovery");

		let discovery_bindings =
			binding_builder(BRIDGE_SOURCE, &clang_args, discovery.clone(), &[], false)
				.generate()?;

		let discovery_syntax = syn::parse_file(&discovery_bindings.to_string())?;
		let discovery_index = discovery.index();

		info!("[STEP] Record collection");

		// Bindgen deliberately emits dummy vtable types for several valid C++
		// layouts. Derive complete tables from the same translation unit and feed
		// typed probe structs through bindgen on the final pass.
		let generated_types = discovery_index.generated_type_names();
		let records = collect_records_under_root(BRIDGE_FILE, BRIDGE_SOURCE, &clang_args, &sdk_src)
			.map_err(cpp_vtable_error)?;

		let generated_record_names =
			bindgen_record_name_map(&records, &discovery_index, &generated_types)?;

		let mut layouts = Vec::new();
		let mut opaque_vtables = BTreeMap::new();

		info!("[STEP] Opaque vtable filtering");

		for qualified_name in records.records().keys() {
			let Some(generated_name) = generated_record_names.get(qualified_name) else {
				continue;
			};

			if discovery_index
				.module_for_generated_name(generated_name)
				.is_none()
			{
				opaque_vtables.insert(
					generated_name.clone(),
					"external dependency type; only its identity and layout are retained"
						.to_owned(),
				);

				continue;
			}

			let layout = match records
				.vtable_model(qualified_name, abi)
				.map_err(cpp_vtable_error)?
			{
				VtableModel::NotPolymorphic => continue,
				VtableModel::Modeled(layout) => layout,

				// Bindgen's placeholder vtable (if any) stays in place and is
				// documented, so no slot order is ever guessed.
				VtableModel::Unsupported { reason } => {
					if opaque_vtables
						.insert(generated_name.clone(), reason)
						.is_some()
					{
						return Err(BindgenError::DuplicateVtableTarget {
							target: generated_name.clone(),
						});
					}

					continue;
				}
			};

			layouts.push((generated_name, layout));
		}

		info!("[STEP] Call trait analysis");

		// How a class passed or returned by value crosses the call depends on
		// its special members, which only Clang's semantic analysis knows.
		let call_traits = query_record_call_traits(
			BRIDGE_FILE,
			BRIDGE_SOURCE,
			&clang_args,
			layouts
				.iter()
				.flat_map(|(_, layout)| layout.by_value_records()),
		)
		.map_err(cpp_vtable_error)?;

		let mut probes = Vec::new();
		let mut flattened_interfaces = Vec::new();
		let mut probe_targets = BTreeMap::new();
		let mut expected_vtables = BTreeMap::new();

		info!("[STEP] Render probes");

		for (generated_name, layout) in layouts {
			let probe =
				render_vtable_probe(&records, &layout, &call_traits).map_err(cpp_vtable_error)?;

			let probe_key = probe
				.stem
				.strip_prefix("__crys_vtable_")
				.unwrap_or(&probe.stem)
				.to_owned();

			if probe_targets
				.insert(probe_key.clone(), generated_name.clone())
				.is_some()
			{
				return Err(BindgenError::DuplicateProbeStem { stem: probe_key });
			}

			let expected_fields = mapped_probe_field_names(&probe, generated_name)?;

			if expected_vtables
				.insert(generated_name.clone(), expected_fields)
				.is_some()
				|| opaque_vtables.contains_key(generated_name)
			{
				return Err(BindgenError::DuplicateVtableTarget {
					target: generated_name.clone(),
				});
			}

			if is_one_pointer_interface(&discovery_syntax, generated_name) {
				flattened_interfaces.push(generated_name.clone());
			}

			probes.push(probe);
		}

		for root in ROOT_TYPES {
			if let Some(reason) = opaque_vtables.get(*root) {
				return Err(BindgenError::UnmodeledRootVtable {
					root: (*root).to_owned(),
					reason: reason.clone(),
				});
			}
		}

		let mut final_header = String::from(BRIDGE_SOURCE);

		info!("[STEP] Render final header");

		for probe in &probes {
			final_header.push_str("\n\n");
			final_header.push_str(&probe.source);
		}

		// Bindgen emits nothing at all for an opaque typedef of an anonymous
		// record, such as glibc's `pthread_mutex_t`, so those stay transparent.
		let external_opaque = discovery_index
			.external_opaque_type_patterns_excluding(records.typedef_named_anonymous_records());

		let generated_to_cpp = generated_record_names
			.iter()
			.map(|(cpp_name, generated_name)| (generated_name.clone(), cpp_name.clone()))
			.collect::<BTreeMap<_, _>>();

		let flattened = flattened_interfaces
			.iter()
			.map(String::as_str)
			.collect::<Vec<_>>();

		let expected = probe_targets.keys().cloned().collect::<BTreeSet<_>>();

		// Records whose C++ layout bindgen cannot express, by C++ name, with
		// the first mismatch found. Each pass makes the newly found ones
		// opaque, and an opaque record always matches its layout.
		let mut inexpressible = BTreeMap::<String, String>::new();
		let mut pass = 0usize;

		info!("[STEP] Make inexpressible layouts opaque");

		let (mut syntax, provenance) = loop {
			let mut opaque_patterns = external_opaque.clone();
			pass += 1;

			info!("       Pass: {pass}");

			opaque_patterns.extend(
				inexpressible
					.keys()
					.map(|cpp_name| format!("^{}$", provenance::escape_regex(cpp_name))),
			);

			let provenance = ProvenanceCollector::new(&sdk_src, [BRIDGE_FILE])
				.with_external_roots([sdk_src.join("thirdparty")]);

			let final_bindings = binding_builder(
				&final_header,
				&clang_args,
				provenance.clone(),
				&opaque_patterns,
				!probes.is_empty(),
			)
			.generate()?;

			let mut syntax = syn::parse_file(&final_bindings.to_string())?;

			reject_directly_linked_symbols(&syntax)?;

			let installed =
				transform::install_vtable_probes(&mut syntax, &probe_targets, &flattened)
					.map_err(vtable_transform_error)?;

			let installed_names = installed.keys().cloned().collect::<BTreeSet<_>>();

			if installed_names != expected {
				return Err(BindgenError::MissingVtableProbes {
					expected: expected.difference(&installed_names).cloned().collect(),
				});
			}

			let provenance = provenance.index();

			prune::prune_unreferenced_external_types(&mut syntax, &provenance);
			layout::remove_unreferenced_broken_aliases(&mut syntax);

			let mismatches = layout::find_layout_mismatches(&syntax, target.layout());

			if mismatches.is_empty() {
				break (syntax, provenance);
			}

			let mut progressed = false;

			for (generated_name, reason) in mismatches.clone() {
				let Some(cpp_name) = generated_to_cpp
					.get(&generated_name)
					.cloned()
					.or_else(|| enclosing_cpp_record(&records, &generated_name))
					.or_else(|| top_level_cpp_name(&provenance, &generated_name))
				else {
					return Err(BindgenError::InexpressibleLayout {
						item: generated_name,
						reason,
					});
				};

				if let std::collections::btree_map::Entry::Vacant(entry) =
					inexpressible.entry(cpp_name)
				{
					entry.insert(reason);
					progressed = true;
				}
			}

			if !progressed {
				let (item, reason) = mismatches
					.into_iter()
					.next()
					.expect("the mismatches were not empty");

				return Err(BindgenError::InexpressibleLayout { item, reason });
			}
		};

		let opaque_records = inexpressible
			.iter()
			.filter_map(|(cpp_name, reason)| {
				Some((
					generated_record_names.get(cpp_name)?.clone(),
					reason.clone(),
				))
			})
			.collect::<BTreeMap<_, _>>();

		info!("[STEP] Validate: required classes expressed");

		for required in ["CTFPlayer", "CTFPlayerShared"] {
			if let Some(reason) = opaque_records.get(required) {
				return Err(BindgenError::InexpressibleLayout {
					item: required.to_owned(),
					reason: reason.clone(),
				});
			}
		}

		let opaque_names = opaque_vtables.keys().cloned().collect::<BTreeSet<_>>();

		info!("[STEP] Validate: vtables");
		transform::validate_vtables_against(&syntax, &expected_vtables, &opaque_names)
			.map_err(vtable_transform_error)?;

		info!("[STEP] Doc: opaque vtables");
		transform::document_opaque_vtables(&mut syntax, &opaque_vtables);

		info!("[STEP] Doc: opaque records");
		transform::document_opaque_records(&mut syntax, &opaque_records);

		info!("[STEP] Validate: player records");
		validate_player_records(&syntax)?;

		info!("[STEP] Validate: root names");
		validate_root_names(&syntax)?;
		add_generated_binding_attributes(&mut syntax);

		info!("[STEP] Collect used includes");

		let included_files = provenance
			.included_files()
			.map(Path::to_owned)
			.chain(protocol_headers.inputs)
			.collect();

		info!("[STEP] Render: partitioned modules");

		let support_module = ModulePath::from_header_path(SUPPORT_HEADER)?;
		let files = render_partitioned_modules(syntax, &provenance, support_module)?;

		Ok(GeneratedBindings {
			files,
			included_files,
		})
	}

	pub fn sdk_path(&self) -> &Path {
		&self.sdk_path
	}
}

#[derive(Debug, thiserror::Error)]
pub enum BindgenError {
	#[error(transparent)]
	Protobuf(#[from] protobuf::ProtobufError),

	#[error("C++ record {record:?} maps to multiple generated Rust types: {candidates:?}")]
	AmbiguousRecordMapping {
		record: String,
		candidates: Vec<String>,
	},

	#[error("bindgen: {0}")]
	Bindgen(#[from] bindgen::BindgenError),

	#[error("C++ vtable analysis failed: {0}")]
	CppVtable(String),

	#[error(
		"generated bindings contain a directly linked C++ symbol; expose SDK interfaces through their vtables instead"
	)]
	DirectlyLinkedSymbol,

	#[error("more than one C++ vtable probe has identifier stem {stem:?}")]
	DuplicateProbeStem { stem: String },

	#[error("more than one C++ vtable probe targets generated Rust type {target:?}")]
	DuplicateVtableTarget { target: String },

	#[error("could not format generated Rust bindings: {0}")]
	Format(#[from] FormatError),

	#[error("vtable probe {probe:?} emitted unexpected field name {field:?}")]
	InvalidProbeFieldName { probe: String, field: String },

	#[error("not every generated C++ vtable probe was installed; missing {expected:?}")]
	MissingVtableProbes { expected: Vec<String> },

	#[error("generated module tree did not contain its root module")]
	MissingRootModule,

	#[error(transparent)]
	ModulePath(#[from] ModulePathError),

	#[error(transparent)]
	ModuleTree(#[from] ModuleTreeError),

	#[error("could not parse generated Rust bindings: {0}")]
	Parse(#[from] syn::Error),

	#[error("environment: {0}")]
	RequireVar(#[from] RequireVarError),

	#[error("generated item {name:?} collides with a reserved root module name")]
	RootNameCollision { name: String },

	#[error(transparent)]
	TargetSupport(#[from] TargetSupportError),

	#[error(
		"generated item {item:?} does not match its C++ layout and cannot be made opaque: {reason}"
	)]
	InexpressibleLayout { item: String, reason: String },

	#[error("root type {root:?} has a vtable which cannot be modeled: {reason}")]
	UnmodeledRootVtable { root: String, reason: String },

	#[error("full TF2 player bindings require the generated field {record}::{field}")]
	IncompletePlayerRecord { record: String, field: String },

	#[error("generated vtable transformation failed: {0}")]
	VtableTransform(String),
}

#[derive(Debug)]
#[non_exhaustive]
pub struct Builder {
	pub sdk_path: PathResolutionMethod,
}

impl Builder {
	pub fn new() -> Self {
		Self {
			sdk_path: PathResolutionMethod::new_env("SOURCE_SDK_2013"),
		}
	}

	pub fn build(self) -> Result<Bindgen, BuilderError> {
		Ok(Bindgen {
			sdk_path: self.sdk_path.resolve()?,
		})
	}

	pub fn with_sdk_path(mut self, path: PathBuf) -> Self {
		self.sdk_path = PathResolutionMethod::Provided(path);
		self
	}
}

impl Default for Builder {
	fn default() -> Self {
		Self::new()
	}
}

#[derive(Debug, thiserror::Error)]
pub enum BuilderError {
	#[error("{0}")]
	PathResolution(#[from] PathResolutionError),
}

#[derive(Debug)]
pub struct GeneratedBindings {
	files: BTreeMap<PathBuf, String>,
	included_files: Vec<PathBuf>,
}

impl GeneratedBindings {
	/// All generated files, keyed by their path relative to the output folder.
	pub fn files(&self) -> &BTreeMap<PathBuf, String> {
		&self.files
	}

	/// Headers observed while parsing the final translation unit.
	pub fn included_files(&self) -> &[PathBuf] {
		&self.included_files
	}

	/// Returns the root `mod.rs` for the split, filesystem-backed module tree.
	pub fn root_source(&self) -> &str {
		self.files
			.get(Path::new("mod.rs"))
			.map(String::as_str)
			.expect("generated bindings always contain mod.rs")
	}

	/// Renders a self-contained inline module tree as readable Rust source.
	pub fn to_source(&self) -> String {
		let syntax = inline_generated_tree(&self.files)
			.expect("the generated module tree was already parsed and validated");

		format_generated(syntax, false).expect("the generated modules were already formatted")
	}

	/// Returns a self-contained inline module tree as Rust tokens.
	///
	/// [`Self::write`] still emits the same bindings as separate files. Use
	/// [`Self::root_source`] when only that split tree's root `mod.rs` is needed.
	pub fn to_token_stream(&self) -> TokenStream {
		let syntax = inline_generated_tree(&self.files)
			.expect("the generated module tree was already parsed and validated");

		quote::quote!(#syntax)
	}

	/// Writes the split tree and removes stale files owned by an earlier write.
	/// Files not listed in the generator manifest are never removed.
	pub fn write(&self, path: impl AsRef<Path>) -> Result<(), std::io::Error> {
		let root = path.as_ref();

		fs::create_dir_all(root)?;

		let desired = self
			.files
			.keys()
			.map(|path| Ok((generated_path_key(path)?, path)))
			.collect::<Result<BTreeMap<_, _>, std::io::Error>>()?;

		let manifest_path = root.join(GENERATED_FILES_MANIFEST);

		let previous = match fs::read_to_string(&manifest_path) {
			Ok(manifest) => manifest
				.lines()
				.filter(|line| !line.is_empty() && !line.starts_with('#'))
				.map(generated_path_from_key)
				.collect::<Result<Vec<_>, _>>()?,

			Err(error) if error.kind() == std::io::ErrorKind::NotFound => Vec::new(),
			Err(error) => return Err(error),
		};

		for stale in previous {
			if desired.contains_key(&generated_path_key(&stale)?) {
				continue;
			}

			info!("[STALE] {}", stale.display());

			match fs::remove_file(root.join(stale)) {
				Ok(()) => {}
				Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
				Err(error) => return Err(error),
			}
		}

		for (relative, contents) in &self.files {
			let output = root.join(relative);

			if let Some(parent) = output.parent() {
				fs::create_dir_all(parent)?;
			}

			info!("[OUT] {}", output.display());
			fs::write(output, contents)?;
		}

		let mut manifest = String::from(GENERATED_MANIFEST_HEADER);

		manifest.push_str(&desired.keys().cloned().collect::<Vec<_>>().join("\n"));
		manifest.push('\n');
		fs::write(&manifest_path, manifest)?;
		info!("Manifest written: {}", manifest_path.display());

		Ok(())
	}
}

/// All targets supported by this crate as of now.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum SupportedTarget {
	/// `i686-unknown-linux-gnu`
	Linux32,

	/// `x86_64-unknown-linux-gnu`
	Linux64,

	/// `i686-pc-windows-msvc`
	Windows32,

	/// `x86_64-pc-windows-msvc`
	Windows64,
}

impl SupportedTarget {
	pub fn from_env() -> anyhow::Result<Self> {
		Self::from_parts(
			&cargo_var("CARGO_CFG_TARGET_ARCH")?,
			&cargo_var("CARGO_CFG_TARGET_OS")?,
			&cargo_var("CARGO_CFG_TARGET_ENV")?,
		)
		.map_err(Into::into)
	}

	pub const fn from_host() -> Result<Self, TargetSupportError> {
		let arch = cfg_select! {
			target_arch = "x86" => "i686",
			target_arch = "x86_64" => "x86_64",
			_ => "",
		};

		let os = cfg_select! {
			target_os = "linux" => "linux",
			target_os = "windows" => "windows",
			_ => "",
		};

		let env = cfg_select! {
			target_env = "msvc" => "msvc",
			target_env = "gnu" => "gnu",
			_ => "",
		};

		Self::from_parts(arch, os, env)
	}

	pub const fn from_parts(arch: &str, os: &str, env: &str) -> Result<Self, TargetSupportError> {
		// HACK: cannot match `str` in `const` yet, so use `as_bytes`.
		match [arch.as_bytes(), os.as_bytes(), env.as_bytes()] {
			[b"i686", b"linux", b"gnu"] => Ok(Self::Linux32),
			[b"x86_64", b"linux", b"gnu"] => Ok(Self::Linux64),
			[b"i686" | b"x86_64", b"linux", ..] => Err(TargetSupportError::GlibcRequired),
			[b"i686", b"windows", b"msvc"] => Ok(Self::Windows32),
			[b"x86_64", b"windows", b"msvc"] => Ok(Self::Windows64),
			[b"i686" | b"x86_64", b"windows", ..] => Err(TargetSupportError::MsvcRequired),
			[..] => Err(TargetSupportError::UnsupportedTarget),
		}
	}

	pub const fn clang_target(&self) -> &'static str {
		match self {
			Self::Linux32 => "i686-unknown-linux-gnu",
			Self::Linux64 => "x86_64-unknown-linux-gnu",
			Self::Windows32 => "i686-pc-windows-msvc",
			Self::Windows64 => "x86_64-pc-windows-msvc",
		}
	}

	pub const fn is_32bit(&self) -> bool {
		matches!(self, Self::Linux32 | Self::Windows32)
	}

	pub const fn is_64bit(&self) -> bool {
		matches!(self, Self::Linux64 | Self::Windows64)
	}

	pub const fn is_linux(&self) -> bool {
		matches!(self, Self::Linux32 | Self::Linux64)
	}

	pub const fn is_windows(&self) -> bool {
		matches!(self, Self::Windows32 | Self::Windows64)
	}

	pub(crate) const fn layout(&self) -> layout::TargetLayout {
		match self {
			Self::Linux32 => layout::TargetLayout {
				pointer_width: 4,
				c_long_width: 4,
				int64_align: 4,
			},

			Self::Linux64 => layout::TargetLayout {
				pointer_width: 8,
				c_long_width: 8,
				int64_align: 8,
			},

			Self::Windows32 => layout::TargetLayout {
				pointer_width: 4,
				c_long_width: 4,
				int64_align: 8,
			},

			Self::Windows64 => layout::TargetLayout {
				pointer_width: 8,
				c_long_width: 4,
				int64_align: 8,
			},
		}
	}

	pub const fn short_name(&self) -> &'static str {
		match self {
			Self::Linux32 => "linux_32",
			Self::Linux64 => "linux_64",
			Self::Windows32 => "windows_32",
			Self::Windows64 => "windows_64",
		}
	}
}

impl FromStr for SupportedTarget {
	type Err = TargetSupportError;

	fn from_str(str: &str) -> Result<Self, Self::Err> {
		let mut split = str.split("-");

		//should use a better error type...
		let arch = split.next().ok_or(TargetSupportError::UnsupportedTarget)?;
		let _vendor = split.next().ok_or(TargetSupportError::UnsupportedTarget)?;
		let os = split.next().ok_or(TargetSupportError::UnsupportedTarget)?;
		let env = split.next().ok_or(TargetSupportError::UnsupportedTarget)?;

		if split.next().is_some() {
			return Err(TargetSupportError::UnsupportedTarget);
		}

		Self::from_parts(arch, os, env)
	}
}

#[derive(Debug, Clone, thiserror::Error)]
pub enum TargetSupportError {
	#[error("Source SDK 2013 requires MSVC for Windows targets")]
	MsvcRequired,

	#[error("Source SDK 2013 requires glibc for Linux targets")]
	GlibcRequired,

	#[error("Unsupported target")]
	UnsupportedTarget,
}

fn add_generated_binding_attributes(syntax: &mut File) {
	let lint_allowances: Attribute = parse_quote! {
		#![allow(
			clippy::all,
			ambiguous_glob_reexports,
			non_snake_case,
			non_camel_case_types,
			non_upper_case_globals,
			unsafe_op_in_unsafe_fn,
			unused_imports,
			unused_qualifications
		)]
	};

	syntax.attrs.insert(0, lint_allowances);
}

fn add_generated_file_headers(files: &mut BTreeMap<PathBuf, String>) {
	for source in files.values_mut() {
		source.insert_str(0, GENERATED_FILE_HEADER);
	}
}

fn bindgen_flattened_cpp_name(qualified_name: &str) -> String {
	qualified_name
		.trim_start_matches("::")
		.split("::")
		.collect::<Vec<_>>()
		.join("_")
		.chars()
		.map(|character| {
			if character.is_ascii_alphanumeric() || character == '_' {
				character
			} else {
				'_'
			}
		})
		.collect::<String>()
}

fn bindgen_record_name_map(
	records: &RecordIndex,
	provenance: &ProvenanceIndex,
	generated_types: &BTreeSet<String>,
) -> Result<BTreeMap<String, String>, BindgenError> {
	let mut mapped = BTreeMap::new();

	for (qualified_name, record) in records.records() {
		// Bindgen names a record by joining its enclosing scopes with `_`, and
		// reports the record's own spelling as its original name. Both must
		// agree. A same-named record in another scope (for example another
		// template's `Iterator_t`) is never a match.
		let flattened_name = bindgen_flattened_cpp_name(qualified_name);

		let candidates = provenance
			.records()
			.filter(|item| {
				matches!(
					item.kind,
					GeneratedItemKind::Struct | GeneratedItemKind::Union
				) && generated_types.contains(&item.final_name)
			})
			.filter(|item| item.final_name == flattened_name)
			.filter(|item| {
				item.original_name.as_deref().is_some_and(|name| {
					cpp_names_equal(name, qualified_name) || cpp_names_equal(name, &record.name)
				})
			})
			.map(|item| item.final_name.clone())
			.collect::<BTreeSet<_>>();

		match candidates.len() {
			0 => {}

			1 => {
				mapped.insert(
					qualified_name.clone(),
					candidates
						.into_iter()
						.next()
						.expect("the length was checked"),
				);
			}

			_ => {
				return Err(BindgenError::AmbiguousRecordMapping {
					record: qualified_name.clone(),
					candidates: candidates.into_iter().collect(),
				});
			}
		}
	}

	Ok(mapped)
}

fn binding_builder(
	header: &str,
	clang_args: &[String],
	provenance: ProvenanceCollector,
	external_opaque: &[String],
	include_vtable_probes: bool,
) -> bindgen::Builder {
	let mut builder = bindgen::builder()
		.header_contents(BRIDGE_FILE, header)
		.clang_args(clang_args)
		.parse_callbacks(Box::new(provenance))
		.opaque_type("std::.*")
		.opaque_type("KeyValues")
		// These bridge declarations stand in for troublesome SDK definitions and
		// intentionally expose identity only, never a fabricated object layout.
		.opaque_type("^bf_(read|write)$")
		// Interfaces are invoked through vtables. Free SDK symbols would require
		// import/static libraries that plugins do not link.
		.blocklist_function(".*")
		.blocklist_var(".*")
		.layout_tests(true)
		.generate_inline_functions(true)
		.vtable_generation(true)
		.allowlist_file(".*[/\\\\]tf_player(_shared)?\\.h")
		.rust_target(RustTarget::stable(98, 1).expect("the requested Rust target is supported"))
		.allowlist_recursively(true);

	for root in ROOT_TYPES {
		builder = builder.allowlist_type(root);
	}

	for pattern in external_opaque {
		builder = builder.opaque_type(pattern);
	}

	if include_vtable_probes {
		builder = builder.allowlist_type("^__crys_vtable_.*");
	}

	builder
}

fn clang_arguments(sdk_src: &Path, target: SupportedTarget) -> Vec<String> {
	let mut arguments = vec![
		String::from("-x"),
		String::from("c++"),
		String::from("-std=c++17"),
		// Probes name private nested classes, such as the network-variable
		// wrappers `CNetworkVarEmbedded` declares. Access control never affects
		// layout, so every pass parses without it.
		String::from("-fno-access-control"),
		// Valve's inline templates can refer to classes completed later by the
		// game's precompiled header. Delay their bodies on both target ABIs.
		String::from("-fdelayed-template-parsing"),
		// The game headers trip these hundreds of times per pass, burying any
		// real diagnostic. Neither affects declarations or layouts.
		String::from("-Wno-inconsistent-missing-override"),
		String::from("-Wno-null-dereference"),
		format!("-I{}", sdk_src.display()),
		format!("-I{}", sdk_src.join("public").display()),
		format!("-I{}", sdk_src.join("public").join("mathlib").display()),
		format!("-I{}", sdk_src.join("public").join("tier0").display()),
		format!("-I{}", sdk_src.join("public").join("tier1").display()),
		format!("-I{}", sdk_src.join("public/engine").display()),
		format!("-I{}", sdk_src.join("public/vstdlib").display()),
		format!("-I{}", sdk_src.join("public/toolframework").display()),
		format!("-I{}", sdk_src.join("public/game/server").display()),
		format!("-I{}", sdk_src.join("game").join("server").display()),
		format!("-I{}", sdk_src.join("game").join("shared").display()),
		format!("-I{}", sdk_src.join("game/server/tf").display()),
		format!("-I{}", sdk_src.join("game/shared/tf").display()),
		format!("-I{}", sdk_src.join("game/shared/econ").display()),
		format!("-I{}", sdk_src.join("game/shared/Multiplayer").display()),
		format!("-I{}", sdk_src.join("game/server/NextBot").display()),
		format!("-I{}", sdk_src.join("game/shared/hl2").display()),
		format!("-I{}", sdk_src.join("utils/common").display()),
		format!("-I{}", sdk_src.join("statemachine").display()),
		format!("-I{}", sdk_src.join("gcsdk/steamextra").display()),
		format!(
			"-I{}",
			sdk_src.join("thirdparty/protobuf-2.6.1/src").display()
		),
		// Last, so it cannot shadow the directories above: `iclient.h` includes
		// `userid.h` from here.
		format!("-I{}", sdk_src.join("common").display()),
	];

	if target.is_windows() {
		arguments.extend([
			"-DCOMPILER_MSVC".to_owned(),
			"-D_CRT_USE_BUILTIN_OFFSETOF".to_owned(),
			"-fms-compatibility".to_owned(),
			"-fms-extensions".to_owned(),
		]);

		if target.is_64bit() {
			arguments.push("-DCOMPILER_MSVC64".to_owned());
		}
	} else {
		arguments.extend([
			"-DCOMPILER_GCC".to_owned(),
			"-DGNUC".to_owned(),
			"-DPOSIX".to_owned(),
			"-DLINUX".to_owned(),
			"-D_LINUX".to_owned(),
		]);
	}

	arguments.push(format!("--target={}", target.clang_target()));
	arguments
}

fn cpp_names_equal(left: &str, right: &str) -> bool {
	left.trim_start_matches("::") == right.trim_start_matches("::")
}

fn cpp_vtable_error(error: cpp_vtable::CppVtableError) -> BindgenError {
	BindgenError::CppVtable(error.to_string())
}

/// The C++ record whose bindgen name prefixes `generated_name` before an
/// underscore, as bindgen spells a record's nested declarations. The longest
/// unambiguous prefix wins.
fn enclosing_cpp_record(records: &RecordIndex, generated_name: &str) -> Option<String> {
	let mut by_flattened_name = BTreeMap::<String, BTreeSet<&String>>::new();

	for qualified_name in records.records().keys() {
		by_flattened_name
			.entry(bindgen_flattened_cpp_name(qualified_name))
			.or_default()
			.insert(qualified_name);
	}

	by_flattened_name
		.into_iter()
		.filter(|(flattened, _)| {
			generated_name
				.strip_prefix(flattened.as_str())
				.is_some_and(|rest| rest.starts_with('_'))
		})
		.filter(|(_, qualified_names)| qualified_names.len() == 1)
		.max_by_key(|(flattened, _)| flattened.len())
		.and_then(|(_, qualified_names)| qualified_names.into_iter().next().cloned())
}

/// Prints generated Rust with prettyplease, first sorting its items with the
/// Cryotheum ordering when `sort` is set, so the output does not depend on
/// the order bindgen emitted them in.
fn format_generated(syntax: File, sort: bool) -> Result<String, FormatError> {
	let options = FormatOptions::new()
		.formatter(RsFormatter::PrettyPlease)
		.sort(sort.then(SortOptions::new));

	Formatter::new(options).format_tokens(syntax.into_token_stream())
}

fn generated_path_from_key(key: &str) -> Result<PathBuf, std::io::Error> {
	if key.is_empty() || key.contains(['\\', ':']) {
		return Err(std::io::Error::new(
			std::io::ErrorKind::InvalidData,
			"invalid generated-files manifest path",
		));
	}

	let mut path = PathBuf::new();

	for segment in key.split('/') {
		if segment.is_empty() || segment == "." || segment == ".." {
			return Err(std::io::Error::new(
				std::io::ErrorKind::InvalidData,
				"invalid generated-files manifest path",
			));
		}

		path.push(segment);
	}

	Ok(path)
}

fn generated_path_key(path: &Path) -> Result<String, std::io::Error> {
	let mut segments = Vec::new();

	for component in path.components() {
		let Component::Normal(segment) = component else {
			return Err(std::io::Error::new(
				std::io::ErrorKind::InvalidInput,
				format!("generated path is not relative: {path:?}"),
			));
		};

		let segment = segment.to_str().ok_or_else(|| {
			std::io::Error::new(
				std::io::ErrorKind::InvalidInput,
				format!("generated path is not UTF-8: {path:?}"),
			)
		})?;

		if segment.contains(['/', '\\']) {
			return Err(std::io::Error::new(
				std::io::ErrorKind::InvalidInput,
				format!("generated path has an invalid component: {path:?}"),
			));
		}

		segments.push(segment);
	}

	if segments.is_empty() {
		return Err(std::io::Error::new(
			std::io::ErrorKind::InvalidInput,
			"generated path is empty",
		));
	}

	Ok(segments.join("/"))
}

fn inline_generated_tree(files: &BTreeMap<PathBuf, String>) -> Result<File, syn::Error> {
	fn inline_file(
		file: &mut File,
		directory: &Path,
		files: &BTreeMap<PathBuf, String>,
	) -> Result<(), syn::Error> {
		let mut rendered = Vec::with_capacity(file.items.len());

		for item in std::mem::take(&mut file.items) {
			match item {
				Item::Mod(mut module) if module.content.is_none() => {
					let child_directory = directory.join(module.ident.to_string());
					let child_path = child_directory.join("mod.rs");

					let Some(source) = files.get(&child_path) else {
						return Err(syn::Error::new(
							module.ident.span(),
							format!("generated module tree is missing {child_path:?}"),
						));
					};

					let mut child = syn::parse_file(source)?;

					inline_file(&mut child, &child_directory, files)?;

					for mut attribute in child.attrs {
						attribute.style = syn::AttrStyle::Outer;
						module.attrs.push(attribute);
					}

					module.content = Some((syn::token::Brace::default(), child.items));
					module.semi = None;

					rendered.push(Item::Mod(module));
				}

				Item::Macro(include) if include.mac.path.is_ident("include") => {
					let relative = syn::parse2::<syn::LitStr>(include.mac.tokens.clone())?.value();
					let included_path = directory.join(relative);

					let Some(source) = files.get(&included_path) else {
						return Err(syn::Error::new_spanned(
							include,
							format!("generated module tree is missing {included_path:?}"),
						));
					};

					let mut included = syn::parse_file(source)?;

					inline_file(&mut included, directory, files)?;
					rendered.extend(included.items);
				}

				item => rendered.push(item),
			}
		}

		file.items = rendered;

		Ok(())
	}

	let root_source = files
		.get(Path::new("mod.rs"))
		.expect("generated bindings always contain mod.rs");
	let mut root = syn::parse_file(root_source)?;
	inline_file(&mut root, Path::new(""), files)?;
	Ok(root)
}

/// Whether `name` is exactly one vtable pointer: a struct holding only
/// `vtable_`, or only a `_base` which is itself such an interface.
///
/// A class such as `class NetworkVar_m_fog : public fogparams_t` also has a
/// single `_base` field, but that base carries data and must keep it.
fn is_one_pointer_interface(syntax: &File, name: &str) -> bool {
	fn check(syntax: &File, name: &str, visiting: &mut BTreeSet<String>) -> bool {
		if !visiting.insert(name.to_owned()) {
			return false;
		}

		syntax.items.iter().any(|item| {
			let Item::Struct(item) = item else {
				return false;
			};

			if item.ident != name || !item.generics.params.is_empty() {
				return false;
			}

			let Fields::Named(fields) = &item.fields else {
				return false;
			};
			let mut fields = fields.named.iter();

			let (Some(field), None) = (fields.next(), fields.next()) else {
				return false;
			};

			match field.ident.as_ref().map(ToString::to_string).as_deref() {
				Some("vtable_") => true,

				Some("_base") => {
					plain_type_name(&field.ty).is_some_and(|base| check(syntax, &base, visiting))
				}

				_ => false,
			}
		})
	}

	check(syntax, name, &mut BTreeSet::new())
}

fn mapped_probe_field_names(
	probe: &VtableProbe,
	generated_name: &str,
) -> Result<Vec<String>, BindgenError> {
	let probe_key = probe
		.stem
		.strip_prefix("__crys_vtable_")
		.unwrap_or(&probe.stem);
	let prefix = format!("{probe_key}_");
	probe
		.field_names
		.iter()
		.map(|field| {
			let suffix =
				field
					.strip_prefix(&prefix)
					.ok_or_else(|| BindgenError::InvalidProbeFieldName {
						probe: probe.stem.clone(),
						field: field.clone(),
					})?;
			Ok(format!("{generated_name}_{suffix}"))
		})
		.collect()
}

fn namespaced_module(module: &ModulePath) -> Result<ModulePath, ModulePathError> {
	let mut path = PathBuf::from(MODULE_NAMESPACE);

	path.extend(module.segments());
	ModulePath::from_header_path(path)
}

fn plain_type_name(type_: &syn::Type) -> Option<String> {
	let syn::Type::Path(path) = type_ else {
		return None;
	};

	if path.qself.is_some() || path.path.segments.len() != 1 {
		return None;
	}

	let segment = path.path.segments.first()?;
	segment
		.arguments
		.is_none()
		.then(|| segment.ident.to_string())
}

fn reject_directly_linked_symbols(syntax: &File) -> Result<(), BindgenError> {
	#[derive(Default)]
	struct DirectSymbolVisitor {
		found: bool,
	}

	impl<'ast> Visit<'ast> for DirectSymbolVisitor {
		fn visit_attribute(&mut self, attribute: &'ast Attribute) {
			self.found |= attribute.path().is_ident("link_name");
			syn::visit::visit_attribute(self, attribute);
		}

		fn visit_foreign_item(&mut self, item: &'ast ForeignItem) {
			self.found |= matches!(item, ForeignItem::Fn(_) | ForeignItem::Static(_));
			syn::visit::visit_foreign_item(self, item);
		}
	}

	let mut visitor = DirectSymbolVisitor::default();

	visitor.visit_file(syntax);

	if visitor.found {
		return Err(BindgenError::DirectlyLinkedSymbol);
	}

	Ok(())
}

fn render_partitioned_modules(
	syntax: File,
	provenance: &ProvenanceIndex,
	support_module: ModulePath,
) -> Result<BTreeMap<PathBuf, String>, BindgenError> {
	let mut tree = ModuleTree::new();
	let mut module_paths = Vec::new();

	for (source_module, mut file) in partition_file(syntax, provenance, support_module) {
		let module = namespaced_module(&source_module)?;
		let depth = module.as_segments().len();
		let parent = std::iter::repeat_n("super", depth)
			.collect::<Vec<_>>()
			.join("::");
		let import: Item = syn::parse_str(&format!(
			"#[allow(unused_imports)] use {parent}::__bindgen_prelude::*;"
		))?;
		file.items.insert(0, import);
		tree.insert(module.clone(), file)?;
		module_paths.push(module);
	}

	let mut files = tree.render();
	let root_source = files
		.remove(Path::new("mod.rs"))
		.ok_or(BindgenError::MissingRootModule)?;
	let mut root = syn::parse_file(&root_source)?;
	add_generated_binding_attributes(&mut root);

	let reexports = module_paths
		.iter()
		.map(|module| {
			let path = module.segments().collect::<Vec<_>>().join("::");
			format!("pub use super::{path}::*;")
		})
		.collect::<Vec<_>>()
		.join("\n");
	let prelude: Item = syn::parse_str(&format!(
		"#[doc(hidden)] #[allow(ambiguous_glob_reexports, unused_imports)] mod __bindgen_prelude {{ {reexports} }}"
	))?;
	root.items.push(prelude);
	root.items.push(parse_quote! {
		#[allow(ambiguous_glob_reexports, unused_imports)]
		pub use self::__bindgen_prelude::*;
	});

	// `ModuleTree` orders the leaves its own way, so every file is sorted again.
	for source in files.values_mut() {
		*source = format_generated(syn::parse_file(source)?, true)?;
	}

	files.insert(PathBuf::from("mod.rs"), format_generated(root, true)?);
	add_generated_file_headers(&mut files);
	Ok(files)
}

/// The C++ name of a generated struct or union declared at global scope,
/// where bindgen's name and the C++ spelling agree.
fn top_level_cpp_name(provenance: &ProvenanceIndex, generated_name: &str) -> Option<String> {
	provenance
		.records()
		.filter(|item| {
			matches!(
				item.kind,
				GeneratedItemKind::Struct | GeneratedItemKind::Union
			)
		})
		.find(|item| {
			item.final_name == generated_name
				&& item.original_name.as_deref() == Some(generated_name)
		})
		.map(|item| item.final_name.clone())
}

/// Do not silently fall back to opaque handles for the full player headers.
fn validate_player_records(syntax: &File) -> Result<(), BindgenError> {
	trace!("validate_player_records");

	for (record, field) in [
		("CTFPlayer", "m_Shared"),
		("CTFPlayerShared", "m_nPlayerCond"),
		("CTFPlayerShared", "m_pOuter"),
	] {
		let present = syntax.items.iter().any(|item| matches!(item,
			Item::Struct(item) if item.ident == record && item.fields.iter().any(|member| member.ident.as_ref().is_some_and(|name| name == field))
		));

		if !present {
			return Err(BindgenError::IncompletePlayerRecord {
				record: record.to_owned(),
				field: field.to_owned(),
			});
		}
	}

	Ok(())
}

fn validate_root_names(syntax: &File) -> Result<(), BindgenError> {
	for item in &syntax.items {
		let name = match item {
			Item::Struct(item) => Some(item.ident.to_string()),
			Item::Union(item) => Some(item.ident.to_string()),
			Item::Enum(item) => Some(item.ident.to_string()),
			Item::Type(item) => Some(item.ident.to_string()),
			Item::Const(item) if item.ident != "_" => Some(item.ident.to_string()),
			Item::Static(item) => Some(item.ident.to_string()),
			Item::Fn(item) => Some(item.sig.ident.to_string()),
			_ => None,
		};

		if name
			.as_deref()
			.is_some_and(|name| name == MODULE_NAMESPACE || name == "__bindgen_prelude")
		{
			return Err(BindgenError::RootNameCollision {
				name: name.expect("checked above"),
			});
		}
	}

	Ok(())
}

fn vtable_transform_error(error: transform::VtableTransformError) -> BindgenError {
	BindgenError::VtableTransform(error.to_string())
}
