//! Tests of [`crate::protobuf`]: generating Valve's protocol headers with the SDK's
//! bundled compiler.

use super::*;
use crate::test_support::TempDir;

#[test]
#[ignore = "set SOURCE_SDK_2013 to an authorized SDK checkout with bundled protoc"]
fn bundled_compiler_generates_all_tf2_dependencies_outside_the_sdk() {
	let sdk = PathBuf::from(std::env::var_os("SOURCE_SDK_2013").expect("SOURCE_SDK_2013"));
	let output = TempDir::new();
	let prepared = prepare(&sdk.join("src"), output.path()).unwrap();
	assert_eq!(prepared.inputs.len(), PROTOS.len() + 2);
	for proto in PROTOS {
		let header = prepared.include_dir.join(format!(
			"{}.pb.h",
			Path::new(proto).file_stem().unwrap().to_str().unwrap()
		));
		let text = fs::read_to_string(header).unwrap();
		assert!(text.contains("Generated by the protocol buffer compiler"));
	}
	assert_eq!(
		fs::read_dir(output.path()).unwrap().count(),
		1,
		"disposable compiler outputs must be removed"
	);
}
