// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CBaseIssue_EVoteAction = ::std::os::raw::c_uint;
pub type CVoteController_BaseClass = CBaseEntity;
pub type CVoteController_TryCastVoteResult = ::std::os::raw::c_uint;
pub const CBaseIssue_EVoteAction_eVoteAction_Fail: CBaseIssue_EVoteAction = 2;
pub const CBaseIssue_EVoteAction_eVoteAction_Pass: CBaseIssue_EVoteAction = 1;
pub const CBaseIssue_EVoteAction_eVoteAction_Wait: CBaseIssue_EVoteAction = 0;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_DUPLICATE: CVoteController_TryCastVoteResult = 5;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_NO_ACTIVE_ISSUE: CVoteController_TryCastVoteResult = 2;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_NO_CHANGES: CVoteController_TryCastVoteResult = 4;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_SERVER_DISABLE: CVoteController_TryCastVoteResult = 1;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_SYSTEM_ERROR: CVoteController_TryCastVoteResult = 7;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_TEAM_RESTRICTED: CVoteController_TryCastVoteResult = 3;
pub const CVoteController_TryCastVoteResult_CAST_FAIL_VOTE_CLOSED: CVoteController_TryCastVoteResult = 6;
pub const CVoteController_TryCastVoteResult_CAST_OK: CVoteController_TryCastVoteResult = 0;
#[repr(C)]
#[derive(Debug)]
pub struct CBaseIssue {
    pub vtable_: *const CBaseIssue__bindgen_vtable,
    pub m_hPlayerTarget: CHandle,
    pub m_FailedVotes: CUtlVector<
        *mut CBaseIssue_FailedVote,
        CUtlMemory<*mut CBaseIssue_FailedVote>,
    >,
    pub m_szTypeString: [::std::os::raw::c_char; 64usize],
    pub m_szDetailsString: [::std::os::raw::c_char; 64usize],
    pub m_iNumYesVotes: ::std::os::raw::c_int,
    pub m_iNumNoVotes: ::std::os::raw::c_int,
    pub m_iNumPotentialVotes: ::std::os::raw::c_int,
    pub m_flNextCallTime: f32,
    pub m_pVoteController: *mut CVoteController,
}
#[repr(C)]
pub struct CBaseIssue__bindgen_vtable {
    pub CBaseIssue_complete_destructor: unsafe extern "C" fn(arg1: *mut CBaseIssue),
    pub CBaseIssue_deleting_destructor: unsafe extern "C" fn(arg1: *mut CBaseIssue),
    pub CBaseIssue_GetTypeStringLocalized: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseIssue_GetDetailsString: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseIssue_SetIssueDetails: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseIssue_OnVoteFailed: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseIssue_OnVoteStarted: unsafe extern "C" fn(arg1: *mut CBaseIssue),
    pub CBaseIssue_IsEnabled: unsafe extern "C" fn(arg1: *mut CBaseIssue) -> bool,
    pub CBaseIssue_CanTeamCallVote: unsafe extern "C" fn(
        arg1: *const CBaseIssue,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseIssue_RequestCallVote: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: ::std::os::raw::c_int,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut vote_create_failed_t,
        arg5: *mut ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseIssue_IsTeamRestrictedVote: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> bool,
    pub CBaseIssue_GetDisplayString: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseIssue_ExecuteCommand: unsafe extern "C" fn(arg1: *mut CBaseIssue),
    pub CBaseIssue_ListIssueDetails: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: *mut CBasePlayer,
    ),
    pub CBaseIssue_GetVotePassedString: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseIssue_CountPotentialVoters: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> ::std::os::raw::c_int,
    pub CBaseIssue_GetNumberVoteOptions: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
    ) -> ::std::os::raw::c_int,
    pub CBaseIssue_IsYesNoVote: unsafe extern "C" fn(arg1: *mut CBaseIssue) -> bool,
    pub CBaseIssue_GetVoteOptions: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: *mut CUtlVector<
            *const ::std::os::raw::c_char,
            CUtlMemory<*const ::std::os::raw::c_char>,
        >,
    ) -> bool,
    pub CBaseIssue_BRecordVoteFailureEventForEntity: unsafe extern "C" fn(
        arg1: *const CBaseIssue,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseIssue_GetQuorumRatio: unsafe extern "C" fn(arg1: *mut CBaseIssue) -> f32,
    pub CBaseIssue_ProcessResults: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: *const CUtlVector<
            *const ::std::os::raw::c_char,
            CUtlMemory<*const ::std::os::raw::c_char>,
        >,
        arg3: *const ::std::os::raw::c_int,
        arg4: *const __BindgenOpaqueArray8<[u8; 40usize]>,
        arg5: ::std::os::raw::c_int,
        arg6: ::std::os::raw::c_int,
        arg7: ::std::os::raw::c_int,
    ) -> CBaseIssue_EVoteAction,
    pub CBaseIssue_OnVoteEnded: unsafe extern "C" fn(arg1: *mut CBaseIssue),
    pub CBaseIssue_OnPlayerDisconnected: unsafe extern "C" fn(
        arg1: *mut CBaseIssue,
        arg2: *mut CBasePlayer,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBaseIssue_FailedVote {
    pub szFailedVoteParameter: [::std::os::raw::c_char; 64usize],
    pub flLockoutTime: f32,
}
/// Opaque: bindgen cannot express this record's C++ layout, so only its size and alignment are kept.
///
/// Generated as fields, its Rust size is 1456, but C++ says 1448.
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController {
    pub _bindgen_opaque_blob: __BindgenOpaqueArray8<[u8; 1448usize]>,
}
#[repr(C)]
pub struct CVoteController__bindgen_vtable {
    pub CVoteController_complete_destructor: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_SetRefEHandle: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CBaseHandle,
    ),
    pub CVoteController_GetRefEHandle: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> *const CBaseHandle,
    pub CVoteController_GetCollideable: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut ICollideable,
    pub CVoteController_GetNetworkable: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut IServerNetworkable,
    pub CVoteController_GetBaseEntity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CBaseEntity,
    pub CVoteController_GetModelIndex: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_GetModelName: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> string_t,
    pub CVoteController_SetModelIndex: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
    ),
    pub CVoteController_GetServerClass: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut ServerClass,
    pub CVoteController_YouForgotToImplementOrDeclareServerClass: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_GetDataDescMap: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut datamap_t,
    pub CVoteController_GetScriptDesc: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut ScriptClassDesc_t,
    pub CVoteController_SetModelIndexOverride: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub CVoteController_TestCollision: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CVoteController_TestHitboxes: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CVoteController_ComputeWorldSpaceSurroundingBox: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub CVoteController_ShouldCollide: unsafe extern "C" fn(
        arg1: *const CVoteController,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CVoteController_SetOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_SetScriptOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: HSCRIPT,
    ),
    pub CVoteController_ShouldTransmit: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CCheckTransmitInfo,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_UpdateTransmitState: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_SetTransmit: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CCheckTransmitInfo,
        arg3: bool,
    ),
    pub CVoteController_GetTracerType: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *const ::std::os::raw::c_char,
    pub CVoteController_Spawn: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_Precache: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_SetModel: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CVoteController_OnNewModel: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CStudioHdr,
    pub CVoteController_PostConstructor: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CVoteController_PostClientActive: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_ParseMapData: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CEntityMapData,
    ),
    pub CVoteController_KeyValue: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> bool,
    pub CVoteController_KeyValue1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
        arg3: f32,
    ) -> bool,
    pub CVoteController_KeyValue2: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const Vector,
    ) -> bool,
    pub CVoteController_GetKeyValue: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
    ) -> bool,
    pub CVoteController_Activate: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_SetParent: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
    ),
    pub CVoteController_ObjectCaps: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    /// C++ takes `::variant_t` by value. `arg5` points to a temporary copy the caller makes; the callee may modify it, and the caller destroys it after the call.
    pub CVoteController_AcceptInput: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut CBaseEntity,
        arg4: *mut CBaseEntity,
        arg5: *mut variant_t,
        arg6: ::std::os::raw::c_int,
    ) -> bool,
    pub CVoteController_GetInputDispatchEffectPosition: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut Vector,
        arg4: *mut QAngle,
    ),
    pub CVoteController_DrawDebugGeometryOverlays: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_DrawDebugTextOverlays: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_Save: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ISave,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_Restore: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut IRestore,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_ShouldSavePhysics: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_OnSave: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut IEntitySaveUtils,
    ),
    pub CVoteController_OnRestore: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_RequiredEdictIndex: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_MoveDone: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_Think: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_NetworkStateChanged_m_nNextThinkTick: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_nNextThinkTick1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_GetBaseAnimating: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CBaseAnimating,
    pub CVoteController_GetResponseSystem: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut IResponseSystem,
    pub CVoteController_DispatchResponse: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CVoteController_Classify: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> Class_T,
    pub CVoteController_DeathNotice: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_ShouldAttractAutoAim: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_GetAutoAimRadius: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> f32,
    pub CVoteController_GetAutoAimCenter: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> Vector,
    pub CVoteController_GetBeamTraceFilter: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut ITraceFilter,
    pub CVoteController_PassesDamageFilter: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CVoteController_TraceAttack: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CTakeDamageInfo,
        arg3: *const Vector,
        arg4: *mut trace_t,
        arg5: *mut CDmgAccumulator,
    ),
    pub CVoteController_CanBeHitByMeleeAttack: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_OnTakeDamage: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_AdjustDamageDirection: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CTakeDamageInfo,
        arg3: *mut Vector,
        arg4: *mut CBaseEntity,
    ),
    pub CVoteController_TakeHealth: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_IsAlive: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_Event_Killed: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CTakeDamageInfo,
    ),
    pub CVoteController_Event_KilledOther: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
        arg3: *const CTakeDamageInfo,
    ),
    pub CVoteController_BloodColor: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_IsTriggered: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_IsNPC: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsNextBot: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_MyCombatCharacterPointer: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CBaseCombatCharacter,
    pub CVoteController_MyNextBotPointer: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut INextBot,
    pub CVoteController_GetDelay: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> f32,
    pub CVoteController_IsMoving: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_DamageDecal: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CVoteController_DecalTrace: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut trace_t,
        arg3: *const ::std::os::raw::c_char,
    ),
    pub CVoteController_ImpactTrace: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
        arg4: *const ::std::os::raw::c_char,
    ),
    pub CVoteController_OnControls: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_HasTarget: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: string_t,
    ) -> bool,
    pub CVoteController_IsPlayer: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsNetClient: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsTemplate: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_IsBaseObject: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsBaseTrain: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsCombatItem: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsProjectileCollisionTarget: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsFuncLOD: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsBaseProjectile: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsBaseCombatWeapon: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_IsWearable: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_MyCombatWeaponPointer: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CBaseCombatWeapon,
    pub CVoteController_GetServerVehicle: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut IServerVehicle,
    pub CVoteController_IsViewable: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_ChangeTeam: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
    ),
    pub CVoteController_OnEntityEvent: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: EntityEvent_t,
        arg3: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_CanStandOn: unsafe extern "C" fn(
        arg1: *const CVoteController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_CanStandOn1: unsafe extern "C" fn(
        arg1: *const CVoteController,
        arg2: *mut edict_t,
    ) -> bool,
    pub CVoteController_GetEnemy: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CBaseEntity,
    pub CVoteController_GetEnemy1: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> *mut CBaseEntity,
    pub CVoteController_Use: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
        arg3: *mut CBaseEntity,
        arg4: USE_TYPE,
        arg5: f32,
    ),
    pub CVoteController_StartTouch: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_Touch: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_EndTouch: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_StartBlocked: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_Blocked: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ),
    pub CVoteController_EndBlocked: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_PhysicsSimulate: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_UpdateOnRemove: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_StopLoopingSounds: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_SUB_AllowedToFade: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_Teleport: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: *const Vector,
    ),
    pub CVoteController_NotifySystemEvent: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
        arg3: notify_system_event_t,
        arg4: *const notify_system_event_params_t,
    ),
    pub CVoteController_MakeTracer: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
        arg3: *const trace_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CVoteController_GetTracerAttachment: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_FireBullets: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const FireBulletsInfo_t,
    ),
    pub CVoteController_DoImpactEffect: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CVoteController_ModifyFireBulletsDamage: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CTakeDamageInfo,
    ),
    pub CVoteController_Respawn: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *mut CBaseEntity,
    pub CVoteController_IsLockedByMaster: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_GetMaxHealth: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_ModifyOrAppendCriteria: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut AI_CriteriaSet,
    ),
    pub CVoteController_NetworkStateChanged_m_iMaxHealth: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_iMaxHealth1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_iHealth: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_iHealth1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_lifeState: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_lifeState1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_takedamage: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_takedamage1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_RunVScripts: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_GetDamageType: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_GetDamage: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> f32,
    pub CVoteController_SetDamage: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: f32,
    ),
    pub CVoteController_EyePosition: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> Vector,
    pub CVoteController_EyeAngles: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *const QAngle,
    pub CVoteController_LocalEyeAngles: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> *const QAngle,
    pub CVoteController_EarPosition: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> Vector,
    pub CVoteController_BodyTarget: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
        arg3: bool,
    ) -> Vector,
    pub CVoteController_HeadTarget: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
    ) -> Vector,
    pub CVoteController_GetVectors: unsafe extern "C" fn(
        arg1: *const CVoteController,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut Vector,
    ),
    pub CVoteController_GetViewOffset: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> *const Vector,
    pub CVoteController_SetViewOffset: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
    ),
    pub CVoteController_GetSmoothedVelocity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> Vector,
    pub CVoteController_GetVelocity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub CVoteController_FVisible: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_FVisible1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_CanBeSeenBy: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CAI_BaseNPC,
    ) -> bool,
    pub CVoteController_GetAttackDamageScale: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CVoteController_GetReceivedDamageScale: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CVoteController_GetGroundVelocityToApply: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut Vector,
    ),
    pub CVoteController_PhysicsSplash: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: f32,
        arg5: f32,
    ) -> bool,
    pub CVoteController_Splash: unsafe extern "C" fn(arg1: *mut CVoteController),
    pub CVoteController_WorldSpaceCenter: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> *const Vector,
    pub CVoteController_GetSoundEmissionOrigin: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> Vector,
    pub CVoteController_ModifyEmitSoundParams: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut EmitSound_t,
    ),
    pub CVoteController_IsDeflectable: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_Deflected: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
        arg3: *mut Vector,
    ),
    pub CVoteController_CreateVPhysics: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_ForceVPhysicsCollide: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CVoteController_VPhysicsDestroyObject: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_VPhysicsUpdate: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut IPhysicsObject,
    ),
    pub CVoteController_VPhysicsTakeDamage: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_VPhysicsShadowCollision: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CVoteController_VPhysicsShadowUpdate: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut IPhysicsObject,
    ),
    pub CVoteController_VPhysicsCollision: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CVoteController_VPhysicsFriction: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut IPhysicsObject,
        arg3: f32,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
    ),
    pub CVoteController_UpdatePhysicsShadowToCurrentPosition: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: f32,
    ),
    pub CVoteController_VPhysicsGetObjectList: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut *mut IPhysicsObject,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CVoteController_VPhysicsIsFlesh: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_HasPhysicsAttacker: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: f32,
    ) -> *mut CBasePlayer,
    pub CVoteController_PhysicsSolidMaskForEntity: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> ::std::os::raw::c_uint,
    pub CVoteController_ResolveFlyCollisionCustom: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut trace_t,
        arg3: *mut Vector,
    ),
    pub CVoteController_PerformCustomPhysics: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut QAngle,
        arg5: *mut QAngle,
    ),
    pub CVoteController_GetStepOrigin: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> Vector,
    pub CVoteController_GetStepAngles: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> QAngle,
    pub CVoteController_ShouldDrawWaterImpacts: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
    pub CVoteController_NetworkStateChanged_m_fFlags: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_fFlags1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_nWaterLevel: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_nWaterLevel1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_hGroundEntity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_hGroundEntity1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_vecBaseVelocity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_vecBaseVelocity1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_flFriction: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_flFriction1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_vecVelocity: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_vecVelocity1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_NetworkStateChanged_m_vecViewOffset: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ),
    pub CVoteController_NetworkStateChanged_m_vecViewOffset1: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CVoteController_ShouldBlockNav: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_ShouldForceTransmitsForTeam: unsafe extern "C" fn(
        arg1: *mut CVoteController,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CVoteController_IsTruceValidForEnt: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> bool,
    pub CVoteController_GetDefaultItemChargeMeterValue: unsafe extern "C" fn(
        arg1: *const CVoteController,
    ) -> f32,
    pub CVoteController_BCanCallVote: unsafe extern "C" fn(
        arg1: *mut CVoteController,
    ) -> bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController_NetworkVar_m_bIsYesNoVote {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController_NetworkVar_m_iActiveIssueIndex {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController_NetworkVar_m_iOnlyTeamToVote {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController_NetworkVar_m_nPotentialVotes {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController_NetworkVar_m_nVoteIdx {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVoteController_NetworkVar_m_nVoteOptionCount {
    pub m_Value: [::std::os::raw::c_int; 5usize],
}
include!("layout_assertions.rs");
