// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of autoaim_params_t"][::std::mem::size_of::<autoaim_params_t>() - 40usize];
    [
        "Alignment of autoaim_params_t",
    ][::std::mem::align_of::<autoaim_params_t>() - 4usize];
    [
        "Offset of field: autoaim_params_t::m_vecAutoAimDir",
    ][::std::mem::offset_of!(autoaim_params_t, m_vecAutoAimDir) - 0usize];
    [
        "Offset of field: autoaim_params_t::m_vecAutoAimPoint",
    ][::std::mem::offset_of!(autoaim_params_t, m_vecAutoAimPoint) - 12usize];
    [
        "Offset of field: autoaim_params_t::m_hAutoAimEntity",
    ][::std::mem::offset_of!(autoaim_params_t, m_hAutoAimEntity) - 24usize];
    [
        "Offset of field: autoaim_params_t::m_bAutoAimAssisting",
    ][::std::mem::offset_of!(autoaim_params_t, m_bAutoAimAssisting) - 28usize];
    [
        "Offset of field: autoaim_params_t::m_bOnTargetNatural",
    ][::std::mem::offset_of!(autoaim_params_t, m_bOnTargetNatural) - 29usize];
    [
        "Offset of field: autoaim_params_t::m_fScale",
    ][::std::mem::offset_of!(autoaim_params_t, m_fScale) - 32usize];
    [
        "Offset of field: autoaim_params_t::m_fMaxDist",
    ][::std::mem::offset_of!(autoaim_params_t, m_fMaxDist) - 36usize];
};
