[package]
name = "source_sdk_2013_declmacros"
version = "0.1.0-alpha.7"
edition = "2024"
rust-version = "1.99.0"

authors.workspace = true
license.workspace = true
repository.workspace = true

description = "Declarative macros re-exported by the source_sdk_2013 crate"
categories = []
keywords = []

[dependencies]
crys_bricks.workspace = true
