// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type PhysGunDrop_t = ::std::os::raw::c_int;
pub type PhysGunForce_t = ::std::os::raw::c_int;
pub type PhysGunPickup_t = ::std::os::raw::c_int;
pub const PhysGunDrop_t_DROPPED_BY_CANNON: PhysGunDrop_t = 2;
pub const PhysGunDrop_t_DROPPED_BY_PLAYER: PhysGunDrop_t = 0;
pub const PhysGunDrop_t_LAUNCHED_BY_CANNON: PhysGunDrop_t = 3;
pub const PhysGunDrop_t_THROWN_BY_PLAYER: PhysGunDrop_t = 1;
pub const PhysGunForce_t_PHYSGUN_FORCE_DROPPED: PhysGunForce_t = 0;
pub const PhysGunForce_t_PHYSGUN_FORCE_LAUNCHED: PhysGunForce_t = 3;
pub const PhysGunForce_t_PHYSGUN_FORCE_PUNTED: PhysGunForce_t = 2;
pub const PhysGunForce_t_PHYSGUN_FORCE_THROWN: PhysGunForce_t = 1;
pub const PhysGunPickup_t_PICKED_UP_BY_CANNON: PhysGunPickup_t = 0;
pub const PhysGunPickup_t_PICKED_UP_BY_PLAYER: PhysGunPickup_t = 2;
pub const PhysGunPickup_t_PUNTED_BY_CANNON: PhysGunPickup_t = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CDefaultPlayerPickupVPhysics {
    pub vtable_: *const CDefaultPlayerPickupVPhysics__bindgen_vtable,
}
#[repr(C)]
pub struct CDefaultPlayerPickupVPhysics__bindgen_vtable {
    pub CDefaultPlayerPickupVPhysics_OnAttemptPhysGunPickup: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
        arg3: PhysGunPickup_t,
    ) -> bool,
    pub CDefaultPlayerPickupVPhysics_OnFailedPhysGunPickup: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: Vector,
    ) -> *mut CBaseEntity,
    pub CDefaultPlayerPickupVPhysics_OnPhysGunPickup: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
        arg3: PhysGunPickup_t,
    ),
    pub CDefaultPlayerPickupVPhysics_OnPhysGunDrop: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
        arg3: PhysGunDrop_t,
    ),
    pub CDefaultPlayerPickupVPhysics_HasPreferredCarryAnglesForPlayer: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
    ) -> bool,
    /// C++ returns `::QAngle` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CDefaultPlayerPickupVPhysics_PreferredCarryAngles: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut QAngle,
    ) -> *mut QAngle,
    pub CDefaultPlayerPickupVPhysics_ForcePhysgunOpen: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
    ) -> bool,
    /// C++ returns `::AngularImpulse` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CDefaultPlayerPickupVPhysics_PhysGunLaunchAngularImpulse: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut AngularImpulse,
    ) -> *mut AngularImpulse,
    pub CDefaultPlayerPickupVPhysics_ShouldPuntUseLaunchForces: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: PhysGunForce_t,
    ) -> bool,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CDefaultPlayerPickupVPhysics_PhysGunLaunchVelocity: unsafe extern "C" fn(
        arg1: *mut CDefaultPlayerPickupVPhysics,
        arg2: *mut Vector,
        arg3: *const Vector,
        arg4: f32,
    ) -> *mut Vector,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPlayerPickupVPhysics {
    pub vtable_: *const IPlayerPickupVPhysics__bindgen_vtable,
}
#[repr(C)]
pub struct IPlayerPickupVPhysics__bindgen_vtable {
    pub IPlayerPickupVPhysics_OnAttemptPhysGunPickup: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
        arg3: PhysGunPickup_t,
    ) -> bool,
    pub IPlayerPickupVPhysics_OnFailedPhysGunPickup: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: Vector,
    ) -> *mut CBaseEntity,
    pub IPlayerPickupVPhysics_OnPhysGunPickup: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
        arg3: PhysGunPickup_t,
    ),
    pub IPlayerPickupVPhysics_OnPhysGunDrop: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
        arg3: PhysGunDrop_t,
    ),
    pub IPlayerPickupVPhysics_HasPreferredCarryAnglesForPlayer: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
    ) -> bool,
    /// C++ returns `::QAngle` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub IPlayerPickupVPhysics_PreferredCarryAngles: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut QAngle,
    ) -> *mut QAngle,
    pub IPlayerPickupVPhysics_ForcePhysgunOpen: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut CBasePlayer,
    ) -> bool,
    /// C++ returns `::AngularImpulse` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub IPlayerPickupVPhysics_PhysGunLaunchAngularImpulse: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut AngularImpulse,
    ) -> *mut AngularImpulse,
    pub IPlayerPickupVPhysics_ShouldPuntUseLaunchForces: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: PhysGunForce_t,
    ) -> bool,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub IPlayerPickupVPhysics_PhysGunLaunchVelocity: unsafe extern "C" fn(
        arg1: *mut IPlayerPickupVPhysics,
        arg2: *mut Vector,
        arg3: *const Vector,
        arg4: f32,
    ) -> *mut Vector,
}
include!("layout_assertions.rs");
