// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of IPartitionEnumerator",
    ][::std::mem::size_of::<IPartitionEnumerator>() - 8usize];
    [
        "Alignment of IPartitionEnumerator",
    ][::std::mem::align_of::<IPartitionEnumerator>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of IPartitionQueryCallback",
    ][::std::mem::size_of::<IPartitionQueryCallback>() - 8usize];
    [
        "Alignment of IPartitionQueryCallback",
    ][::std::mem::align_of::<IPartitionQueryCallback>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ISpatialPartition"][::std::mem::size_of::<ISpatialPartition>() - 8usize];
    [
        "Alignment of ISpatialPartition",
    ][::std::mem::align_of::<ISpatialPartition>() - 8usize];
};
