// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CUtlMemory__bindgen_ty_1 = ::std::os::raw::c_int;
pub const CUtlMemory_EXTERNAL_BUFFER_MARKER: CUtlMemory__bindgen_ty_1 = 0;
pub const CUtlMemory_EXTERNAL_CONST_BUFFER_MARKER: CUtlMemory__bindgen_ty_1 = 0;
#[repr(C)]
#[derive(Debug)]
pub struct CUtlMemory<T> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
    pub m_pMemory: *mut T,
    pub m_nAllocationCount: ::std::os::raw::c_int,
    pub m_nGrowSize: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug)]
pub struct CUtlMemoryConservative<T> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
    pub m_pMemory: *mut T,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUtlMemoryConservative_Iterator_t {
    pub index: ::std::os::raw::c_int,
    pub limit: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CUtlMemory_Iterator_t<I> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<I>>,
    pub index: I,
}
