// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IAudioOutputStream"][::std::mem::size_of::<IAudioOutputStream>() - 8usize];
    [
        "Alignment of IAudioOutputStream",
    ][::std::mem::align_of::<IAudioOutputStream>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IEngineSound"][::std::mem::size_of::<IEngineSound>() - 8usize];
    ["Alignment of IEngineSound"][::std::mem::align_of::<IEngineSound>() - 8usize];
};
