// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::super::__bindgen_prelude::*;
pub type CEconItem_BaseClass = GCSDK_CSharedObject;
#[repr(C)]
pub struct CEconItem {
    pub _base: GCSDK_CSharedObject,
    pub _base_1: __BindgenOpaqueArray8<[u8; 8usize]>,
    pub m_pszSmallIcon: *const ::std::os::raw::c_char,
    pub m_pszLargeIcon: *const ::std::os::raw::c_char,
    pub m_ulID: uint64,
    pub m_unAccountID: uint32,
    pub m_unInventory: uint32,
    pub m_unDefIndex: item_definition_index_t,
    pub m_unLevel: uint8,
    pub m_nQuality: uint8,
    pub m_unFlags: uint8,
    pub m_unOrigin: uint8,
    pub m_unStyle: style_index_t,
    pub m_dirtyBits: CEconItem_dirty_bits_t,
    pub m_EquipInstanceSingleton: CEconItem_EquippedInstance_t,
    pub m_CustomAttribSingleton: CEconItem_attribute_t,
    pub m_pCustomData: *mut CEconItemCustomData,
}
#[repr(C)]
pub struct CEconItem__bindgen_vtable {
    pub CEconItem_complete_destructor: unsafe extern "C" fn(arg1: *mut CEconItem),
    pub CEconItem_deleting_destructor: unsafe extern "C" fn(arg1: *mut CEconItem),
    pub CEconItem_GetTypeID: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> ::std::os::raw::c_int,
    pub CEconItem_BParseFromMessage: unsafe extern "C" fn(
        arg1: *mut CEconItem,
        arg2: *const CUtlBuffer,
    ) -> bool,
    pub CEconItem_BParseFromMessage1: unsafe extern "C" fn(
        arg1: *mut CEconItem,
        arg2: *const std_string,
    ) -> bool,
    pub CEconItem_BUpdateFromNetwork: unsafe extern "C" fn(
        arg1: *mut CEconItem,
        arg2: *const GCSDK_CSharedObject,
    ) -> bool,
    pub CEconItem_BIsKeyLess: unsafe extern "C" fn(
        arg1: *const CEconItem,
        arg2: *const GCSDK_CSharedObject,
    ) -> bool,
    pub CEconItem_Copy: unsafe extern "C" fn(
        arg1: *mut CEconItem,
        arg2: *const GCSDK_CSharedObject,
    ),
    pub CEconItem_Dump: unsafe extern "C" fn(arg1: *const CEconItem),
    pub CEconItem_BShouldDeleteByCache: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> bool,
    /// C++ returns `::CUtlString` by value. `arg1` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub CEconItem_GetDebugString: unsafe extern "C" fn(
        arg1: *mut CUtlString,
        arg2: *const CEconItem,
    ) -> *mut CUtlString,
    pub CEconItem_GetItemDefinition: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> *const GameItemDefinition_t,
    pub CEconItem_IterateAttributes: unsafe extern "C" fn(
        arg1: *const CEconItem,
        arg2: *mut IEconItemAttributeIterator,
    ),
    pub CEconItem_GetID: unsafe extern "C" fn(arg1: *const CEconItem) -> itemid_t,
    pub CEconItem_GetAccountID: unsafe extern "C" fn(arg1: *const CEconItem) -> uint32,
    pub CEconItem_GetItemLevel: unsafe extern "C" fn(arg1: *const CEconItem) -> uint32,
    pub CEconItem_GetQuality: unsafe extern "C" fn(arg1: *const CEconItem) -> int32,
    pub CEconItem_GetQuantity: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> ::std::os::raw::c_int,
    pub CEconItem_GetFlags: unsafe extern "C" fn(arg1: *const CEconItem) -> uint8,
    pub CEconItem_GetOrigin: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> eEconItemOrigin,
    pub CEconItem_GetStyle: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> style_index_t,
    pub CEconItem_GetCustomName: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> *const ::std::os::raw::c_char,
    pub CEconItem_GetCustomDesc: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> *const ::std::os::raw::c_char,
    pub CEconItem_GetInUse: unsafe extern "C" fn(arg1: *const CEconItem) -> bool,
    pub CEconItem_IsTradable: unsafe extern "C" fn(arg1: *const CEconItem) -> bool,
    pub CEconItem_IsMarketable: unsafe extern "C" fn(arg1: *const CEconItem) -> bool,
    pub CEconItem_IsCommodity: unsafe extern "C" fn(arg1: *const CEconItem) -> bool,
    pub CEconItem_IsUsableInCrafting: unsafe extern "C" fn(
        arg1: *const CEconItem,
    ) -> bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CEconItem_EquippedInstance_t {
    pub m_unEquippedClass: equipped_class_t,
    pub m_unEquippedSlot: equipped_slot_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct CEconItem_attribute_t {
    pub m_unDefinitionIndex: attrib_definition_index_t,
    pub m_value: attribute_data_union_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CEconItem_dirty_bits_t {
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 1usize]>,
}
impl CEconItem_dirty_bits_t {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn m_bHasAttribSingleton_raw(this: *const Self) -> uint8 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 1usize],
                >>::raw_get_const::<
                    2usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u8,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn m_bHasEquipSingleton_raw(this: *const Self) -> uint8 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 1usize],
                >>::raw_get_const::<
                    1usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u8,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn m_bInUse_raw(this: *const Self) -> uint8 {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 1usize],
                >>::raw_get_const::<
                    0usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u8,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        m_bInUse: uint8,
        m_bHasEquipSingleton: uint8,
        m_bHasAttribSingleton: uint8,
    ) -> __BindgenBitfieldUnit<[u8; 1usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 1usize]> = Default::default();
        __bindgen_bitfield_unit
            .set_const::<
                0usize,
                1u8,
            >({
                let m_bInUse: u8 = unsafe { ::std::mem::transmute(m_bInUse) };
                m_bInUse as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                1usize,
                1u8,
            >({
                let m_bHasEquipSingleton: u8 = unsafe {
                    ::std::mem::transmute(m_bHasEquipSingleton)
                };
                m_bHasEquipSingleton as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                2usize,
                1u8,
            >({
                let m_bHasAttribSingleton: u8 = unsafe {
                    ::std::mem::transmute(m_bHasAttribSingleton)
                };
                m_bHasAttribSingleton as u64
            });
        __bindgen_bitfield_unit
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_m_bHasAttribSingleton_raw(this: *mut Self, val: uint8) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 1usize],
            >>::raw_set_const::<
                2usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_m_bHasEquipSingleton_raw(this: *mut Self, val: uint8) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 1usize],
            >>::raw_set_const::<
                1usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_m_bInUse_raw(this: *mut Self, val: uint8) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 1usize],
            >>::raw_set_const::<
                0usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn m_bHasAttribSingleton(&self) -> uint8 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<2usize, 1u8>() as u8)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn m_bHasEquipSingleton(&self) -> uint8 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<1usize, 1u8>() as u8)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn m_bInUse(&self) -> uint8 {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<0usize, 1u8>() as u8)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_m_bHasAttribSingleton(&mut self, val: uint8) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<2usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_m_bHasEquipSingleton(&mut self, val: uint8) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<1usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_m_bInUse(&mut self, val: uint8) {
        unsafe {
            let val: u8 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 1u8>(val as u64)
        }
    }
}
#[repr(C)]
pub struct CEconItemCustomData {
    pub m_vecAttributes: CUtlVector<
        CEconItem_attribute_t,
        CUtlMemory<CEconItem_attribute_t>,
    >,
    pub m_pInteriorItem: *mut CEconItem,
    pub m_ulOriginalID: uint64,
    pub m_unQuantity: uint16,
    pub m_vecEquipped: CUtlVector<
        CEconItem_EquippedInstance_t,
        CUtlMemory<CEconItem_EquippedInstance_t>,
    >,
}
#[repr(C)]
pub struct CEconItemHandle {
    pub _base: GCSDK_ISharedObjectListener,
    pub m_pItem: *mut CEconItem,
    pub m_iItemID: itemid_t,
    pub m_OwnerSteamID: CSteamID,
}
#[repr(C)]
pub struct CEconItemHandle__bindgen_vtable {
    pub CEconItemHandle_SOCreated: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: *const GCSDK_CSharedObject,
        arg4: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_PreSOUpdate: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_SOUpdated: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: *const GCSDK_CSharedObject,
        arg4: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_PostSOUpdate: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_SODestroyed: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: *const GCSDK_CSharedObject,
        arg4: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_SOCacheSubscribed: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_SOCacheUnsubscribed: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
        arg2: *const CSteamID,
        arg3: GCSDK_ESOCacheEvent,
    ),
    pub CEconItemHandle_complete_destructor: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
    ),
    pub CEconItemHandle_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut CEconItemHandle,
    ),
}
#[repr(C)]
#[derive(Debug)]
pub struct GCSDK_CColumnSet {
    _unused: [u8; 0],
}
include!("layout_assertions.rs");
