// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CVariant = CVariantBase;
pub type CVariantDefaultAllocator__bindgen_ty_1 = ::std::os::raw::c_uint;
pub type HSCRIPT = *mut HSCRIPT__;
pub const CVariantDefaultAllocator_ALWAYS_COPY: CVariantDefaultAllocator__bindgen_ty_1 = 0;
#[repr(C)]
pub struct CVariantBase {
    pub __bindgen_anon_1: CVariantBase__bindgen_ty_1,
    pub m_type: int16,
    pub m_flags: uint16,
}
#[repr(C)]
pub union CVariantBase__bindgen_ty_1 {
    pub m_int: ::std::os::raw::c_int,
    pub m_uint: uint,
    pub m_float: f32,
    pub m_pszString: *const ::std::os::raw::c_char,
    pub m_pVector: *const Vector,
    pub m_pData: *mut ::std::os::raw::c_void,
    pub m_char: ::std::os::raw::c_char,
    pub m_bool: bool,
    pub m_hScript: HSCRIPT,
    pub m_hEntity: uint32,
    pub m_uint64: uint64,
    pub m_int64: int64,
    pub m_float64: float64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVariantDefaultAllocator {
    pub _address: u8,
}
include!("layout_assertions.rs");
