// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_bFlipViewModel",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_bFlipViewModel>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_bFlipViewModel",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_bFlipViewModel>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_flNextPrimaryAttack",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_flNextPrimaryAttack>()
        - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_flNextPrimaryAttack",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_flNextPrimaryAttack>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_flNextSecondaryAttack",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_flNextSecondaryAttack>()
        - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_flNextSecondaryAttack",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_flNextSecondaryAttack>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_flTimeWeaponIdle",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_flTimeWeaponIdle>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_flTimeWeaponIdle",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_flTimeWeaponIdle>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_hOwner",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_hOwner>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_hOwner",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_hOwner>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iClip1",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iClip1>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iClip1",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iClip1>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iClip2",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iClip2>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iClip2",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iClip2>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iPrimaryAmmoType",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iPrimaryAmmoType>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iPrimaryAmmoType",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iPrimaryAmmoType>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iSecondaryAmmoType",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iSecondaryAmmoType>()
        - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iSecondaryAmmoType",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iSecondaryAmmoType>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iState",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iState>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iState",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iState>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iViewModelIndex",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iViewModelIndex>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iViewModelIndex",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iViewModelIndex>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_iWorldModelIndex",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_iWorldModelIndex>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_iWorldModelIndex",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_iWorldModelIndex>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_nCustomViewmodelModelIndex",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_nCustomViewmodelModelIndex>()
        - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_nCustomViewmodelModelIndex",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_nCustomViewmodelModelIndex>()
        - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon_NetworkVar_m_nViewModelIndex",
    ][::std::mem::size_of::<CBaseCombatWeapon_NetworkVar_m_nViewModelIndex>() - 1usize];
    [
        "Alignment of CBaseCombatWeapon_NetworkVar_m_nViewModelIndex",
    ][::std::mem::align_of::<CBaseCombatWeapon_NetworkVar_m_nViewModelIndex>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of CBaseCombatWeapon",
    ][::std::mem::size_of::<CBaseCombatWeapon>() - 2232usize];
    [
        "Alignment of CBaseCombatWeapon",
    ][::std::mem::align_of::<CBaseCombatWeapon>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CDmgAccumulator"][::std::mem::size_of::<CDmgAccumulator>() - 160usize];
    ["Alignment of CDmgAccumulator"][::std::mem::align_of::<CDmgAccumulator>() - 8usize];
    [
        "Offset of field: CDmgAccumulator::m_updatedInfo",
    ][::std::mem::offset_of!(CDmgAccumulator, m_updatedInfo) - 8usize];
    [
        "Offset of field: CDmgAccumulator::m_TargetsDmgInfo",
    ][::std::mem::offset_of!(CDmgAccumulator, m_TargetsDmgInfo) - 112usize];
    [
        "Offset of field: CDmgAccumulator::m_bActive",
    ][::std::mem::offset_of!(CDmgAccumulator, m_bActive) - 152usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of acttable_t"][::std::mem::size_of::<acttable_t>() - 12usize];
    ["Alignment of acttable_t"][::std::mem::align_of::<acttable_t>() - 4usize];
    [
        "Offset of field: acttable_t::baseAct",
    ][::std::mem::offset_of!(acttable_t, baseAct) - 0usize];
    [
        "Offset of field: acttable_t::weaponAct",
    ][::std::mem::offset_of!(acttable_t, weaponAct) - 4usize];
    [
        "Offset of field: acttable_t::required",
    ][::std::mem::offset_of!(acttable_t, required) - 8usize];
};
