// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IEngineTrace"][::std::mem::size_of::<IEngineTrace>() - 8usize];
    ["Alignment of IEngineTrace"][::std::mem::align_of::<IEngineTrace>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IEntityEnumerator"][::std::mem::size_of::<IEntityEnumerator>() - 8usize];
    [
        "Alignment of IEntityEnumerator",
    ][::std::mem::align_of::<IEntityEnumerator>() - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ITraceFilter"][::std::mem::size_of::<ITraceFilter>() - 8usize];
    ["Alignment of ITraceFilter"][::std::mem::align_of::<ITraceFilter>() - 8usize];
};
