// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug)]
pub struct CBaseTempEntity {
    pub vtable_: *const CBaseTempEntity__bindgen_vtable,
    pub m_pszName: *const ::std::os::raw::c_char,
    pub m_pNext: *mut CBaseTempEntity,
}
#[repr(C)]
pub struct CBaseTempEntity__bindgen_vtable {
    pub CBaseTempEntity_GetServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseTempEntity,
    ) -> *mut ServerClass,
    pub CBaseTempEntity_YouForgotToImplementOrDeclareServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseTempEntity,
    ) -> ::std::os::raw::c_int,
    pub CBaseTempEntity_complete_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseTempEntity,
    ),
    pub CBaseTempEntity_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseTempEntity,
    ),
    pub CBaseTempEntity_Test: unsafe extern "C" fn(
        arg1: *mut CBaseTempEntity,
        arg2: *const Vector,
        arg3: *const QAngle,
    ),
    pub CBaseTempEntity_Create: unsafe extern "C" fn(
        arg1: *mut CBaseTempEntity,
        arg2: *mut IRecipientFilter,
        arg3: f32,
    ),
    pub CBaseTempEntity_Precache: unsafe extern "C" fn(arg1: *mut CBaseTempEntity),
}
include!("layout_assertions.rs");
