// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CFogController_BaseClass = CBaseEntity;
#[repr(C)]
pub struct CFogController {
    pub _base: CBaseEntity,
    pub m_fog: CFogController_NetworkVar_m_fog,
    pub m_bUseAngles: bool,
    pub m_iChangedVariables: ::std::os::raw::c_int,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CFogController_NetworkVar_m_fog {
    pub _base: fogparams_t,
}
#[repr(C)]
pub struct CFogController__bindgen_vtable {
    pub CFogController_destructor: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void,
    pub CFogController_SetRefEHandle: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CBaseHandle,
    ),
    pub CFogController_GetRefEHandle: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> *const CBaseHandle,
    pub CFogController_GetCollideable: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut ICollideable,
    pub CFogController_GetNetworkable: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut IServerNetworkable,
    pub CFogController_GetBaseEntity: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CBaseEntity,
    pub CFogController_GetModelIndex: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_GetModelName: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> string_t,
    pub CFogController_SetModelIndex: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
    ),
    pub CFogController_GetServerClass: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut ServerClass,
    pub CFogController_YouForgotToImplementOrDeclareServerClass: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_GetDataDescMap: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut datamap_t,
    pub CFogController_GetScriptDesc: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut ScriptClassDesc_t,
    pub CFogController_SetModelIndexOverride: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub CFogController_TestCollision: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CFogController_TestHitboxes: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CFogController_ComputeWorldSpaceSurroundingBox: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub CFogController_ShouldCollide: unsafe extern "C" fn(
        arg1: *const CFogController,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CFogController_SetOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_SetScriptOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: HSCRIPT,
    ),
    pub CFogController_ShouldTransmit: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CCheckTransmitInfo,
    ) -> ::std::os::raw::c_int,
    pub CFogController_UpdateTransmitState: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_SetTransmit: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CCheckTransmitInfo,
        arg3: bool,
    ),
    pub CFogController_GetTracerType: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *const ::std::os::raw::c_char,
    pub CFogController_Spawn: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_Precache: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_SetModel: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CFogController_OnNewModel: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CStudioHdr,
    pub CFogController_PostConstructor: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CFogController_PostClientActive: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_ParseMapData: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CEntityMapData,
    ),
    pub CFogController_KeyValue2: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const Vector,
    ) -> bool,
    pub CFogController_KeyValue1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
        arg3: f32,
    ) -> bool,
    pub CFogController_KeyValue: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> bool,
    pub CFogController_GetKeyValue: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
    ) -> bool,
    pub CFogController_Activate: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_SetParent: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
    ),
    pub CFogController_ObjectCaps: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_AcceptInput: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut CBaseEntity,
        arg4: *mut CBaseEntity,
        arg5: variant_t,
        arg6: ::std::os::raw::c_int,
    ) -> bool,
    pub CFogController_GetInputDispatchEffectPosition: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut Vector,
        arg4: *mut QAngle,
    ),
    pub CFogController_DrawDebugGeometryOverlays: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_DrawDebugTextOverlays: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_Save: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ISave,
    ) -> ::std::os::raw::c_int,
    pub CFogController_Restore: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut IRestore,
    ) -> ::std::os::raw::c_int,
    pub CFogController_ShouldSavePhysics: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_OnSave: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut IEntitySaveUtils,
    ),
    pub CFogController_OnRestore: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_RequiredEdictIndex: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_MoveDone: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_Think: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_NetworkStateChanged_m_nNextThinkTick1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_nNextThinkTick: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_GetBaseAnimating: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CBaseAnimating,
    pub CFogController_GetResponseSystem: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut IResponseSystem,
    pub CFogController_DispatchResponse: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CFogController_Classify: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> Class_T,
    pub CFogController_DeathNotice: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_ShouldAttractAutoAim: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CFogController_GetAutoAimRadius: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> f32,
    pub CFogController_GetAutoAimCenter: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> Vector,
    pub CFogController_GetBeamTraceFilter: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut ITraceFilter,
    pub CFogController_PassesDamageFilter: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CFogController_TraceAttack: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CTakeDamageInfo,
        arg3: *const Vector,
        arg4: *mut trace_t,
        arg5: *mut CDmgAccumulator,
    ),
    pub CFogController_CanBeHitByMeleeAttack: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CFogController_OnTakeDamage: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CFogController_AdjustDamageDirection: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CTakeDamageInfo,
        arg3: *mut Vector,
        arg4: *mut CBaseEntity,
    ),
    pub CFogController_TakeHealth: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CFogController_IsAlive: unsafe extern "C" fn(arg1: *mut CFogController) -> bool,
    pub CFogController_Event_Killed: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CTakeDamageInfo,
    ),
    pub CFogController_Event_KilledOther: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
        arg3: *const CTakeDamageInfo,
    ),
    pub CFogController_BloodColor: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_IsTriggered: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CFogController_IsNPC: unsafe extern "C" fn(arg1: *const CFogController) -> bool,
    pub CFogController_MyCombatCharacterPointer: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CBaseCombatCharacter,
    pub CFogController_MyNextBotPointer: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut INextBot,
    pub CFogController_GetDelay: unsafe extern "C" fn(arg1: *mut CFogController) -> f32,
    pub CFogController_IsMoving: unsafe extern "C" fn(arg1: *mut CFogController) -> bool,
    pub CFogController_DamageDecal: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CFogController_DecalTrace: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut trace_t,
        arg3: *const ::std::os::raw::c_char,
    ),
    pub CFogController_ImpactTrace: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
        arg4: *const ::std::os::raw::c_char,
    ),
    pub CFogController_OnControls: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CFogController_HasTarget: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: string_t,
    ) -> bool,
    pub CFogController_IsPlayer: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_IsNetClient: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_IsTemplate: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_IsBaseObject: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_IsBaseTrain: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_IsCombatItem: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_IsBaseCombatWeapon: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_IsWearable: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_MyCombatWeaponPointer: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CBaseCombatWeapon,
    pub CFogController_GetServerVehicle: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut IServerVehicle,
    pub CFogController_IsViewable: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_ChangeTeam: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
    ),
    pub CFogController_OnEntityEvent: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: EntityEvent_t,
        arg3: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_CanStandOn1: unsafe extern "C" fn(
        arg1: *const CFogController,
        arg2: *mut edict_t,
    ) -> bool,
    pub CFogController_CanStandOn: unsafe extern "C" fn(
        arg1: *const CFogController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CFogController_GetEnemy1: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> *mut CBaseEntity,
    pub CFogController_GetEnemy: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CBaseEntity,
    pub CFogController_Use: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
        arg3: *mut CBaseEntity,
        arg4: USE_TYPE,
        arg5: f32,
    ),
    pub CFogController_StartTouch: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_Touch: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_EndTouch: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_StartBlocked: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_Blocked: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ),
    pub CFogController_EndBlocked: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_PhysicsSimulate: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_UpdateOnRemove: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_StopLoopingSounds: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_SUB_AllowedToFade: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_Teleport: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: *const Vector,
    ),
    pub CFogController_NotifySystemEvent: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
        arg3: notify_system_event_t,
        arg4: *const notify_system_event_params_t,
    ),
    pub CFogController_MakeTracer: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
        arg3: *const trace_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CFogController_GetTracerAttachment: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_FireBullets: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const FireBulletsInfo_t,
    ),
    pub CFogController_DoImpactEffect: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CFogController_ModifyFireBulletsDamage: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CTakeDamageInfo,
    ),
    pub CFogController_Respawn: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *mut CBaseEntity,
    pub CFogController_IsLockedByMaster: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_GetMaxHealth: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_ModifyOrAppendCriteria: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut AI_CriteriaSet,
    ),
    pub CFogController_NetworkStateChanged_m_iMaxHealth1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_iMaxHealth: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_iHealth1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_iHealth: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_lifeState1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_lifeState: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_takedamage1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_takedamage: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_RunVScripts: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_GetDamageType: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> ::std::os::raw::c_int,
    pub CFogController_GetDamage: unsafe extern "C" fn(arg1: *mut CFogController) -> f32,
    pub CFogController_SetDamage: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: f32,
    ),
    pub CFogController_EyePosition: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> Vector,
    pub CFogController_EyeAngles: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *const QAngle,
    pub CFogController_LocalEyeAngles: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> *const QAngle,
    pub CFogController_EarPosition: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> Vector,
    pub CFogController_BodyTarget: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
        arg3: bool,
    ) -> Vector,
    pub CFogController_HeadTarget: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
    ) -> Vector,
    pub CFogController_GetVectors: unsafe extern "C" fn(
        arg1: *const CFogController,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut Vector,
    ),
    pub CFogController_GetViewOffset: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> *const Vector,
    pub CFogController_SetViewOffset: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
    ),
    pub CFogController_GetSmoothedVelocity: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> Vector,
    pub CFogController_GetVelocity: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub CFogController_FVisible1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CFogController_FVisible: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CFogController_CanBeSeenBy: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CAI_BaseNPC,
    ) -> bool,
    pub CFogController_GetAttackDamageScale: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CFogController_GetReceivedDamageScale: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CFogController_GetGroundVelocityToApply: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut Vector,
    ),
    pub CFogController_PhysicsSplash: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: f32,
        arg5: f32,
    ) -> bool,
    pub CFogController_Splash: unsafe extern "C" fn(arg1: *mut CFogController),
    pub CFogController_WorldSpaceCenter: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> *const Vector,
    pub CFogController_GetSoundEmissionOrigin: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> Vector,
    pub CFogController_ModifyEmitSoundParams: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut EmitSound_t,
    ),
    pub CFogController_IsDeflectable: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_Deflected: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
        arg3: *mut Vector,
    ),
    pub CFogController_CreateVPhysics: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_ForceVPhysicsCollide: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CFogController_VPhysicsDestroyObject: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_VPhysicsUpdate: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut IPhysicsObject,
    ),
    pub CFogController_VPhysicsTakeDamage: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CFogController_VPhysicsShadowCollision: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CFogController_VPhysicsShadowUpdate: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut IPhysicsObject,
    ),
    pub CFogController_VPhysicsCollision: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CFogController_VPhysicsFriction: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut IPhysicsObject,
        arg3: f32,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
    ),
    pub CFogController_UpdatePhysicsShadowToCurrentPosition: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: f32,
    ),
    pub CFogController_VPhysicsGetObjectList: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut *mut IPhysicsObject,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CFogController_VPhysicsIsFlesh: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_HasPhysicsAttacker: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: f32,
    ) -> *mut CBasePlayer,
    pub CFogController_PhysicsSolidMaskForEntity: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> ::std::os::raw::c_uint,
    pub CFogController_ResolveFlyCollisionCustom: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut trace_t,
        arg3: *mut Vector,
    ),
    pub CFogController_PerformCustomPhysics: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut QAngle,
        arg5: *mut QAngle,
    ),
    pub CFogController_GetStepOrigin: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> Vector,
    pub CFogController_GetStepAngles: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> QAngle,
    pub CFogController_ShouldDrawWaterImpacts: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
    pub CFogController_NetworkStateChanged_m_fFlags1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_fFlags: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_nWaterLevel1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_nWaterLevel: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_hGroundEntity1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_hGroundEntity: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_vecBaseVelocity1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_vecBaseVelocity: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_flFriction1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_flFriction: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_vecVelocity1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_vecVelocity: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_NetworkStateChanged_m_vecViewOffset1: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CFogController_NetworkStateChanged_m_vecViewOffset: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ),
    pub CFogController_ShouldBlockNav: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_ShouldForceTransmitsForTeam: unsafe extern "C" fn(
        arg1: *mut CFogController,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CFogController_IsTruceValidForEnt: unsafe extern "C" fn(
        arg1: *const CFogController,
    ) -> bool,
    pub CFogController_BCanCallVote: unsafe extern "C" fn(
        arg1: *mut CFogController,
    ) -> bool,
}
include!("layout_assertions.rs");
