// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseCombatCharacter_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseCombatCharacter_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseCombatWeapon_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseCombatWeapon_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseCombatWeapon_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseCombatWeapon_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseEntity_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBasePlayer_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBasePlayer_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: CHandle_open0_CBaseViewModel_close0",
    ][::std::mem::size_of::<CHandle>() - 4usize];
    [
        "Align of template specialization: CHandle_open0_CBaseViewModel_close0",
    ][::std::mem::align_of::<CHandle>() - 4usize];
};
