[package]
name = "metamod_source_sys"
edition = "2024"
rust-version = "1.99.0"

authors.workspace = true
license.workspace = true
repository.workspace = true

description = "Low-level bindings for Metamod:Source."
categories = ["external-ffi-bindings"]
keywords = []

# Planning on changing this to `0.1.0+metamod-1.12.0-2.0.0`
# Once this is extracted to its own repository
version.workspace = true

[dependencies]

[build-dependencies]
anyhow.workspace = true
cc = "1.4.4"
crys_bricks.workspace = true
dotenv = "0.15.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]
