// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug)]
pub struct CPhysCollide {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vcollide_t {
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize]>,
    pub descSize: ::std::os::raw::c_ushort,
    pub solids: *mut *mut CPhysCollide,
    pub pKeyValues: *mut ::std::os::raw::c_char,
}
impl vcollide_t {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn isPacked(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<15usize, 1u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn isPacked_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 2usize],
                >>::raw_get_const::<
                    15usize,
                    1u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        solidCount: ::std::os::raw::c_ushort,
        isPacked: ::std::os::raw::c_ushort,
    ) -> __BindgenBitfieldUnit<[u8; 2usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 2usize]> = Default::default();
        __bindgen_bitfield_unit
            .set_const::<
                0usize,
                15u8,
            >({
                let solidCount: u16 = unsafe { ::std::mem::transmute(solidCount) };
                solidCount as u64
            });
        __bindgen_bitfield_unit
            .set_const::<
                15usize,
                1u8,
            >({
                let isPacked: u16 = unsafe { ::std::mem::transmute(isPacked) };
                isPacked as u64
            });
        __bindgen_bitfield_unit
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_isPacked(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<15usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_isPacked_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 2usize],
            >>::raw_set_const::<
                15usize,
                1u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_solidCount(&mut self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 15u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_solidCount_raw(this: *mut Self, val: ::std::os::raw::c_ushort) {
        unsafe {
            let val: u16 = ::std::mem::transmute(val);
            <__BindgenBitfieldUnit<
                [u8; 2usize],
            >>::raw_set_const::<
                0usize,
                15u8,
            >(::std::ptr::addr_of_mut!((*this)._bitfield_1), val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn solidCount(&self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(self._bitfield_1.get_const::<0usize, 15u8>() as u16)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn solidCount_raw(this: *const Self) -> ::std::os::raw::c_ushort {
        unsafe {
            ::std::mem::transmute(
                <__BindgenBitfieldUnit<
                    [u8; 2usize],
                >>::raw_get_const::<
                    0usize,
                    15u8,
                >(::std::ptr::addr_of!((*this)._bitfield_1)) as u16,
            )
        }
    }
}
include!("layout_assertions.rs");
