// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type MDLCacheDataType_t = ::std::os::raw::c_uint;
pub type MDLCacheFlush_t = ::std::os::raw::c_uint;
pub const MDLCacheDataType_t_MDLCACHE_ANIMBLOCK: MDLCacheDataType_t = 3;
pub const MDLCacheDataType_t_MDLCACHE_DECODEDANIMBLOCK: MDLCacheDataType_t = 6;
pub const MDLCacheDataType_t_MDLCACHE_STUDIOHDR: MDLCacheDataType_t = 0;
pub const MDLCacheDataType_t_MDLCACHE_STUDIOHWDATA: MDLCacheDataType_t = 1;
pub const MDLCacheDataType_t_MDLCACHE_VCOLLIDE: MDLCacheDataType_t = 2;
pub const MDLCacheDataType_t_MDLCACHE_VERTEXES: MDLCacheDataType_t = 5;
pub const MDLCacheDataType_t_MDLCACHE_VIRTUALMODEL: MDLCacheDataType_t = 4;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_ALL: MDLCacheFlush_t = 4294967295;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_ANIMBLOCK: MDLCacheFlush_t = 8;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_AUTOPLAY: MDLCacheFlush_t = 32;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_IGNORELOCK: MDLCacheFlush_t = 2147483648;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_STUDIOHDR: MDLCacheFlush_t = 1;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_STUDIOHWDATA: MDLCacheFlush_t = 2;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_VCOLLIDE: MDLCacheFlush_t = 4;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_VERTEXES: MDLCacheFlush_t = 64;
pub const MDLCacheFlush_t_MDLCACHE_FLUSH_VIRTUALMODEL: MDLCacheFlush_t = 16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMDLCache {
    pub vtable_: *const IMDLCache__bindgen_vtable,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMDLCacheNotify {
    pub vtable_: *const IMDLCacheNotify__bindgen_vtable,
}
#[repr(C)]
pub struct IMDLCacheNotify__bindgen_vtable {
    pub IMDLCacheNotify_OnDataLoaded: unsafe extern "C" fn(
        arg1: *mut IMDLCacheNotify,
        arg2: MDLCacheDataType_t,
        arg3: MDLHandle_t,
    ),
    pub IMDLCacheNotify_OnDataUnloaded: unsafe extern "C" fn(
        arg1: *mut IMDLCacheNotify,
        arg2: MDLCacheDataType_t,
        arg3: MDLHandle_t,
    ),
}
#[repr(C)]
pub struct IMDLCache__bindgen_vtable {
    pub IMDLCache_Connect: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: CreateInterfaceFn,
    ) -> bool,
    pub IMDLCache_Disconnect: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_QueryInterface: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void,
    pub IMDLCache_Init: unsafe extern "C" fn(arg1: *mut IMDLCache) -> InitReturnVal_t,
    pub IMDLCache_Shutdown: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_SetCacheNotify: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: *mut IMDLCacheNotify,
    ),
    pub IMDLCache_FindMDL: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: *const ::std::os::raw::c_char,
    ) -> MDLHandle_t,
    pub IMDLCache_AddRef: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> ::std::os::raw::c_int,
    pub IMDLCache_Release: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> ::std::os::raw::c_int,
    pub IMDLCache_GetRef: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> ::std::os::raw::c_int,
    pub IMDLCache_GetStudioHdr: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut studiohdr_t,
    pub IMDLCache_GetHardwareData: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut studiohwdata_t,
    pub IMDLCache_GetVCollide: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut vcollide_t,
    pub IMDLCache_GetAnimBlock: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_uchar,
    pub IMDLCache_GetVirtualModel: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut virtualmodel_t,
    pub IMDLCache_GetAutoplayList: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: *mut *mut ::std::os::raw::c_ushort,
    ) -> ::std::os::raw::c_int,
    pub IMDLCache_GetVertexData: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut vertexFileHeader_t,
    pub IMDLCache_TouchAllData_Old: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ),
    pub IMDLCache_SetUserData: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: *mut ::std::os::raw::c_void,
    ),
    pub IMDLCache_GetUserData: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut ::std::os::raw::c_void,
    pub IMDLCache_IsErrorModel: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> bool,
    pub IMDLCache_Flush: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLCacheFlush_t,
    ),
    pub IMDLCache_Flush1: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub IMDLCache_GetModelName: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *const ::std::os::raw::c_char,
    pub IMDLCache_GetVirtualModelFast: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: *const studiohdr_t,
        arg3: MDLHandle_t,
    ) -> *mut virtualmodel_t,
    pub IMDLCache_BeginLock: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_EndLock: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_GetFrameUnlockCounterPtrOLD: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
    ) -> *mut ::std::os::raw::c_int,
    pub IMDLCache_FinishPendingLoads: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_GetVCollideEx: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: bool,
    ) -> *mut vcollide_t,
    pub IMDLCache_GetVCollideSize: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: *mut ::std::os::raw::c_int,
    ) -> bool,
    pub IMDLCache_GetAsyncLoad: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLCacheDataType_t,
    ) -> bool,
    pub IMDLCache_SetAsyncLoad: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLCacheDataType_t,
        arg3: bool,
    ) -> bool,
    pub IMDLCache_BeginMapLoad: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_EndMapLoad: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_MarkAsLoaded: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ),
    pub IMDLCache_InitPreloadData: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: bool,
    ),
    pub IMDLCache_ShutdownPreloadData: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_IsDataLoaded: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
        arg3: MDLCacheDataType_t,
    ) -> bool,
    pub IMDLCache_GetFrameUnlockCounterPtr: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLCacheDataType_t,
    ) -> *mut ::std::os::raw::c_int,
    pub IMDLCache_LockStudioHdr: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> *mut studiohdr_t,
    pub IMDLCache_UnlockStudioHdr: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ),
    pub IMDLCache_PreloadModel: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> bool,
    pub IMDLCache_ResetErrorModelStatus: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ),
    pub IMDLCache_MarkFrame: unsafe extern "C" fn(arg1: *mut IMDLCache),
    pub IMDLCache_TouchAllData: unsafe extern "C" fn(
        arg1: *mut IMDLCache,
        arg2: MDLHandle_t,
    ) -> bool,
}
include!("layout_assertions.rs");
