// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type AngularImpulse = Vector;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct QAngle {
    pub x: vec_t,
    pub y: vec_t,
    pub z: vec_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Quaternion {
    pub x: vec_t,
    pub y: vec_t,
    pub z: vec_t,
    pub w: vec_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RadianEuler {
    pub x: vec_t,
    pub y: vec_t,
    pub z: vec_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Vector {
    pub x: vec_t,
    pub y: vec_t,
    pub z: vec_t,
}
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct VectorAligned {
    pub _base: Vector,
}
include!("layout_assertions.rs");
