// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CreateInterfaceFn = ::std::option::Option<
    unsafe extern "C" fn(
        pName: *const ::std::os::raw::c_char,
        pReturnCode: *mut ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug)]
pub struct IBaseInterface {
    pub vtable_: *const IBaseInterface__bindgen_vtable,
}
#[repr(C)]
pub struct IBaseInterface__bindgen_vtable {
    pub IBaseInterface_complete_destructor: unsafe extern "C" fn(
        arg1: *mut IBaseInterface,
    ),
    pub IBaseInterface_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut IBaseInterface,
    ),
}
include!("layout_assertions.rs");
