// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CBitVecT<BASE_OPS> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<BASE_OPS>>,
    pub _base: BASE_OPS,
}
#[repr(C)]
#[derive(Debug)]
pub struct CVarBitVec {
    pub _base: CBitVecT<CVarBitVecBase<::std::os::raw::c_ushort>>,
}
#[repr(C)]
#[derive(Debug)]
pub struct CVarBitVecBase<BITCOUNTTYPE> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<BITCOUNTTYPE>>,
    pub m_numBits: BITCOUNTTYPE,
    pub m_numInts: BITCOUNTTYPE,
    pub m_iBitStringStorage: uint32,
    pub m_pInt: *mut uint32,
}
include!("layout_assertions.rs");
