[package]
name = "metamod_source"
version.workspace = true
edition = "2024"
rust-version = "1.98.1"

authors.workspace = true
license.workspace = true
repository.workspace = true

description = "Higher-level bindings for Metamod:Source."
categories = ["api-bindings"]
keywords = ["gamedev", "source-engine", "metamod"]

[features]
## Console commands and hooks for `source_sdk_2013`.
sdk = ["dep:source_sdk_2013", "dep:thiserror"]

[dependencies]
crys_bricks.workspace = true
source_sdk_2013 = { path = "../sdk", version = "0.1.0-alpha.2", optional = true }
sys = { path = "../metamod_sys", version = "0.1.0-alpha.2", package = "metamod_source_sys" }
thiserror = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]
