// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of CSoundParameters"][::std::mem::size_of::<CSoundParameters>() - 164usize];
    [
        "Alignment of CSoundParameters",
    ][::std::mem::align_of::<CSoundParameters>() - 4usize];
    [
        "Offset of field: CSoundParameters::channel",
    ][::std::mem::offset_of!(CSoundParameters, channel) - 0usize];
    [
        "Offset of field: CSoundParameters::volume",
    ][::std::mem::offset_of!(CSoundParameters, volume) - 4usize];
    [
        "Offset of field: CSoundParameters::pitch",
    ][::std::mem::offset_of!(CSoundParameters, pitch) - 8usize];
    [
        "Offset of field: CSoundParameters::pitchlow",
    ][::std::mem::offset_of!(CSoundParameters, pitchlow) - 12usize];
    [
        "Offset of field: CSoundParameters::pitchhigh",
    ][::std::mem::offset_of!(CSoundParameters, pitchhigh) - 16usize];
    [
        "Offset of field: CSoundParameters::soundlevel",
    ][::std::mem::offset_of!(CSoundParameters, soundlevel) - 20usize];
    [
        "Offset of field: CSoundParameters::play_to_owner_only",
    ][::std::mem::offset_of!(CSoundParameters, play_to_owner_only) - 24usize];
    [
        "Offset of field: CSoundParameters::count",
    ][::std::mem::offset_of!(CSoundParameters, count) - 28usize];
    [
        "Offset of field: CSoundParameters::soundname",
    ][::std::mem::offset_of!(CSoundParameters, soundname) - 32usize];
    [
        "Offset of field: CSoundParameters::delay_msec",
    ][::std::mem::offset_of!(CSoundParameters, delay_msec) - 160usize];
};
