[alias]

# Base command for generating bindings
_bind = [
	"run",
	"--package", "source_sdk_2013_bindgen_runner",
	"--release", # it takes less time to compile in the release profile than to run the debug binary
]

bind-linux = [
	"_bind",
	"--target", "x86_64-unknown-linux-gnu",
	"--",
	"--manifest-dir", "./crates/sdk_sys_linux64/",
	"--target", "x86_64-unknown-linux-gnu"
]

bind-windows = [
	"_bind",
	"--target", "x86_64-pc-windows-msvc",
	"--",
	"--manifest-dir", "./crates/sdk_sys_win64/",
	"--target", "x86_64-pc-windows-msvc"
]

bind-wsl = [
	"bind-linux",
	"--dotenv", "./wsl.env"
]

rscodefmt = [
	"rscode", "fmt",
	"--package", "crys_bricks",
	"--package", "metamod_source",
	"--package", "metamod_source_sys",
	"--package", "source_sdk_2013",
	"--package", "source_sdk_2013_bindgen",
	"--package", "source_sdk_2013_bindgen_runner",
	"--package", "source_sdk_2013_declmacros",
	"--package", "source_sdk_2013_raw",
	"--package", "source_sdk_2013_sys",
	# these format their bindings automatically!
	# "--package", "source_sdk_2013_sys_x64_linux",
	# "--package", "source_sdk_2013_sys_x64_windows",
	"--all-features",
]

# cargo publish-p1 && cargo publish-p2 && cargo publish-p3 && cargo publish-p4 && cargo publish-p5
publish-p1 = [
	"publish",
	"--package", "metamod_source_sys",
	"--package", "source_sdk_2013_bindgen",
	"--package", "source_sdk_2013_declmacros",
	"--package", "source_sdk_2013_sys_x64_linux",
	"--package", "source_sdk_2013_sys_x64_windows",
]

publish-p2 = [
	"publish",
	"--package", "source_sdk_2013_sys",
]

publish-p3 = [
	"publish",
	"--package", "source_sdk_2013_raw",
]

publish-p4 = [
	"publish",
	"--package", "source_sdk_2013",
]

publish-p5 = [
	"publish",
	"--package", "metamod_source",
]
