// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug)]
pub struct IServerEntity {
    pub vtable_: *const IServerEntity__bindgen_vtable,
}
#[repr(C)]
pub struct IServerEntity__bindgen_vtable {
    pub IServerEntity_complete_destructor: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
    ),
    pub IServerEntity_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
    ),
    pub IServerEntity_SetRefEHandle: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
        arg2: *const CBaseHandle,
    ),
    pub IServerEntity_GetRefEHandle: unsafe extern "C" fn(
        arg1: *const IServerEntity,
    ) -> *const CBaseHandle,
    pub IServerEntity_GetCollideable: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
    ) -> *mut ICollideable,
    pub IServerEntity_GetNetworkable: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
    ) -> *mut IServerNetworkable,
    pub IServerEntity_GetBaseEntity: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
    ) -> *mut CBaseEntity,
    pub IServerEntity_GetModelIndex: unsafe extern "C" fn(
        arg1: *const IServerEntity,
    ) -> ::std::os::raw::c_int,
    pub IServerEntity_GetModelName: unsafe extern "C" fn(
        arg1: *const IServerEntity,
    ) -> string_t,
    pub IServerEntity_SetModelIndex: unsafe extern "C" fn(
        arg1: *mut IServerEntity,
        arg2: ::std::os::raw::c_int,
    ),
}
include!("layout_assertions.rs");
