// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct gamevcollisionevent_t {
    pub _base: vcollisionevent_t,
    pub preVelocity: [Vector; 2usize],
    pub postVelocity: [Vector; 2usize],
    pub preAngularVelocity: [AngularImpulse; 2usize],
    pub pEntities: [*mut CBaseEntity; 2usize],
}
include!("layout_assertions.rs");
