// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug)]
pub struct IResponseFilter {
    pub vtable_: *const IResponseFilter__bindgen_vtable,
}
#[repr(C)]
pub struct IResponseFilter__bindgen_vtable {
    pub IResponseFilter_complete_destructor: unsafe extern "C" fn(
        arg1: *mut IResponseFilter,
    ),
    pub IResponseFilter_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut IResponseFilter,
    ),
    pub IResponseFilter_IsValidResponse: unsafe extern "C" fn(
        arg1: *mut IResponseFilter,
        arg2: ResponseType_t,
        arg3: *const ::std::os::raw::c_char,
    ) -> bool,
}
#[repr(C)]
#[derive(Debug)]
pub struct IResponseSystem {
    pub vtable_: *const IResponseSystem__bindgen_vtable,
}
#[repr(C)]
pub struct IResponseSystem__bindgen_vtable {
    pub IResponseSystem_complete_destructor: unsafe extern "C" fn(
        arg1: *mut IResponseSystem,
    ),
    pub IResponseSystem_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut IResponseSystem,
    ),
    pub IResponseSystem_FindBestResponse: unsafe extern "C" fn(
        arg1: *mut IResponseSystem,
        arg2: *const AI_CriteriaSet,
        arg3: *mut AI_Response,
        arg4: *mut IResponseFilter,
    ) -> bool,
    pub IResponseSystem_GetAllResponses: unsafe extern "C" fn(
        arg1: *mut IResponseSystem,
        arg2: *mut CUtlVector<*mut AI_Response, CUtlMemory<*mut AI_Response>>,
    ),
    pub IResponseSystem_PrecacheResponses: unsafe extern "C" fn(
        arg1: *mut IResponseSystem,
        arg2: bool,
    ),
}
include!("layout_assertions.rs");
