// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of WeaponProficiencyInfo_t",
    ][::std::mem::size_of::<WeaponProficiencyInfo_t>() - 8usize];
    [
        "Alignment of WeaponProficiencyInfo_t",
    ][::std::mem::align_of::<WeaponProficiencyInfo_t>() - 4usize];
    [
        "Offset of field: WeaponProficiencyInfo_t::spreadscale",
    ][::std::mem::offset_of!(WeaponProficiencyInfo_t, spreadscale) - 0usize];
    [
        "Offset of field: WeaponProficiencyInfo_t::bias",
    ][::std::mem::offset_of!(WeaponProficiencyInfo_t, bias) - 4usize];
};
