// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of template specialization: MurmurHash3Functor_open0_int_close0",
    ][::std::mem::size_of::<MurmurHash3Functor>() - 1usize];
    [
        "Align of template specialization: MurmurHash3Functor_open0_int_close0",
    ][::std::mem::align_of::<MurmurHash3Functor>() - 1usize];
};
