// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug)]
pub struct CAchievementData {
    pub aDamagers: __BindgenOpaqueArray8<[u8; 48usize]>,
    pub aDamageEvents: __BindgenOpaqueArray8<[u8; 48usize]>,
    pub aTargets: __BindgenOpaqueArray8<[u8; 48usize]>,
    pub aSentryDamagers: __BindgenOpaqueArray8<[u8; 48usize]>,
    pub aPushers: __BindgenOpaqueArray8<[u8; 48usize]>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CEntityDamageHistoryLess {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CEntityHistoryLess {
    pub _address: u8,
}
#[repr(C)]
pub struct EntityDamageHistory_t {
    pub _base: EntityHistory_t,
    pub nDamageAmount: ::std::os::raw::c_int,
}
#[repr(C)]
pub struct EntityHistory_t {
    pub hEntity: EHANDLE,
    pub hObject: EHANDLE,
    pub flTimeDamage: f32,
}
include!("layout_assertions.rs");
