// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPhysicsCollisionData {
    pub vtable_: *const IPhysicsCollisionData__bindgen_vtable,
}
#[repr(C)]
pub struct IPhysicsCollisionData__bindgen_vtable {
    pub IPhysicsCollisionData_GetSurfaceNormal: unsafe extern "C" fn(
        arg1: *mut IPhysicsCollisionData,
        arg2: *mut Vector,
    ),
    pub IPhysicsCollisionData_GetContactPoint: unsafe extern "C" fn(
        arg1: *mut IPhysicsCollisionData,
        arg2: *mut Vector,
    ),
    pub IPhysicsCollisionData_GetContactSpeed: unsafe extern "C" fn(
        arg1: *mut IPhysicsCollisionData,
        arg2: *mut Vector,
    ),
}
#[repr(C)]
#[derive(Debug)]
pub struct IPhysicsConstraint {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct IPhysicsFrictionSnapshot {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct IPhysicsObject {
    pub vtable_: *const IPhysicsObject__bindgen_vtable,
}
#[repr(C)]
pub struct IPhysicsObject__bindgen_vtable {
    pub IPhysicsObject_destructor: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void,
    pub IPhysicsObject_IsStatic: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsAsleep: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsTrigger: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsFluid: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsHinged: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsCollisionEnabled: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsGravityEnabled: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsDragEnabled: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsMotionEnabled: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsMoveable: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_IsAttachedToConstraint: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: bool,
    ) -> bool,
    pub IPhysicsObject_EnableCollisions: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: bool,
    ),
    pub IPhysicsObject_EnableGravity: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: bool,
    ),
    pub IPhysicsObject_EnableDrag: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: bool,
    ),
    pub IPhysicsObject_EnableMotion: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: bool,
    ),
    pub IPhysicsObject_SetGameData: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub IPhysicsObject_GetGameData: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> *mut ::std::os::raw::c_void,
    pub IPhysicsObject_SetGameFlags: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_ushort,
    ),
    pub IPhysicsObject_GetGameFlags: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> ::std::os::raw::c_ushort,
    pub IPhysicsObject_SetGameIndex: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_ushort,
    ),
    pub IPhysicsObject_GetGameIndex: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> ::std::os::raw::c_ushort,
    pub IPhysicsObject_SetCallbackFlags: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_ushort,
    ),
    pub IPhysicsObject_GetCallbackFlags: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> ::std::os::raw::c_ushort,
    pub IPhysicsObject_Wake: unsafe extern "C" fn(arg1: *mut IPhysicsObject),
    pub IPhysicsObject_Sleep: unsafe extern "C" fn(arg1: *mut IPhysicsObject),
    pub IPhysicsObject_RecheckCollisionFilter: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
    ),
    pub IPhysicsObject_RecheckContactPoints: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
    ),
    pub IPhysicsObject_SetMass: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: f32,
    ),
    pub IPhysicsObject_GetMass: unsafe extern "C" fn(arg1: *const IPhysicsObject) -> f32,
    pub IPhysicsObject_GetInvMass: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> f32,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub IPhysicsObject_GetInertia: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
    ) -> *mut Vector,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub IPhysicsObject_GetInvInertia: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub IPhysicsObject_SetInertia: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
    ),
    pub IPhysicsObject_SetDamping: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const f32,
        arg3: *const f32,
    ),
    pub IPhysicsObject_GetDamping: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut f32,
        arg3: *mut f32,
    ),
    pub IPhysicsObject_SetDragCoefficient: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *mut f32,
        arg3: *mut f32,
    ),
    pub IPhysicsObject_SetBuoyancyRatio: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: f32,
    ),
    pub IPhysicsObject_GetMaterialIndex: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> ::std::os::raw::c_int,
    pub IPhysicsObject_SetMaterialIndex: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_int,
    ),
    pub IPhysicsObject_GetContents: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> ::std::os::raw::c_uint,
    pub IPhysicsObject_SetContents: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_uint,
    ),
    pub IPhysicsObject_GetSphereRadius: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> f32,
    pub IPhysicsObject_GetEnergy: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> f32,
    /// C++ returns `::Vector` by value. `arg2` is the hidden result pointer: the callee constructs the result in the uninitialized storage it points to, and returns it.
    pub IPhysicsObject_GetMassCenterLocalSpace: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
    ) -> *mut Vector,
    pub IPhysicsObject_SetPosition: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: bool,
    ),
    pub IPhysicsObject_SetPositionMatrix: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const matrix3x4_t,
        arg3: bool,
    ),
    pub IPhysicsObject_GetPosition: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *mut QAngle,
    ),
    pub IPhysicsObject_GetPositionMatrix: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut matrix3x4_t,
    ),
    pub IPhysicsObject_SetVelocity: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
        arg3: *const AngularImpulse,
    ),
    pub IPhysicsObject_SetVelocityInstantaneous: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
        arg3: *const AngularImpulse,
    ),
    pub IPhysicsObject_GetVelocity: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub IPhysicsObject_AddVelocity: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
        arg3: *const AngularImpulse,
    ),
    pub IPhysicsObject_GetVelocityAtPoint: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *const Vector,
        arg3: *mut Vector,
    ),
    pub IPhysicsObject_GetImplicitVelocity: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub IPhysicsObject_LocalToWorld: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *const Vector,
    ),
    pub IPhysicsObject_WorldToLocal: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *const Vector,
    ),
    pub IPhysicsObject_LocalToWorldVector: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *const Vector,
    ),
    pub IPhysicsObject_WorldToLocalVector: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *const Vector,
    ),
    pub IPhysicsObject_ApplyForceCenter: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
    ),
    pub IPhysicsObject_ApplyForceOffset: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
        arg3: *const Vector,
    ),
    pub IPhysicsObject_ApplyTorqueCenter: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const AngularImpulse,
    ),
    pub IPhysicsObject_CalculateForceOffset: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: *mut Vector,
        arg5: *mut AngularImpulse,
    ),
    pub IPhysicsObject_CalculateVelocityOffset: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: *mut Vector,
        arg5: *mut AngularImpulse,
    ),
    pub IPhysicsObject_CalculateLinearDrag: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *const Vector,
    ) -> f32,
    pub IPhysicsObject_CalculateAngularDrag: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *const Vector,
    ) -> f32,
    pub IPhysicsObject_GetContactPoint: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *mut *mut IPhysicsObject,
    ) -> bool,
    pub IPhysicsObject_SetShadow: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: f32,
        arg3: f32,
        arg4: bool,
        arg5: bool,
    ),
    pub IPhysicsObject_UpdateShadow: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: bool,
        arg5: f32,
    ),
    pub IPhysicsObject_GetShadowPosition: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
        arg2: *mut Vector,
        arg3: *mut QAngle,
    ) -> ::std::os::raw::c_int,
    pub IPhysicsObject_GetShadowController: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> *mut IPhysicsShadowController,
    pub IPhysicsObject_RemoveShadowController: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
    ),
    pub IPhysicsObject_ComputeShadowControl: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *const hlshadowcontrol_params_t,
        arg3: f32,
        arg4: f32,
    ) -> f32,
    pub IPhysicsObject_GetCollide: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> *const CPhysCollide,
    pub IPhysicsObject_GetName: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> *const ::std::os::raw::c_char,
    pub IPhysicsObject_BecomeTrigger: unsafe extern "C" fn(arg1: *mut IPhysicsObject),
    pub IPhysicsObject_RemoveTrigger: unsafe extern "C" fn(arg1: *mut IPhysicsObject),
    pub IPhysicsObject_BecomeHinged: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: ::std::os::raw::c_int,
    ),
    pub IPhysicsObject_RemoveHinged: unsafe extern "C" fn(arg1: *mut IPhysicsObject),
    pub IPhysicsObject_CreateFrictionSnapshot: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
    ) -> *mut IPhysicsFrictionSnapshot,
    pub IPhysicsObject_DestroyFrictionSnapshot: unsafe extern "C" fn(
        arg1: *mut IPhysicsObject,
        arg2: *mut IPhysicsFrictionSnapshot,
    ),
    pub IPhysicsObject_OutputDebugInfo: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ),
    pub IPhysicsObject_GetBuoyancyRatio: unsafe extern "C" fn(
        arg1: *const IPhysicsObject,
    ) -> f32,
}
#[repr(C)]
#[derive(Debug)]
pub struct IPhysicsPlayerController {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct IPhysicsShadowController {
    pub vtable_: *const IPhysicsShadowController__bindgen_vtable,
}
#[repr(C)]
pub struct IPhysicsShadowController__bindgen_vtable {
    pub IPhysicsShadowController_destructor: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void,
    pub IPhysicsShadowController_Update: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: f32,
    ),
    pub IPhysicsShadowController_MaxSpeed: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: f32,
        arg3: f32,
    ),
    pub IPhysicsShadowController_StepUp: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: f32,
    ),
    pub IPhysicsShadowController_SetTeleportDistance: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: f32,
    ),
    pub IPhysicsShadowController_AllowsTranslation: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
    ) -> bool,
    pub IPhysicsShadowController_AllowsRotation: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
    ) -> bool,
    pub IPhysicsShadowController_SetPhysicallyControlled: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: bool,
    ),
    pub IPhysicsShadowController_IsPhysicallyControlled: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
    ) -> bool,
    pub IPhysicsShadowController_GetLastImpulse: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: *mut Vector,
    ),
    pub IPhysicsShadowController_UseShadowMaterial: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: bool,
    ),
    pub IPhysicsShadowController_ObjectMaterialChanged: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: ::std::os::raw::c_int,
    ),
    pub IPhysicsShadowController_GetTargetPosition: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: *mut Vector,
        arg3: *mut QAngle,
    ) -> f32,
    pub IPhysicsShadowController_GetTeleportDistance: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
    ) -> f32,
    pub IPhysicsShadowController_GetMaxSpeed: unsafe extern "C" fn(
        arg1: *mut IPhysicsShadowController,
        arg2: *mut f32,
        arg3: *mut f32,
    ),
}
#[repr(C)]
#[derive(Debug)]
pub struct IPhysicsSurfaceProps {
    pub vtable_: *const IPhysicsSurfaceProps__bindgen_vtable,
}
#[repr(C)]
pub struct IPhysicsSurfaceProps__bindgen_vtable {
    pub IPhysicsSurfaceProps_destructor: unsafe extern "C" fn(
        arg1: *mut IPhysicsSurfaceProps,
        arg2: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void,
    pub IPhysicsSurfaceProps_ParseSurfaceData: unsafe extern "C" fn(
        arg1: *mut IPhysicsSurfaceProps,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub IPhysicsSurfaceProps_SurfacePropCount: unsafe extern "C" fn(
        arg1: *const IPhysicsSurfaceProps,
    ) -> ::std::os::raw::c_int,
    pub IPhysicsSurfaceProps_GetSurfaceIndex: unsafe extern "C" fn(
        arg1: *const IPhysicsSurfaceProps,
        arg2: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
    pub IPhysicsSurfaceProps_GetPhysicsProperties: unsafe extern "C" fn(
        arg1: *const IPhysicsSurfaceProps,
        arg2: ::std::os::raw::c_int,
        arg3: *mut f32,
        arg4: *mut f32,
        arg5: *mut f32,
        arg6: *mut f32,
    ),
    pub IPhysicsSurfaceProps_GetSurfaceData: unsafe extern "C" fn(
        arg1: *mut IPhysicsSurfaceProps,
        arg2: ::std::os::raw::c_int,
    ) -> *mut surfacedata_t,
    pub IPhysicsSurfaceProps_GetString: unsafe extern "C" fn(
        arg1: *const IPhysicsSurfaceProps,
        arg2: ::std::os::raw::c_ushort,
    ) -> *const ::std::os::raw::c_char,
    pub IPhysicsSurfaceProps_GetPropName: unsafe extern "C" fn(
        arg1: *const IPhysicsSurfaceProps,
        arg2: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub IPhysicsSurfaceProps_SetWorldMaterialIndexTable: unsafe extern "C" fn(
        arg1: *mut IPhysicsSurfaceProps,
        arg2: *mut ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub IPhysicsSurfaceProps_GetPhysicsParameters: unsafe extern "C" fn(
        arg1: *const IPhysicsSurfaceProps,
        arg2: ::std::os::raw::c_int,
        arg3: *mut surfacephysicsparams_t,
    ),
}
#[repr(C)]
#[derive(Debug)]
pub struct IRestore {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct ISave {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hlshadowcontrol_params_t {
    pub targetPosition: Vector,
    pub targetRotation: QAngle,
    pub maxAngular: f32,
    pub maxDampAngular: f32,
    pub maxSpeed: f32,
    pub maxDampSpeed: f32,
    pub dampFactor: f32,
    pub teleportDistance: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct surfaceaudioparams_t {
    pub reflectivity: f32,
    pub hardnessFactor: f32,
    pub roughnessFactor: f32,
    pub roughThreshold: f32,
    pub hardThreshold: f32,
    pub hardVelocityThreshold: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct surfacedata_t {
    pub physics: surfacephysicsparams_t,
    pub audio: surfaceaudioparams_t,
    pub sounds: surfacesoundnames_t,
    pub game: surfacegameprops_t,
    pub soundhandles: surfacesoundhandles_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct surfacegameprops_t {
    pub maxSpeedFactor: f32,
    pub jumpFactor: f32,
    pub material: ::std::os::raw::c_ushort,
    pub climbable: ::std::os::raw::c_uchar,
    pub pad: ::std::os::raw::c_uchar,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct surfacephysicsparams_t {
    pub friction: f32,
    pub elasticity: f32,
    pub density: f32,
    pub thickness: f32,
    pub dampening: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct surfacesoundhandles_t {
    pub stepleft: ::std::os::raw::c_short,
    pub stepright: ::std::os::raw::c_short,
    pub impactSoft: ::std::os::raw::c_short,
    pub impactHard: ::std::os::raw::c_short,
    pub scrapeSmooth: ::std::os::raw::c_short,
    pub scrapeRough: ::std::os::raw::c_short,
    pub bulletImpact: ::std::os::raw::c_short,
    pub rolling: ::std::os::raw::c_short,
    pub breakSound: ::std::os::raw::c_short,
    pub strainSound: ::std::os::raw::c_short,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct surfacesoundnames_t {
    pub stepleft: ::std::os::raw::c_ushort,
    pub stepright: ::std::os::raw::c_ushort,
    pub impactSoft: ::std::os::raw::c_ushort,
    pub impactHard: ::std::os::raw::c_ushort,
    pub scrapeSmooth: ::std::os::raw::c_ushort,
    pub scrapeRough: ::std::os::raw::c_ushort,
    pub bulletImpact: ::std::os::raw::c_ushort,
    pub rolling: ::std::os::raw::c_ushort,
    pub breakSound: ::std::os::raw::c_ushort,
    pub strainSound: ::std::os::raw::c_ushort,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vcollisionevent_t {
    pub pObjects: [*mut IPhysicsObject; 2usize],
    pub surfaceProps: [::std::os::raw::c_int; 2usize],
    pub isCollision: bool,
    pub isShadowCollision: bool,
    pub deltaCollisionTime: f32,
    pub collisionSpeed: f32,
    pub pInternalData: *mut IPhysicsCollisionData,
}
include!("layout_assertions.rs");
