// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type ThreadId_t = uint64;
#[repr(C)]
pub struct CThreadEvent {
    pub _base: CThreadSyncObject,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CThreadFastMutex {
    pub m_ownerID: ThreadId_t,
    pub m_depth: ::std::os::raw::c_int,
}
#[repr(C)]
pub struct CThreadMutex {
    pub m_Mutex: pthread_mutex_t,
    pub m_Attr: pthread_mutexattr_t,
    pub m_currentOwnerID: ThreadId_t,
    pub m_lockCount: uint16,
    pub m_bTrace: bool,
}
#[repr(C)]
pub struct CThreadRWLock {
    pub m_mutex: CThreadMutex,
    pub m_CanWrite: CThreadEvent,
    pub m_CanRead: CThreadEvent,
    pub m_nWriters: ::std::os::raw::c_int,
    pub m_nActiveReaders: ::std::os::raw::c_int,
    pub m_nPendingReaders: ::std::os::raw::c_int,
}
#[repr(C)]
pub struct CThreadSyncObject {
    pub m_Mutex: pthread_mutex_t,
    pub m_Condition: pthread_cond_t,
    pub m_bInitalized: bool,
    pub m_cSet: ::std::os::raw::c_int,
    pub m_bManualReset: bool,
    pub m_bWakeForEvent: bool,
}
include!("layout_assertions.rs");
