// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of DVariant"][::std::mem::size_of::<DVariant>() - 24usize];
    ["Alignment of DVariant"][::std::mem::align_of::<DVariant>() - 8usize];
    [
        "Offset of field: DVariant::m_Type",
    ][::std::mem::offset_of!(DVariant, m_Type) - 16usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    [
        "Size of DVariant__bindgen_ty_1",
    ][::std::mem::size_of::<DVariant__bindgen_ty_1>() - 16usize];
    [
        "Alignment of DVariant__bindgen_ty_1",
    ][::std::mem::align_of::<DVariant__bindgen_ty_1>() - 8usize];
    [
        "Offset of field: DVariant__bindgen_ty_1::m_Float",
    ][::std::mem::offset_of!(DVariant__bindgen_ty_1, m_Float) - 0usize];
    [
        "Offset of field: DVariant__bindgen_ty_1::m_Int",
    ][::std::mem::offset_of!(DVariant__bindgen_ty_1, m_Int) - 0usize];
    [
        "Offset of field: DVariant__bindgen_ty_1::m_pString",
    ][::std::mem::offset_of!(DVariant__bindgen_ty_1, m_pString) - 0usize];
    [
        "Offset of field: DVariant__bindgen_ty_1::m_pData",
    ][::std::mem::offset_of!(DVariant__bindgen_ty_1, m_pData) - 0usize];
    [
        "Offset of field: DVariant__bindgen_ty_1::m_Vector",
    ][::std::mem::offset_of!(DVariant__bindgen_ty_1, m_Vector) - 0usize];
};
