// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FileWeaponInfo_t"][::std::mem::size_of::<FileWeaponInfo_t>() - 1832usize];
    [
        "Alignment of FileWeaponInfo_t",
    ][::std::mem::align_of::<FileWeaponInfo_t>() - 8usize];
    [
        "Offset of field: FileWeaponInfo_t::bParsedScript",
    ][::std::mem::offset_of!(FileWeaponInfo_t, bParsedScript) - 8usize];
    [
        "Offset of field: FileWeaponInfo_t::bLoadedHudElements",
    ][::std::mem::offset_of!(FileWeaponInfo_t, bLoadedHudElements) - 9usize];
    [
        "Offset of field: FileWeaponInfo_t::szClassName",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szClassName) - 10usize];
    [
        "Offset of field: FileWeaponInfo_t::szPrintName",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szPrintName) - 90usize];
    [
        "Offset of field: FileWeaponInfo_t::szViewModel",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szViewModel) - 170usize];
    [
        "Offset of field: FileWeaponInfo_t::szWorldModel",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szWorldModel) - 250usize];
    [
        "Offset of field: FileWeaponInfo_t::szAnimationPrefix",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szAnimationPrefix) - 330usize];
    [
        "Offset of field: FileWeaponInfo_t::iSlot",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iSlot) - 348usize];
    [
        "Offset of field: FileWeaponInfo_t::iPosition",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iPosition) - 352usize];
    [
        "Offset of field: FileWeaponInfo_t::iMaxClip1",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iMaxClip1) - 356usize];
    [
        "Offset of field: FileWeaponInfo_t::iMaxClip2",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iMaxClip2) - 360usize];
    [
        "Offset of field: FileWeaponInfo_t::iDefaultClip1",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iDefaultClip1) - 364usize];
    [
        "Offset of field: FileWeaponInfo_t::iDefaultClip2",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iDefaultClip2) - 368usize];
    [
        "Offset of field: FileWeaponInfo_t::iWeight",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iWeight) - 372usize];
    [
        "Offset of field: FileWeaponInfo_t::iRumbleEffect",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iRumbleEffect) - 376usize];
    [
        "Offset of field: FileWeaponInfo_t::bAutoSwitchTo",
    ][::std::mem::offset_of!(FileWeaponInfo_t, bAutoSwitchTo) - 380usize];
    [
        "Offset of field: FileWeaponInfo_t::bAutoSwitchFrom",
    ][::std::mem::offset_of!(FileWeaponInfo_t, bAutoSwitchFrom) - 381usize];
    [
        "Offset of field: FileWeaponInfo_t::iFlags",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iFlags) - 384usize];
    [
        "Offset of field: FileWeaponInfo_t::szAmmo1",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szAmmo1) - 388usize];
    [
        "Offset of field: FileWeaponInfo_t::szAmmo2",
    ][::std::mem::offset_of!(FileWeaponInfo_t, szAmmo2) - 420usize];
    [
        "Offset of field: FileWeaponInfo_t::aShootSounds",
    ][::std::mem::offset_of!(FileWeaponInfo_t, aShootSounds) - 452usize];
    [
        "Offset of field: FileWeaponInfo_t::iAmmoType",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iAmmoType) - 1732usize];
    [
        "Offset of field: FileWeaponInfo_t::iAmmo2Type",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iAmmo2Type) - 1736usize];
    [
        "Offset of field: FileWeaponInfo_t::m_bMeleeWeapon",
    ][::std::mem::offset_of!(FileWeaponInfo_t, m_bMeleeWeapon) - 1740usize];
    [
        "Offset of field: FileWeaponInfo_t::m_bBuiltRightHanded",
    ][::std::mem::offset_of!(FileWeaponInfo_t, m_bBuiltRightHanded) - 1741usize];
    [
        "Offset of field: FileWeaponInfo_t::m_bAllowFlipping",
    ][::std::mem::offset_of!(FileWeaponInfo_t, m_bAllowFlipping) - 1742usize];
    [
        "Offset of field: FileWeaponInfo_t::iSpriteCount",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iSpriteCount) - 1744usize];
    [
        "Offset of field: FileWeaponInfo_t::iconActive",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconActive) - 1752usize];
    [
        "Offset of field: FileWeaponInfo_t::iconInactive",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconInactive) - 1760usize];
    [
        "Offset of field: FileWeaponInfo_t::iconAmmo",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconAmmo) - 1768usize];
    [
        "Offset of field: FileWeaponInfo_t::iconAmmo2",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconAmmo2) - 1776usize];
    [
        "Offset of field: FileWeaponInfo_t::iconCrosshair",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconCrosshair) - 1784usize];
    [
        "Offset of field: FileWeaponInfo_t::iconAutoaim",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconAutoaim) - 1792usize];
    [
        "Offset of field: FileWeaponInfo_t::iconZoomedCrosshair",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconZoomedCrosshair) - 1800usize];
    [
        "Offset of field: FileWeaponInfo_t::iconZoomedAutoaim",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconZoomedAutoaim) - 1808usize];
    [
        "Offset of field: FileWeaponInfo_t::iconSmall",
    ][::std::mem::offset_of!(FileWeaponInfo_t, iconSmall) - 1816usize];
    [
        "Offset of field: FileWeaponInfo_t::bShowUsageHint",
    ][::std::mem::offset_of!(FileWeaponInfo_t, bShowUsageHint) - 1824usize];
};
