// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ICollideable {
    pub vtable_: *const ICollideable__bindgen_vtable,
}
#[repr(C)]
pub struct ICollideable__bindgen_vtable {
    pub ICollideable_GetEntityHandle: unsafe extern "C" fn(
        arg1: *mut ICollideable,
    ) -> *mut IHandleEntity,
    pub ICollideable_OBBMinsPreScaled: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const Vector,
    pub ICollideable_OBBMaxsPreScaled: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const Vector,
    pub ICollideable_OBBMins: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const Vector,
    pub ICollideable_OBBMaxs: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const Vector,
    pub ICollideable_WorldSpaceTriggerBounds: unsafe extern "C" fn(
        arg1: *const ICollideable,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub ICollideable_TestCollision: unsafe extern "C" fn(
        arg1: *mut ICollideable,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub ICollideable_TestHitboxes: unsafe extern "C" fn(
        arg1: *mut ICollideable,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub ICollideable_GetCollisionModelIndex: unsafe extern "C" fn(
        arg1: *mut ICollideable,
    ) -> ::std::os::raw::c_int,
    pub ICollideable_GetCollisionModel: unsafe extern "C" fn(
        arg1: *mut ICollideable,
    ) -> *const model_t,
    pub ICollideable_GetCollisionOrigin: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const Vector,
    pub ICollideable_GetCollisionAngles: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const QAngle,
    pub ICollideable_CollisionToWorldTransform: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const matrix3x4_t,
    pub ICollideable_GetSolid: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> SolidType_t,
    pub ICollideable_GetSolidFlags: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> ::std::os::raw::c_int,
    pub ICollideable_GetIClientUnknown: unsafe extern "C" fn(
        arg1: *mut ICollideable,
    ) -> *mut IClientUnknown,
    pub ICollideable_GetCollisionGroup: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> ::std::os::raw::c_int,
    pub ICollideable_WorldSpaceSurroundingBounds: unsafe extern "C" fn(
        arg1: *mut ICollideable,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub ICollideable_ShouldTouchTrigger: unsafe extern "C" fn(
        arg1: *const ICollideable,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub ICollideable_GetRootParentToWorldTransform: unsafe extern "C" fn(
        arg1: *const ICollideable,
    ) -> *const matrix3x4_t,
}
include!("layout_assertions.rs");
