// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IHasBuildPoints"][::std::mem::size_of::<IHasBuildPoints>() - 8usize];
    ["Alignment of IHasBuildPoints"][::std::mem::align_of::<IHasBuildPoints>() - 8usize];
};
