// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
#[derive(Debug)]
pub struct CBotCmd {
    pub vtable_: *const CBotCmd__bindgen_vtable,
    pub command_number: ::std::os::raw::c_int,
    pub tick_count: ::std::os::raw::c_int,
    pub viewangles: QAngle,
    pub forwardmove: f32,
    pub sidemove: f32,
    pub upmove: f32,
    pub buttons: ::std::os::raw::c_int,
    pub impulse: byte,
    pub weaponselect: ::std::os::raw::c_int,
    pub weaponsubtype: ::std::os::raw::c_int,
    pub random_seed: ::std::os::raw::c_int,
    pub mousedx: ::std::os::raw::c_short,
    pub mousedy: ::std::os::raw::c_short,
    pub hasbeenpredicted: bool,
}
#[repr(C)]
pub struct CBotCmd__bindgen_vtable {
    pub CBotCmd_complete_destructor: unsafe extern "C" fn(arg1: *mut CBotCmd),
    pub CBotCmd_deleting_destructor: unsafe extern "C" fn(arg1: *mut CBotCmd),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IBotController {
    pub vtable_: *const IBotController__bindgen_vtable,
}
#[repr(C)]
pub struct IBotController__bindgen_vtable {
    pub IBotController_SetAbsOrigin: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: *mut Vector,
    ),
    pub IBotController_SetAbsAngles: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: *mut QAngle,
    ),
    pub IBotController_SetLocalOrigin: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: *const Vector,
    ),
    pub IBotController_GetLocalOrigin: unsafe extern "C" fn(
        arg1: *mut IBotController,
    ) -> Vector,
    pub IBotController_SetLocalAngles: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: *const QAngle,
    ),
    pub IBotController_GetLocalAngles: unsafe extern "C" fn(
        arg1: *mut IBotController,
    ) -> QAngle,
    pub IBotController_RemoveAllItems: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: bool,
    ),
    pub IBotController_SetActiveWeapon: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub IBotController_IsEFlagSet: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub IBotController_RunPlayerMove: unsafe extern "C" fn(
        arg1: *mut IBotController,
        arg2: *mut CBotCmd,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IBotManager {
    pub vtable_: *const IBotManager__bindgen_vtable,
}
#[repr(C)]
pub struct IBotManager__bindgen_vtable {
    pub IBotManager_GetBotController: unsafe extern "C" fn(
        arg1: *mut IBotManager,
        arg2: *mut edict_t,
    ) -> *mut IBotController,
    pub IBotManager_CreateBot: unsafe extern "C" fn(
        arg1: *mut IBotManager,
        arg2: *const ::std::os::raw::c_char,
    ) -> *mut edict_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPlayerInfo {
    pub vtable_: *const IPlayerInfo__bindgen_vtable,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IPlayerInfoManager {
    pub vtable_: *const IPlayerInfoManager__bindgen_vtable,
}
#[repr(C)]
pub struct IPlayerInfoManager__bindgen_vtable {
    pub IPlayerInfoManager_GetPlayerInfo: unsafe extern "C" fn(
        arg1: *mut IPlayerInfoManager,
        arg2: *mut edict_t,
    ) -> *mut IPlayerInfo,
    pub IPlayerInfoManager_GetGlobalVars: unsafe extern "C" fn(
        arg1: *mut IPlayerInfoManager,
    ) -> *mut CGlobalVars,
}
#[repr(C)]
pub struct IPlayerInfo__bindgen_vtable {
    pub IPlayerInfo_GetName: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> *const ::std::os::raw::c_char,
    pub IPlayerInfo_GetUserID: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_GetNetworkIDString: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> *const ::std::os::raw::c_char,
    pub IPlayerInfo_GetTeamIndex: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_ChangeTeam: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
        arg2: ::std::os::raw::c_int,
    ),
    pub IPlayerInfo_GetFragCount: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_GetDeathCount: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_IsConnected: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_GetArmorValue: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_IsHLTV: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_IsPlayer: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_IsFakeClient: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_IsDead: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_IsInAVehicle: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_IsObserver: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
    pub IPlayerInfo_GetAbsOrigin: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> Vector,
    pub IPlayerInfo_GetAbsAngles: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> QAngle,
    pub IPlayerInfo_GetPlayerMins: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> Vector,
    pub IPlayerInfo_GetPlayerMaxs: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> Vector,
    pub IPlayerInfo_GetWeaponName: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> *const ::std::os::raw::c_char,
    pub IPlayerInfo_GetModelName: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> *const ::std::os::raw::c_char,
    pub IPlayerInfo_GetHealth: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_GetMaxHealth: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> ::std::os::raw::c_int,
    pub IPlayerInfo_GetLastUserCommand: unsafe extern "C" fn(
        arg1: *mut IPlayerInfo,
    ) -> CBotCmd,
    pub IPlayerInfo_IsReplay: unsafe extern "C" fn(arg1: *mut IPlayerInfo) -> bool,
}
include!("layout_assertions.rs");
