// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
#[repr(C)]
pub struct CBaseEntityOutput {
    pub m_Value: variant_t,
    pub m_ActionList: *mut CEventAction,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CEventAction {
    pub m_iTarget: string_t,
    pub m_iTargetInput: string_t,
    pub m_iParameter: string_t,
    pub m_flDelay: f32,
    pub m_nTimesToFire: ::std::os::raw::c_int,
    pub m_iIDStamp: ::std::os::raw::c_int,
    pub m_pNext: *mut CEventAction,
}
#[repr(C)]
pub struct COutputEvent {
    pub _base: CBaseEntityOutput,
}
include!("layout_assertions.rs");
