// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type EUniverse = ::std::os::raw::c_uint;
pub const EUniverse_k_EUniverseBeta: EUniverse = 2;
pub const EUniverse_k_EUniverseDev: EUniverse = 4;
pub const EUniverse_k_EUniverseInternal: EUniverse = 3;
pub const EUniverse_k_EUniverseInvalid: EUniverse = 0;
pub const EUniverse_k_EUniverseMax: EUniverse = 5;
pub const EUniverse_k_EUniversePublic: EUniverse = 1;
