[package]
name = "source_sdk_2013_raw"
version.workspace = true
edition = "2024"
rust-version = "1.98.1"

authors.workspace = true
license.workspace = true
repository.workspace = true

description = "Low-level module inspection utilities for Source engine integrations."
categories = ["api-bindings"]
keywords = ["gamedev", "source-engine", "valve"]

[dependencies]
thiserror.workspace = true

[features]
default = []
