// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type MaterialVarFlags_t = ::std::os::raw::c_uint;
pub type PreviewImageRetVal_t = ::std::os::raw::c_uint;
pub const MaterialVarFlags_t_MATERIAL_VAR_ADDITIVE: MaterialVarFlags_t = 128;
pub const MaterialVarFlags_t_MATERIAL_VAR_ALLOWALPHATOCOVERAGE: MaterialVarFlags_t = 536870912;
pub const MaterialVarFlags_t_MATERIAL_VAR_ALPHATEST: MaterialVarFlags_t = 256;
pub const MaterialVarFlags_t_MATERIAL_VAR_BASEALPHAENVMAPMASK: MaterialVarFlags_t = 1048576;
pub const MaterialVarFlags_t_MATERIAL_VAR_DEBUG: MaterialVarFlags_t = 1;
pub const MaterialVarFlags_t_MATERIAL_VAR_DECAL: MaterialVarFlags_t = 65536;
pub const MaterialVarFlags_t_MATERIAL_VAR_ENVMAPCAMERASPACE: MaterialVarFlags_t = 524288;
pub const MaterialVarFlags_t_MATERIAL_VAR_ENVMAPMODE: MaterialVarFlags_t = 33554432;
pub const MaterialVarFlags_t_MATERIAL_VAR_ENVMAPSPHERE: MaterialVarFlags_t = 131072;
pub const MaterialVarFlags_t_MATERIAL_VAR_FLAT: MaterialVarFlags_t = 4096;
pub const MaterialVarFlags_t_MATERIAL_VAR_HALFLAMBERT: MaterialVarFlags_t = 134217728;
pub const MaterialVarFlags_t_MATERIAL_VAR_IGNOREZ: MaterialVarFlags_t = 32768;
pub const MaterialVarFlags_t_MATERIAL_VAR_IGNORE_ALPHA_MODULATION: MaterialVarFlags_t = 1073741824;
pub const MaterialVarFlags_t_MATERIAL_VAR_MODEL: MaterialVarFlags_t = 2048;
pub const MaterialVarFlags_t_MATERIAL_VAR_MULTIPASS: MaterialVarFlags_t = 512;
pub const MaterialVarFlags_t_MATERIAL_VAR_NEEDS_SOFTWARE_SKINNING: MaterialVarFlags_t = 8388608;
pub const MaterialVarFlags_t_MATERIAL_VAR_NOALPHAMOD: MaterialVarFlags_t = 262144;
pub const MaterialVarFlags_t_MATERIAL_VAR_NOCULL: MaterialVarFlags_t = 8192;
pub const MaterialVarFlags_t_MATERIAL_VAR_NOFOG: MaterialVarFlags_t = 16384;
pub const MaterialVarFlags_t_MATERIAL_VAR_NORMALMAPALPHAENVMAPMASK: MaterialVarFlags_t = 4194304;
pub const MaterialVarFlags_t_MATERIAL_VAR_NO_DEBUG_OVERRIDE: MaterialVarFlags_t = 2;
pub const MaterialVarFlags_t_MATERIAL_VAR_NO_DRAW: MaterialVarFlags_t = 4;
pub const MaterialVarFlags_t_MATERIAL_VAR_OPAQUETEXTURE: MaterialVarFlags_t = 16777216;
pub const MaterialVarFlags_t_MATERIAL_VAR_SELFILLUM: MaterialVarFlags_t = 64;
pub const MaterialVarFlags_t_MATERIAL_VAR_SUPPRESS_DECALS: MaterialVarFlags_t = 67108864;
pub const MaterialVarFlags_t_MATERIAL_VAR_TRANSLUCENT: MaterialVarFlags_t = 2097152;
pub const MaterialVarFlags_t_MATERIAL_VAR_USE_IN_FILLRATE_MODE: MaterialVarFlags_t = 8;
pub const MaterialVarFlags_t_MATERIAL_VAR_VERTEXALPHA: MaterialVarFlags_t = 32;
pub const MaterialVarFlags_t_MATERIAL_VAR_VERTEXCOLOR: MaterialVarFlags_t = 16;
pub const MaterialVarFlags_t_MATERIAL_VAR_WIREFRAME: MaterialVarFlags_t = 268435456;
pub const MaterialVarFlags_t_MATERIAL_VAR_ZNEARER: MaterialVarFlags_t = 1024;
pub const PreviewImageRetVal_t_MATERIAL_NO_PREVIEW_IMAGE: PreviewImageRetVal_t = 2;
pub const PreviewImageRetVal_t_MATERIAL_PREVIEW_IMAGE_BAD: PreviewImageRetVal_t = 0;
pub const PreviewImageRetVal_t_MATERIAL_PREVIEW_IMAGE_OK: PreviewImageRetVal_t = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMaterial {
    pub vtable_: *const IMaterial__bindgen_vtable,
}
#[repr(C)]
#[derive(Debug)]
pub struct IMaterialVar {
    _unused: [u8; 0],
}
#[repr(C)]
pub struct IMaterial__bindgen_vtable {
    pub IMaterial_GetName: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> *const ::std::os::raw::c_char,
    pub IMaterial_GetTextureGroupName: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> *const ::std::os::raw::c_char,
    pub IMaterial_GetPreviewImageProperties: unsafe extern "C" fn(
        arg1: *const IMaterial,
        arg2: *mut ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_int,
        arg4: *mut ImageFormat,
        arg5: *mut bool,
    ) -> PreviewImageRetVal_t,
    pub IMaterial_GetPreviewImage: unsafe extern "C" fn(
        arg1: *const IMaterial,
        arg2: *mut ::std::os::raw::c_uchar,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ImageFormat,
    ) -> PreviewImageRetVal_t,
    pub IMaterial_GetMappingWidth: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_GetMappingHeight: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_GetNumAnimationFrames: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_InMaterialPage: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_GetMaterialOffset: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut f32,
    ),
    pub IMaterial_GetMaterialScale: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut f32,
    ),
    pub IMaterial_GetMaterialPage: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> *mut IMaterial,
    pub IMaterial_FindVar: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut bool,
        arg4: bool,
    ) -> *mut IMaterialVar,
    pub IMaterial_IncrementReferenceCount: unsafe extern "C" fn(arg1: *mut IMaterial),
    pub IMaterial_DecrementReferenceCount: unsafe extern "C" fn(arg1: *mut IMaterial),
    pub IMaterial_GetEnumerationID: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_GetLowResColorSample: unsafe extern "C" fn(
        arg1: *const IMaterial,
        arg2: f32,
        arg3: f32,
        arg4: *mut f32,
    ),
    pub IMaterial_RecomputeStateSnapshots: unsafe extern "C" fn(arg1: *mut IMaterial),
    pub IMaterial_IsTranslucent: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_IsAlphaTested: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_IsVertexLit: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_GetVertexFormat: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> VertexFormat_t,
    pub IMaterial_HasProxy: unsafe extern "C" fn(arg1: *const IMaterial) -> bool,
    pub IMaterial_UsesEnvCubemap: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_NeedsTangentSpace: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_NeedsPowerOfTwoFrameBufferTexture: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: bool,
    ) -> bool,
    pub IMaterial_NeedsFullFrameBufferTexture: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: bool,
    ) -> bool,
    pub IMaterial_NeedsSoftwareSkinning: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> bool,
    pub IMaterial_AlphaModulate: unsafe extern "C" fn(arg1: *mut IMaterial, arg2: f32),
    pub IMaterial_ColorModulate: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: f32,
        arg3: f32,
        arg4: f32,
    ),
    pub IMaterial_SetMaterialVarFlag: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: MaterialVarFlags_t,
        arg3: bool,
    ),
    pub IMaterial_GetMaterialVarFlag: unsafe extern "C" fn(
        arg1: *const IMaterial,
        arg2: MaterialVarFlags_t,
    ) -> bool,
    pub IMaterial_GetReflectivity: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut Vector,
    ),
    pub IMaterial_GetPropertyFlag: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: MaterialPropertyTypes_t,
    ) -> bool,
    pub IMaterial_IsTwoSided: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_SetShader: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub IMaterial_GetNumPasses: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_GetTextureMemoryBytes: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_Refresh: unsafe extern "C" fn(arg1: *mut IMaterial),
    pub IMaterial_NeedsLightmapBlendAlpha: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> bool,
    pub IMaterial_NeedsSoftwareLighting: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> bool,
    pub IMaterial_ShaderParamCount: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> ::std::os::raw::c_int,
    pub IMaterial_GetShaderParams: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> *mut *mut IMaterialVar,
    pub IMaterial_IsErrorMaterial: unsafe extern "C" fn(arg1: *const IMaterial) -> bool,
    pub IMaterial_SetUseFixedFunctionBakedLighting: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: bool,
    ),
    pub IMaterial_GetAlphaModulation: unsafe extern "C" fn(arg1: *mut IMaterial) -> f32,
    pub IMaterial_GetColorModulation: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut f32,
        arg3: *mut f32,
        arg4: *mut f32,
    ),
    pub IMaterial_GetMorphFormat: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> MorphFormat_t,
    pub IMaterial_FindVarFast: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_uint,
    ) -> *mut IMaterialVar,
    pub IMaterial_SetShaderAndParams: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut KeyValues,
    ),
    pub IMaterial_GetShaderName: unsafe extern "C" fn(
        arg1: *const IMaterial,
    ) -> *const ::std::os::raw::c_char,
    pub IMaterial_DeleteIfUnreferenced: unsafe extern "C" fn(arg1: *mut IMaterial),
    pub IMaterial_IsSpriteCard: unsafe extern "C" fn(arg1: *mut IMaterial) -> bool,
    pub IMaterial_CallBindProxy: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub IMaterial_CheckProxyReplacement: unsafe extern "C" fn(
        arg1: *mut IMaterial,
        arg2: *mut ::std::os::raw::c_void,
    ) -> *mut IMaterial,
    pub IMaterial_RefreshPreservingMaterialVars: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ),
    pub IMaterial_WasReloadedFromWhitelist: unsafe extern "C" fn(
        arg1: *mut IMaterial,
    ) -> bool,
    pub IMaterial_IsPrecached: unsafe extern "C" fn(arg1: *const IMaterial) -> bool,
}
include!("layout_assertions.rs");
