// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Vector2D"][::std::mem::size_of::<Vector2D>() - 8usize];
    ["Alignment of Vector2D"][::std::mem::align_of::<Vector2D>() - 4usize];
    ["Offset of field: Vector2D::x"][::std::mem::offset_of!(Vector2D, x) - 0usize];
    ["Offset of field: Vector2D::y"][::std::mem::offset_of!(Vector2D, y) - 4usize];
};
