// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type CBaseMultiplayerPlayer__bindgen_ty_1 = ::std::os::raw::c_uint;
pub type CBaseMultiplayerPlayer_BaseClass = CAI_ExpresserHost<CBasePlayer>;
pub const CBaseMultiplayerPlayer_CHAT_IGNORE_ALL: CBaseMultiplayerPlayer__bindgen_ty_1 = 1;
pub const CBaseMultiplayerPlayer_CHAT_IGNORE_NONE: CBaseMultiplayerPlayer__bindgen_ty_1 = 0;
pub const CBaseMultiplayerPlayer_CHAT_IGNORE_TEAM: CBaseMultiplayerPlayer__bindgen_ty_1 = 2;
#[repr(C)]
#[derive(Debug)]
pub struct CBaseMultiplayerPlayer {
    pub _base: CAI_ExpresserHost<CBasePlayer>,
    pub m_iIgnoreGlobalChat: ::std::os::raw::c_int,
    pub m_flAreaCaptureScoreAccumulator: f32,
    pub m_flCapPointScoreRate: f32,
    pub m_iCurrentConcept: ::std::os::raw::c_int,
    pub m_pExpresser: *mut CMultiplayer_Expresser,
    pub m_flConnectionTime: f32,
    pub m_flLastForcedChangeTeamTime: f32,
    pub m_iBalanceScore: ::std::os::raw::c_int,
    pub m_pAchievementKV: *mut KeyValues,
    pub m_RateLimitLastCommandTimes: __BindgenOpaqueArray8<[u8; 48usize]>,
}
#[repr(C)]
pub struct CBaseMultiplayerPlayer__bindgen_vtable {
    pub CBaseMultiplayerPlayer_complete_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_deleting_destructor: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SetRefEHandle: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CBaseHandle,
    ),
    pub CBaseMultiplayerPlayer_GetRefEHandle: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> *const CBaseHandle,
    pub CBaseMultiplayerPlayer_GetCollideable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut ICollideable,
    pub CBaseMultiplayerPlayer_GetNetworkable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut IServerNetworkable,
    pub CBaseMultiplayerPlayer_GetBaseEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_GetModelIndex: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_GetModelName: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> string_t,
    pub CBaseMultiplayerPlayer_SetModelIndex: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_GetServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut ServerClass,
    pub CBaseMultiplayerPlayer_YouForgotToImplementOrDeclareServerClass: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_GetDataDescMap: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut datamap_t,
    pub CBaseMultiplayerPlayer_GetScriptDesc: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut ScriptClassDesc_t,
    pub CBaseMultiplayerPlayer_SetModelIndexOverride: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_TestCollision: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CBaseMultiplayerPlayer_TestHitboxes: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Ray_t,
        arg3: ::std::os::raw::c_uint,
        arg4: *mut trace_t,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ComputeWorldSpaceSurroundingBox: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut Vector,
        arg3: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_ShouldCollide: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_SetOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_SetScriptOwnerEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: HSCRIPT,
    ),
    pub CBaseMultiplayerPlayer_ShouldTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CCheckTransmitInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_UpdateTransmitState: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_SetTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CCheckTransmitInfo,
        arg3: bool,
    ),
    pub CBaseMultiplayerPlayer_GetTracerType: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseMultiplayerPlayer_Spawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Precache: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SetModel: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_OnNewModel: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CStudioHdr,
    pub CBaseMultiplayerPlayer_PostConstructor: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_PostClientActive: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ParseMapData: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CEntityMapData,
    ),
    pub CBaseMultiplayerPlayer_KeyValue: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const ::std::os::raw::c_char,
    ) -> bool,
    pub CBaseMultiplayerPlayer_KeyValue1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: f32,
    ) -> bool,
    pub CBaseMultiplayerPlayer_KeyValue2: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetKeyValue: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_char,
        arg4: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Activate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SetParent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_ObjectCaps: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    /// C++ takes `::variant_t` by value. `arg5` points to a temporary copy the caller makes; the callee may modify it, and the caller destroys it after the call.
    pub CBaseMultiplayerPlayer_AcceptInput: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut CBaseEntity,
        arg4: *mut CBaseEntity,
        arg5: *mut variant_t,
        arg6: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetInputDispatchEffectPosition: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut Vector,
        arg4: *mut QAngle,
    ),
    pub CBaseMultiplayerPlayer_DrawDebugGeometryOverlays: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_DrawDebugTextOverlays: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_Save: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ISave,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_Restore: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IRestore,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_ShouldSavePhysics: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_OnSave: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IEntitySaveUtils,
    ),
    pub CBaseMultiplayerPlayer_OnRestore: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_RequiredEdictIndex: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_MoveDone: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Think: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_nNextThinkTick: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_nNextThinkTick1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_GetBaseAnimating: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseAnimating,
    pub CBaseMultiplayerPlayer_GetResponseSystem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut IResponseSystem,
    pub CBaseMultiplayerPlayer_DispatchResponse: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_Classify: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Class_T,
    pub CBaseMultiplayerPlayer_DeathNotice: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_ShouldAttractAutoAim: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetAutoAimRadius: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetAutoAimCenter: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetBeamTraceFilter: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut ITraceFilter,
    pub CBaseMultiplayerPlayer_PassesDamageFilter: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CBaseMultiplayerPlayer_TraceAttack: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
        arg3: *const Vector,
        arg4: *mut trace_t,
        arg5: *mut CDmgAccumulator,
    ),
    pub CBaseMultiplayerPlayer_CanBeHitByMeleeAttack: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_OnTakeDamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_AdjustDamageDirection: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
        arg3: *mut Vector,
        arg4: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_TakeHealth: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_IsAlive: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Event_Killed: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_Event_KilledOther: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *const CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_BloodColor: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_IsTriggered: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsNPC: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsNextBot: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_MyCombatCharacterPointer: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseCombatCharacter,
    pub CBaseMultiplayerPlayer_MyNextBotPointer: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut INextBot,
    pub CBaseMultiplayerPlayer_GetDelay: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_IsMoving: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_DamageDecal: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseMultiplayerPlayer_DecalTrace: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut trace_t,
        arg3: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_ImpactTrace: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
        arg4: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_OnControls: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_HasTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: string_t,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsPlayer: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsNetClient: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsTemplate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsBaseObject: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsBaseTrain: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsCombatItem: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsProjectileCollisionTarget: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsFuncLOD: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsBaseProjectile: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsBaseCombatWeapon: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsWearable: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_MyCombatWeaponPointer: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseCombatWeapon,
    pub CBaseMultiplayerPlayer_GetServerVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut IServerVehicle,
    pub CBaseMultiplayerPlayer_IsViewable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ChangeTeam: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_OnEntityEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: EntityEvent_t,
        arg3: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_CanStandOn: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanStandOn1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut edict_t,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetEnemy: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_GetEnemy1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_Use: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *mut CBaseEntity,
        arg4: USE_TYPE,
        arg5: f32,
    ),
    pub CBaseMultiplayerPlayer_StartTouch: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_Touch: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_EndTouch: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_StartBlocked: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_Blocked: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_EndBlocked: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_PhysicsSimulate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_UpdateOnRemove: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_StopLoopingSounds: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SUB_AllowedToFade: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Teleport: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const QAngle,
        arg4: *const Vector,
    ),
    pub CBaseMultiplayerPlayer_NotifySystemEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: notify_system_event_t,
        arg4: *const notify_system_event_params_t,
    ),
    pub CBaseMultiplayerPlayer_MakeTracer: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const trace_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_GetTracerAttachment: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_FireBullets: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const FireBulletsInfo_t,
    ),
    pub CBaseMultiplayerPlayer_DoImpactEffect: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut trace_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_ModifyFireBulletsDamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_Respawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_IsLockedByMaster: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetMaxHealth: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_ModifyOrAppendCriteria: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut AI_CriteriaSet,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_iMaxHealth: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_iMaxHealth1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_iHealth: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_iHealth1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_lifeState: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_lifeState1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_takedamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_takedamage1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_RunVScripts: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetDamageType: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_GetDamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_SetDamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ),
    pub CBaseMultiplayerPlayer_EyePosition: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_EyeAngles: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *const QAngle,
    pub CBaseMultiplayerPlayer_LocalEyeAngles: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *const QAngle,
    pub CBaseMultiplayerPlayer_EarPosition: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_BodyTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: bool,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_HeadTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetVectors: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_GetViewOffset: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> *const Vector,
    pub CBaseMultiplayerPlayer_SetViewOffset: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ),
    pub CBaseMultiplayerPlayer_GetSmoothedVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut Vector,
        arg3: *mut AngularImpulse,
    ),
    pub CBaseMultiplayerPlayer_FVisible: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_FVisible1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: ::std::os::raw::c_int,
        arg4: *mut *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanBeSeenBy: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CAI_BaseNPC,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetAttackDamageScale: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetReceivedDamageScale: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetGroundVelocityToApply: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_PhysicsSplash: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: f32,
        arg5: f32,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Splash: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_WorldSpaceCenter: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> *const Vector,
    pub CBaseMultiplayerPlayer_GetSoundEmissionOrigin: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_ModifyEmitSoundParams: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut EmitSound_t,
    ),
    pub CBaseMultiplayerPlayer_IsDeflectable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Deflected: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_CreateVPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ForceVPhysicsCollide: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_VPhysicsDestroyObject: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_VPhysicsUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IPhysicsObject,
    ),
    pub CBaseMultiplayerPlayer_VPhysicsTakeDamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_VPhysicsShadowCollision: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CBaseMultiplayerPlayer_VPhysicsShadowUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IPhysicsObject,
    ),
    pub CBaseMultiplayerPlayer_VPhysicsCollision: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *mut gamevcollisionevent_t,
    ),
    pub CBaseMultiplayerPlayer_VPhysicsFriction: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IPhysicsObject,
        arg3: f32,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_UpdatePhysicsShadowToCurrentPosition: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ),
    pub CBaseMultiplayerPlayer_VPhysicsGetObjectList: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut *mut IPhysicsObject,
        arg3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_VPhysicsIsFlesh: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_HasPhysicsAttacker: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ) -> *mut CBasePlayer,
    pub CBaseMultiplayerPlayer_PhysicsSolidMaskForEntity: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_uint,
    pub CBaseMultiplayerPlayer_ResolveFlyCollisionCustom: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut trace_t,
        arg3: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_PerformCustomPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut Vector,
        arg3: *mut Vector,
        arg4: *mut QAngle,
        arg5: *mut QAngle,
    ),
    pub CBaseMultiplayerPlayer_GetStepOrigin: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetStepAngles: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> QAngle,
    pub CBaseMultiplayerPlayer_ShouldDrawWaterImpacts: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_fFlags: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_fFlags1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_nWaterLevel: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_nWaterLevel1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_hGroundEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_hGroundEntity1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_vecBaseVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_vecBaseVelocity1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_flFriction: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_flFriction1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_vecVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_vecVelocity1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_vecViewOffset: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_vecViewOffset1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_ShouldBlockNav: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ShouldForceTransmitsForTeam: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsTruceValidForEnt: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetDefaultItemChargeMeterValue: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_BCanCallVote: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetIdealSpeed: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetIdealAccel: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_StudioFrameAdvance: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SetSequence: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_IsActivityFinished: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetSequenceGroundSpeed: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CStudioHdr,
        arg3: ::std::os::raw::c_int,
    ) -> f32,
    pub CBaseMultiplayerPlayer_ClampRagdollForce: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_BecomeRagdollOnClient: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanBecomeRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetSkeleton: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CStudioHdr,
        arg3: *mut Vector,
        arg4: *mut Quaternion,
        arg5: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_GetBoneTransform: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *mut matrix3x4_t,
    ),
    pub CBaseMultiplayerPlayer_SetupBones: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut matrix3x4_t,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_CalculateIKLocks: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ),
    pub CBaseMultiplayerPlayer_DispatchAnimEvents: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseAnimating,
    ),
    pub CBaseMultiplayerPlayer_HandleAnimEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut animevent_t,
    ),
    pub CBaseMultiplayerPlayer_PopulatePoseParameters: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetAttachment: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *mut matrix3x4_t,
    ) -> bool,
    pub CBaseMultiplayerPlayer_InitBoneControllers: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetGroundSpeedVelocity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_RefreshCollisionBounds: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Ignite: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: bool,
        arg4: f32,
        arg5: bool,
    ),
    pub CBaseMultiplayerPlayer_IgniteLifetime: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ),
    pub CBaseMultiplayerPlayer_IgniteNumHitboxFires: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_IgniteHitboxFireScale: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ),
    pub CBaseMultiplayerPlayer_Extinguish: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SetLightingOriginRelative: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_SetLightingOrigin: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_SetViewtarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ),
    pub CBaseMultiplayerPlayer_StartSceneEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CSceneEventInfo,
        arg3: *mut CChoreoScene,
        arg4: *mut CChoreoEvent,
        arg5: *mut CChoreoActor,
        arg6: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ProcessSceneEvents: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ProcessSceneEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CSceneEventInfo,
        arg3: *mut CChoreoScene,
        arg4: *mut CChoreoEvent,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ClearSceneEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CSceneEventInfo,
        arg3: bool,
        arg4: bool,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CheckSceneEventCompletion: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CSceneEventInfo,
        arg3: f32,
        arg4: *mut CChoreoScene,
        arg5: *mut CChoreoEvent,
    ) -> bool,
    pub CBaseMultiplayerPlayer_PlayScene: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: f32,
        arg4: *mut AI_Response,
        arg5: *mut IRecipientFilter,
    ) -> f32,
    pub CBaseMultiplayerPlayer_PlayAutoGeneratedSoundScene: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetSpecialDSP: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_GetPhysicsImpactDamageTable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *const impactdamagetable_t,
    pub CBaseMultiplayerPlayer_FInViewCone: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_FInViewCone1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_FInAimCone: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_FInAimCone1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ShouldShootMissTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatCharacter,
    ) -> bool,
    pub CBaseMultiplayerPlayer_FindMissTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_HandleInteraction: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *mut ::std::os::raw::c_void,
        arg4: *mut CBaseCombatCharacter,
    ) -> bool,
    pub CBaseMultiplayerPlayer_BodyAngles: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> QAngle,
    pub CBaseMultiplayerPlayer_BodyDirection2D: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_BodyDirection3D: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_HeadDirection2D: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_HeadDirection3D: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_EyeDirection2D: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_EyeDirection3D: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_IsHiddenByFog: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsHiddenByFog1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsHiddenByFog2: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: f32,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetFogObscuredRatio: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetFogObscuredRatio1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> f32,
    pub CBaseMultiplayerPlayer_GetFogObscuredRatio2: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: f32,
    ) -> f32,
    pub CBaseMultiplayerPlayer_IsLookingTowards: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const CBaseEntity,
        arg3: f32,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsLookingTowards1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: f32,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsInFieldOfView: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsInFieldOfView1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsLineOfSightClear: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: CBaseCombatCharacter_LineOfSightCheckType,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsLineOfSightClear1: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: CBaseCombatCharacter_LineOfSightCheckType,
        arg4: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GiveAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
        arg4: bool,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_RemoveAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_RemoveAmmo1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_GetAmmoCount: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_NPC_TranslateActivity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: Activity,
    ) -> Activity,
    pub CBaseMultiplayerPlayer_Weapon_TranslateActivity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: Activity,
        arg3: *mut bool,
    ) -> Activity,
    pub CBaseMultiplayerPlayer_Weapon_FrameUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Weapon_HandleAnimEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut animevent_t,
    ),
    pub CBaseMultiplayerPlayer_Weapon_CanUse: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Weapon_Equip: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ),
    pub CBaseMultiplayerPlayer_Weapon_EquipAmmoOnly: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Weapon_Drop: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
        arg3: *const Vector,
        arg4: *const Vector,
    ),
    pub CBaseMultiplayerPlayer_Weapon_Switch: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Weapon_ShootPosition: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_Weapon_CanSwitchTo: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Weapon_SlotOccupied: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Weapon_GetSlot: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> *mut CBaseCombatWeapon,
    pub CBaseMultiplayerPlayer_AddPlayerItem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_RemovePlayerItem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanBecomeServerRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_OnTakeDamage_Alive: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_OnTakeDamage_Dying: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_OnTakeDamage_Dead: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_GetAliveDuration: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_OnFriendDamaged: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatCharacter,
        arg3: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_NotifyFriendsOfDamage: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_HasEverBeenInjured: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetTimeSinceLastInjury: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> f32,
    pub CBaseMultiplayerPlayer_OnPlayerKilledOther: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *const CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_GetDeathActivity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> Activity,
    pub CBaseMultiplayerPlayer_CorpseGib: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CorpseFade: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_HasHumanGibs: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_HasAlienGibs: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ShouldGib: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CBaseMultiplayerPlayer_OnKilledNPC: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatCharacter,
    ),
    pub CBaseMultiplayerPlayer_Event_Gibbed: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Event_Dying: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_Event_Dying1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_BecomeRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
        arg3: *const Vector,
    ) -> bool,
    pub CBaseMultiplayerPlayer_FixupBurningServerRagdoll: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_BecomeRagdollBoogie: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *const Vector,
        arg4: f32,
        arg5: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CheckTraceHullAttack: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: *const Vector,
        arg4: *const Vector,
        arg5: ::std::os::raw::c_int,
        arg6: ::std::os::raw::c_int,
        arg7: f32,
        arg8: bool,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_CheckTraceHullAttack1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const Vector,
        arg4: *const Vector,
        arg5: *const Vector,
        arg6: ::std::os::raw::c_int,
        arg7: ::std::os::raw::c_int,
        arg8: f32,
        arg9: bool,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_PushawayTouch: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_IRelationType: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> Disposition_t,
    pub CBaseMultiplayerPlayer_IRelationPriority: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_IsInAVehicle: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut IServerVehicle,
    pub CBaseMultiplayerPlayer_GetVehicleEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_ExitVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_RemoveAllWeapons: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_CalcWeaponProficiency: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> WeaponProficiency_t,
    pub CBaseMultiplayerPlayer_GetAttackSpread: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
        arg3: *mut CBaseEntity,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetSpreadBias: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
        arg3: *mut CBaseEntity,
    ) -> f32,
    pub CBaseMultiplayerPlayer_DoMuzzleFlash: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_AddEntityRelationship: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: Disposition_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_RemoveEntityRelationship: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_AddClassRelationship: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: Class_T,
        arg3: Disposition_t,
        arg4: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_OnChangeActiveWeapon: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
        arg3: *mut CBaseCombatWeapon,
    ),
    pub CBaseMultiplayerPlayer_GetLastKnownArea: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> *mut CNavArea,
    pub CBaseMultiplayerPlayer_IsAreaTraversable: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const CNavArea,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ClearLastKnownArea: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_UpdateLastKnownArea: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_OnNavAreaChanged: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CNavArea,
        arg3: *mut CNavArea,
    ),
    pub CBaseMultiplayerPlayer_OnNavAreaRemoved: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CNavArea,
    ),
    pub CBaseMultiplayerPlayer_OnPursuedBy: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut INextBot,
    ),
    pub CBaseMultiplayerPlayer_GetBossType: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> HalloweenBossType,
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_iAmmo: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_iAmmo1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_CreateViewModel: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_SetupVisibility: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *mut ::std::os::raw::c_uchar,
        arg4: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_WantsLagCompensationOnEntity: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: *const CBasePlayer,
        arg3: *const CUserCmd,
        arg4: *const u8,
    ) -> bool,
    pub CBaseMultiplayerPlayer_SharedSpawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ForceRespawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_InitialSpawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_InitHUD: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ShowViewPortPanel: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: bool,
        arg4: *mut KeyValues,
    ),
    pub CBaseMultiplayerPlayer_PlayerDeathThink: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Jump: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Duck: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_PreThink: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_PostThink: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_DamageEffect: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_OnDamagedByExplosion: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_ShouldFadeOnDeath: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsFakeClient: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetPlayerMins: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetPlayerMaxs: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_CalcRoll: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const QAngle,
        arg3: *const Vector,
        arg4: f32,
        arg5: f32,
    ) -> f32,
    pub CBaseMultiplayerPlayer_PackDeadPlayerItems: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_RemoveAllItems: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ),
    pub CBaseMultiplayerPlayer_Weapon_SetLast: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ),
    pub CBaseMultiplayerPlayer_Weapon_ShouldSetLast: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
        arg3: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_Weapon_ShouldSelectItem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_OnMyWeaponFired: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ),
    pub CBaseMultiplayerPlayer_GetTimeSinceWeaponFired: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_IsFiringWeapon: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_UpdateClientData: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ExitLadder: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetLadderSurface: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
    ) -> *mut surfacedata_t,
    pub CBaseMultiplayerPlayer_SetFlashlightEnabled: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ),
    pub CBaseMultiplayerPlayer_FlashlightIsOn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_FlashlightTurnOn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_FlashlightTurnOff: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_IsIlluminatedByFlashlight: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: *mut f32,
    ) -> bool,
    pub CBaseMultiplayerPlayer_UpdateStepSound: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut surfacedata_t,
        arg3: *const Vector,
        arg4: *const Vector,
    ),
    pub CBaseMultiplayerPlayer_PlayStepSound: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut Vector,
        arg3: *mut surfacedata_t,
        arg4: f32,
        arg5: bool,
    ),
    pub CBaseMultiplayerPlayer_GetOverrideStepSound: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseMultiplayerPlayer_GetStepSoundVelocities: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut f32,
        arg3: *mut f32,
    ),
    pub CBaseMultiplayerPlayer_SetStepSoundTime: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: stepsoundtimes_t,
        arg3: bool,
    ),
    pub CBaseMultiplayerPlayer_DeathSound: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CTakeDamageInfo,
    ),
    pub CBaseMultiplayerPlayer_GetSceneSoundToken: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *const ::std::os::raw::c_char,
    pub CBaseMultiplayerPlayer_OnEmitFootstepSound: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CSoundParameters,
        arg3: *const Vector,
        arg4: f32,
    ),
    pub CBaseMultiplayerPlayer_SetAnimation: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: PLAYER_ANIM,
    ),
    pub CBaseMultiplayerPlayer_ImpulseCommands: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_CheatImpulseCommands: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_ClientCommand: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const CCommand,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetTeamVoteController: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CVoteController,
    pub CBaseMultiplayerPlayer_StartObserverMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_StopObserverMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ModeWantsSpectatorGUI: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_SetObserverMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetObserverMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_SetObserverTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ObserverUse: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ),
    pub CBaseMultiplayerPlayer_GetObserverTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_FindNextObserverTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_GetNextObserverSearchStartPoint: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_IsValidObserverTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CheckObserverSettings: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_JumptoPosition: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const QAngle,
    ),
    pub CBaseMultiplayerPlayer_ForceObserverMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_ResetObserverMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ValidateCurrentObserverTarget: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_AttemptToExitFreezeCam: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_StartReplayMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: f32,
        arg4: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_StopReplayMode: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetDelayTicks: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_GetReplayEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_CreateCorpse: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_EntSelectSpawnPoint: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_GetInVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IServerVehicle,
        arg3: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_LeaveVehicle: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const QAngle,
    ),
    pub CBaseMultiplayerPlayer_OnVehicleStart: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_OnVehicleEnd: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut Vector,
    ),
    pub CBaseMultiplayerPlayer_BumpWeapon: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseCombatWeapon,
    ) -> bool,
    pub CBaseMultiplayerPlayer_SelectLastItem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SelectItem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_ItemPostFrame: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GiveNamedItem: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_CheckTrainUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_SetPlayerUnderwater: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ),
    pub CBaseMultiplayerPlayer_CanBreatheUnderwater: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_PlayerUse: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_PlayUseDenySound: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_FindUseEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CBaseEntity,
    pub CBaseMultiplayerPlayer_IsUseableEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: ::std::os::raw::c_uint,
    ) -> bool,
    pub CBaseMultiplayerPlayer_PickupObject: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
        arg3: bool,
    ),
    pub CBaseMultiplayerPlayer_ForceDropOfCarriedPhysObjects: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBaseEntity,
    ),
    pub CBaseMultiplayerPlayer_GetHeldObjectMass: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut IPhysicsObject,
    ) -> f32,
    pub CBaseMultiplayerPlayer_UpdateGeigerCounter: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetAutoaimVector: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetAutoaimVector1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: f32,
    ) -> Vector,
    pub CBaseMultiplayerPlayer_GetAutoaimVector2: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut autoaim_params_t,
    ),
    pub CBaseMultiplayerPlayer_ShouldAutoaim: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ForceClientDllUpdate: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ProcessUsercmds: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CUserCmd,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
        arg6: bool,
    ),
    pub CBaseMultiplayerPlayer_PlayerRunCommand: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CUserCmd,
        arg3: *mut IMoveHelper,
    ),
    pub CBaseMultiplayerPlayer_ChangeTeam1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: bool,
        arg4: bool,
        arg5: bool,
    ),
    pub CBaseMultiplayerPlayer_CanHearAndReadChatFrom: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CBasePlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanSpeak: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ModifyOrAppendPlayerCriteria: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut AI_CriteriaSet,
    ),
    pub CBaseMultiplayerPlayer_CheckChatText: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_char,
        arg3: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_CreateRagdollEntity: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ShouldAnnounceAchievement: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_EquipWearable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CEconWearable,
    ),
    pub CBaseMultiplayerPlayer_RemoveWearable: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut CEconWearable,
    ),
    pub CBaseMultiplayerPlayer_IsFollowingPhysics: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_InitVCollision: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: *const Vector,
    ),
    pub CBaseMultiplayerPlayer_UpdatePhysicsShadowToCurrentPosition1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_Hints: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CHintSystem,
    pub CBaseMultiplayerPlayer_IsReadyToPlay: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsReadyToSpawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ShouldGainInstantSpawn: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ResetPerRoundStats: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_ResetScores: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_EquipSuit: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ),
    pub CBaseMultiplayerPlayer_RemoveSuit: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_GetPlayerMaxSpeed: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> f32,
    pub CBaseMultiplayerPlayer_CommitSuicide: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
        arg3: bool,
    ),
    pub CBaseMultiplayerPlayer_CommitSuicide1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const Vector,
        arg3: bool,
        arg4: bool,
    ),
    pub CBaseMultiplayerPlayer_IsBot: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_IsBotOfType: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetBotType: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_CanPlayerTalk: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_GetExpresser: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CAI_Expresser,
    pub CBaseMultiplayerPlayer_Internal_HandleMapEvent: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut inputdata_t,
    ),
    pub CBaseMultiplayerPlayer_SpawnArmorValue: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_ArmorValue: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NetworkStateChanged_m_ArmorValue1: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *mut ::std::os::raw::c_void,
    ),
    pub CBaseMultiplayerPlayer_HasHaptics: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_SetHaptics: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: bool,
    ),
    pub CBaseMultiplayerPlayer_PlayerSolidMask: unsafe extern "C" fn(
        arg1: *const CBaseMultiplayerPlayer,
        arg2: bool,
    ) -> ::std::os::raw::c_uint,
    pub CBaseMultiplayerPlayer_BHaveChatSuspensionInCurrentMatch: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_OnVoiceTransmit: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ),
    pub CBaseMultiplayerPlayer_NoteSpeaking: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: f32,
        arg3: f32,
    ),
    pub CBaseMultiplayerPlayer_Speak: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: AIConcept_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut ::std::os::raw::c_char,
        arg5: usize,
        arg6: *mut IRecipientFilter,
    ) -> bool,
    pub CBaseMultiplayerPlayer_PostSpeakDispatchResponse: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: AIConcept_t,
        arg3: *mut AI_Response,
    ),
    pub CBaseMultiplayerPlayer_SpeakIfAllowed: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: AIConcept_t,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut ::std::os::raw::c_char,
        arg5: usize,
        arg6: *mut IRecipientFilter,
    ) -> bool,
    pub CBaseMultiplayerPlayer_SpeakConceptIfAllowed: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
        arg3: *const ::std::os::raw::c_char,
        arg4: *mut ::std::os::raw::c_char,
        arg5: usize,
        arg6: *mut IRecipientFilter,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanBeAutobalanced: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_CanSpeakVoiceCommand: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_ShouldShowVoiceSubtitleToEnemy: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> bool,
    pub CBaseMultiplayerPlayer_NoteSpokeVoiceCommand: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: *const ::std::os::raw::c_char,
    ),
    pub CBaseMultiplayerPlayer_OnAchievementEarned: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
        arg2: ::std::os::raw::c_int,
    ),
    pub CBaseMultiplayerPlayer_GetMultiplayerExpresser: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CMultiplayer_Expresser,
    pub CBaseMultiplayerPlayer_CalculateTeamBalanceScore: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> ::std::os::raw::c_int,
    pub CBaseMultiplayerPlayer_CreateExpresser: unsafe extern "C" fn(
        arg1: *mut CBaseMultiplayerPlayer,
    ) -> *mut CAI_Expresser,
}
include!("layout_assertions.rs");
