// @generated by `source_sdk_2013_bindgen`. DO NOT EDIT.
// Regenerate with the `source_sdk_2013_bindgen/generate_bindings` Cargo feature.

#![allow(
    clippy::all,
    ambiguous_glob_reexports,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    unsafe_op_in_unsafe_fn,
    unused_imports,
    unused_qualifications
)]
#[allow(unused_imports)]
use super::super::super::super::__bindgen_prelude::*;
pub type notify_system_event_t = ::std::os::raw::c_int;
pub const notify_system_event_t_NOTIFY_EVENT_DESTROY: notify_system_event_t = 1;
pub const notify_system_event_t_NOTIFY_EVENT_TELEPORT: notify_system_event_t = 0;
#[repr(C)]
#[derive(Debug)]
pub struct CGlobalEntityList {
    pub _base: CBaseEntityList,
    pub m_iHighestEnt: ::std::os::raw::c_int,
    pub m_iNumEnts: ::std::os::raw::c_int,
    pub m_iNumEdicts: ::std::os::raw::c_int,
    pub m_bClearingEntities: bool,
    pub m_entityListeners: CUtlVector<
        *mut IEntityListener,
        CUtlMemory<*mut IEntityListener>,
    >,
}
#[repr(C)]
pub struct CGlobalEntityList__bindgen_vtable {
    /// C++ takes `::CBaseHandle` by value. `arg3` points to a temporary copy the caller makes; the callee may modify it, and the callee destroys it.
    pub CGlobalEntityList_OnAddEntity: unsafe extern "C" fn(
        arg1: *mut CGlobalEntityList,
        arg2: *mut IHandleEntity,
        arg3: *mut CBaseHandle,
    ),
    /// C++ takes `::CBaseHandle` by value. `arg3` points to a temporary copy the caller makes; the callee may modify it, and the callee destroys it.
    pub CGlobalEntityList_OnRemoveEntity: unsafe extern "C" fn(
        arg1: *mut CGlobalEntityList,
        arg2: *mut IHandleEntity,
        arg3: *mut CBaseHandle,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IEntityFindFilter {
    pub vtable_: *const IEntityFindFilter__bindgen_vtable,
}
#[repr(C)]
pub struct IEntityFindFilter__bindgen_vtable {
    pub IEntityFindFilter_ShouldFindEntity: unsafe extern "C" fn(
        arg1: *mut IEntityFindFilter,
        arg2: *mut CBaseEntity,
    ) -> bool,
    pub IEntityFindFilter_GetFilterResult: unsafe extern "C" fn(
        arg1: *mut IEntityFindFilter,
    ) -> *mut CBaseEntity,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IEntityListener {
    pub vtable_: *const IEntityListener__bindgen_vtable,
}
#[repr(C)]
pub struct IEntityListener__bindgen_vtable {
    pub IEntityListener_OnEntityCreated: unsafe extern "C" fn(
        arg1: *mut IEntityListener,
        arg2: *mut CBaseEntity,
    ),
    pub IEntityListener_OnEntitySpawned: unsafe extern "C" fn(
        arg1: *mut IEntityListener,
        arg2: *mut CBaseEntity,
    ),
    pub IEntityListener_OnEntityDeleted: unsafe extern "C" fn(
        arg1: *mut IEntityListener,
        arg2: *mut CBaseEntity,
    ),
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct notify_destroy_params_t {
    pub _address: u8,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct notify_system_event_params_t {
    pub __bindgen_anon_1: notify_system_event_params_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union notify_system_event_params_t__bindgen_ty_1 {
    pub pTeleport: *const notify_teleport_params_t,
    pub pDestroy: *const notify_destroy_params_t,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct notify_teleport_params_t {
    pub prevOrigin: Vector,
    pub prevAngles: QAngle,
    pub physicsRotate: bool,
}
include!("layout_assertions.rs");
